// Code generated by cmd/gen-tools. DO NOT EDIT.
// Source: docs/api/openapi.yml

package tools

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strings"

	"github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"

	signozclient "github.com/SigNoz/signoz-mcp-server/internal/client"
	gentypes "github.com/SigNoz/signoz-mcp-server/pkg/types/gentools"
)

// Reference every import unconditionally so tags without (say) path or
// query params still compile. These blanks are free at runtime.
var (
	_ = context.Background
	_ = fmt.Sprintf
	_ = http.MethodGet
	_ url.Values
	_ = strings.ReplaceAll
	_ = signozclient.DefaultQueryTimeout
	_ = mcp.NewTool
	_ server.MCPServer
)

// registerDashboardGenerated registers all generated tools for the
// "dashboard" OpenAPI tag.
func (h *Handler) registerDashboardGenerated(s *server.MCPServer) {
	h.genRegisterCreatePublicDashboard(s)
	h.genRegisterDeletePublicDashboard(s)
	h.genRegisterGetPublicDashboardWidgetQueryRange(s)
	h.genRegisterUpdatePublicDashboard(s)
}

func (h *Handler) genRegisterCreatePublicDashboard(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_create_public_dashboard",
		"This endpoint creates public sharing config and enables public sharing of the dashboard",
		gentypes.SchemaCreatePublicDashboard,
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleCreatePublicDashboard))
}

func (h *Handler) genHandleCreatePublicDashboard(ctx context.Context, req mcp.CallToolRequest, in gentypes.CreatePublicDashboardInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/dashboards/{id}/public"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	res, err := c.Do(ctx, http.MethodPost, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterDeletePublicDashboard(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_delete_public_dashboard",
		"This endpoint deletes the public sharing config and disables the public sharing of a dashboard",
		gentypes.SchemaDeletePublicDashboard,
	)
	destructive := true
	tool.Annotations.DestructiveHint = &destructive
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleDeletePublicDashboard))
}

func (h *Handler) genHandleDeletePublicDashboard(ctx context.Context, req mcp.CallToolRequest, in gentypes.DeletePublicDashboardInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/dashboards/{id}/public"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	res, err := c.Do(ctx, http.MethodDelete, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterGetPublicDashboardWidgetQueryRange(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_get_public_dashboard_widget_query_range",
		"This endpoint return query range results for a widget of public dashboard",
		gentypes.SchemaGetPublicDashboardWidgetQueryRange,
	)
	readOnly := true
	tool.Annotations.ReadOnlyHint = &readOnly
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleGetPublicDashboardWidgetQueryRange))
}

func (h *Handler) genHandleGetPublicDashboardWidgetQueryRange(ctx context.Context, req mcp.CallToolRequest, in gentypes.GetPublicDashboardWidgetQueryRangeInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/public/dashboards/{id}/widgets/{idx}/query_range"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))
	if in.Idx == "" {
		return mcp.NewToolResultError("missing required path parameter \"idx\""), nil
	}
	path = strings.ReplaceAll(path, "{idx}", url.PathEscape(in.Idx))

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterUpdatePublicDashboard(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_update_public_dashboard",
		"This endpoint updates the public sharing config for a dashboard",
		gentypes.SchemaUpdatePublicDashboard,
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleUpdatePublicDashboard))
}

func (h *Handler) genHandleUpdatePublicDashboard(ctx context.Context, req mcp.CallToolRequest, in gentypes.UpdatePublicDashboardInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/dashboards/{id}/public"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	res, err := c.Do(ctx, http.MethodPut, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}
