// Code generated by cmd/gen-tools. DO NOT EDIT.
// Source: docs/api/openapi.yml

package tools

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strings"

	"github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"

	signozclient "github.com/SigNoz/signoz-mcp-server/internal/client"
	gentypes "github.com/SigNoz/signoz-mcp-server/pkg/types/gentools"
)

// Reference every import unconditionally so tags without (say) path or
// query params still compile. These blanks are free at runtime.
var (
	_ = context.Background
	_ = fmt.Sprintf
	_ = http.MethodGet
	_ url.Values
	_ = strings.ReplaceAll
	_ = signozclient.DefaultQueryTimeout
	_ = mcp.NewTool
	_ server.MCPServer
)

// registerMetricsGenerated registers all generated tools for the
// "metrics" OpenAPI tag.
func (h *Handler) registerMetricsGenerated(s *server.MCPServer) {
	h.genRegisterGetMetricAlerts(s)
	h.genRegisterGetMetricAttributes(s)
	h.genRegisterGetMetricDashboards(s)
	h.genRegisterGetMetricHighlights(s)
	h.genRegisterGetMetricMetadata(s)
	h.genRegisterGetMetricsOnboardingStatus(s)
	h.genRegisterGetMetricsStats(s)
	h.genRegisterGetMetricsTreemap(s)
	h.genRegisterInspectMetrics(s)
	h.genRegisterUpdateMetricMetadata(s)
}

func (h *Handler) genRegisterGetMetricAlerts(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_get_metric_alerts",
		mcp.WithDescription("GET /api/v2/metrics/{metric_name}/alerts — Get metric alerts"),
		mcp.WithReadOnlyHintAnnotation(true),
		withRawSchema(gentypes.SchemaGetMetricAlerts),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleGetMetricAlerts))
}

func (h *Handler) genHandleGetMetricAlerts(ctx context.Context, req mcp.CallToolRequest, in gentypes.GetMetricAlertsInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/metrics/{metric_name}/alerts"
	if in.MetricName == "" {
		return mcp.NewToolResultError("missing required path parameter \"metric_name\""), nil
	}
	path = strings.ReplaceAll(path, "{metric_name}", url.PathEscape(in.MetricName))

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterGetMetricAttributes(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_get_metric_attributes",
		mcp.WithDescription("GET /api/v2/metrics/{metric_name}/attributes — Get metric attributes"),
		mcp.WithReadOnlyHintAnnotation(true),
		withRawSchema(gentypes.SchemaGetMetricAttributes),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleGetMetricAttributes))
}

func (h *Handler) genHandleGetMetricAttributes(ctx context.Context, req mcp.CallToolRequest, in gentypes.GetMetricAttributesInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/metrics/{metric_name}/attributes"
	if in.MetricName == "" {
		return mcp.NewToolResultError("missing required path parameter \"metric_name\""), nil
	}
	path = strings.ReplaceAll(path, "{metric_name}", url.PathEscape(in.MetricName))

	q := url.Values{}
	if in.Start != 0 {
		q.Set("start", fmt.Sprintf("%d", in.Start))
	}
	if in.End != 0 {
		q.Set("end", fmt.Sprintf("%d", in.End))
	}
	if len(q) > 0 {
		path += "?" + q.Encode()
	}

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterGetMetricDashboards(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_get_metric_dashboards",
		mcp.WithDescription("GET /api/v2/metrics/{metric_name}/dashboards — Get metric dashboards"),
		mcp.WithReadOnlyHintAnnotation(true),
		withRawSchema(gentypes.SchemaGetMetricDashboards),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleGetMetricDashboards))
}

func (h *Handler) genHandleGetMetricDashboards(ctx context.Context, req mcp.CallToolRequest, in gentypes.GetMetricDashboardsInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/metrics/{metric_name}/dashboards"
	if in.MetricName == "" {
		return mcp.NewToolResultError("missing required path parameter \"metric_name\""), nil
	}
	path = strings.ReplaceAll(path, "{metric_name}", url.PathEscape(in.MetricName))

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterGetMetricHighlights(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_get_metric_highlights",
		mcp.WithDescription("GET /api/v2/metrics/{metric_name}/highlights — Get metric highlights"),
		mcp.WithReadOnlyHintAnnotation(true),
		withRawSchema(gentypes.SchemaGetMetricHighlights),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleGetMetricHighlights))
}

func (h *Handler) genHandleGetMetricHighlights(ctx context.Context, req mcp.CallToolRequest, in gentypes.GetMetricHighlightsInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/metrics/{metric_name}/highlights"
	if in.MetricName == "" {
		return mcp.NewToolResultError("missing required path parameter \"metric_name\""), nil
	}
	path = strings.ReplaceAll(path, "{metric_name}", url.PathEscape(in.MetricName))

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterGetMetricMetadata(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_get_metric_metadata",
		mcp.WithDescription("GET /api/v2/metrics/{metric_name}/metadata — Get metric metadata"),
		mcp.WithReadOnlyHintAnnotation(true),
		withRawSchema(gentypes.SchemaGetMetricMetadata),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleGetMetricMetadata))
}

func (h *Handler) genHandleGetMetricMetadata(ctx context.Context, req mcp.CallToolRequest, in gentypes.GetMetricMetadataInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/metrics/{metric_name}/metadata"
	if in.MetricName == "" {
		return mcp.NewToolResultError("missing required path parameter \"metric_name\""), nil
	}
	path = strings.ReplaceAll(path, "{metric_name}", url.PathEscape(in.MetricName))

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterGetMetricsOnboardingStatus(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_get_metrics_onboarding_status",
		mcp.WithDescription("GET /api/v2/metrics/onboarding — Check if non-SigNoz metrics have been received"),
		mcp.WithReadOnlyHintAnnotation(true),
		withRawSchema(gentypes.SchemaGetMetricsOnboardingStatus),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleGetMetricsOnboardingStatus))
}

func (h *Handler) genHandleGetMetricsOnboardingStatus(ctx context.Context, req mcp.CallToolRequest, in gentypes.GetMetricsOnboardingStatusInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/metrics/onboarding"

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterGetMetricsStats(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_get_metrics_stats",
		mcp.WithDescription("POST /api/v2/metrics/stats — Get metrics statistics"),
		withRawSchema(gentypes.SchemaGetMetricsStats),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleGetMetricsStats))
}

func (h *Handler) genHandleGetMetricsStats(ctx context.Context, req mcp.CallToolRequest, in gentypes.GetMetricsStatsInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/metrics/stats"

	res, err := c.Do(ctx, http.MethodPost, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterGetMetricsTreemap(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_get_metrics_treemap",
		mcp.WithDescription("POST /api/v2/metrics/treemap — Get metrics treemap"),
		withRawSchema(gentypes.SchemaGetMetricsTreemap),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleGetMetricsTreemap))
}

func (h *Handler) genHandleGetMetricsTreemap(ctx context.Context, req mcp.CallToolRequest, in gentypes.GetMetricsTreemapInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/metrics/treemap"

	res, err := c.Do(ctx, http.MethodPost, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterInspectMetrics(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_inspect_metrics",
		mcp.WithDescription("POST /api/v2/metrics/inspect — Inspect raw metric data points"),
		withRawSchema(gentypes.SchemaInspectMetrics),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleInspectMetrics))
}

func (h *Handler) genHandleInspectMetrics(ctx context.Context, req mcp.CallToolRequest, in gentypes.InspectMetricsInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/metrics/inspect"

	res, err := c.Do(ctx, http.MethodPost, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterUpdateMetricMetadata(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_update_metric_metadata",
		mcp.WithDescription("POST /api/v2/metrics/{metric_name}/metadata — Update metric metadata"),
		withRawSchema(gentypes.SchemaUpdateMetricMetadata),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleUpdateMetricMetadata))
}

func (h *Handler) genHandleUpdateMetricMetadata(ctx context.Context, req mcp.CallToolRequest, in gentypes.UpdateMetricMetadataInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/metrics/{metric_name}/metadata"
	if in.MetricName == "" {
		return mcp.NewToolResultError("missing required path parameter \"metric_name\""), nil
	}
	path = strings.ReplaceAll(path, "{metric_name}", url.PathEscape(in.MetricName))

	res, err := c.Do(ctx, http.MethodPost, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}
