// Code generated by cmd/gen-tools. DO NOT EDIT.
// Source: docs/api/openapi.yml

package tools

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strings"

	"github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"

	signozclient "github.com/SigNoz/signoz-mcp-server/internal/client"
	gentypes "github.com/SigNoz/signoz-mcp-server/pkg/types/gentools"
)

// Reference every import unconditionally so tags without (say) path or
// query params still compile. These blanks are free at runtime.
var (
	_ = context.Background
	_ = fmt.Sprintf
	_ = http.MethodGet
	_ url.Values
	_ = strings.ReplaceAll
	_ = signozclient.DefaultQueryTimeout
	_ = mcp.NewTool
	_ server.MCPServer
)

// registerZeusGenerated registers all generated tools for the
// "zeus" OpenAPI tag.
func (h *Handler) registerZeusGenerated(s *server.MCPServer) {
	h.genRegisterGetHosts(s)
	h.genRegisterPutHost(s)
	h.genRegisterPutProfile(s)
}

func (h *Handler) genRegisterGetHosts(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_get_hosts",
		"This endpoint gets the host info from zeus.",
		gentypes.SchemaGetHosts,
	)
	readOnly := true
	tool.Annotations.ReadOnlyHint = &readOnly
	tool.RawOutputSchema = gentypes.OutputSchemaGetHosts
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleGetHosts))
}

func (h *Handler) genHandleGetHosts(ctx context.Context, req mcp.CallToolRequest, in gentypes.GetHostsInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/zeus/hosts"

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterPutHost(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_put_host",
		"This endpoint saves the host of a deployment to zeus.",
		gentypes.SchemaPutHost,
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandlePutHost))
}

func (h *Handler) genHandlePutHost(ctx context.Context, req mcp.CallToolRequest, in gentypes.PutHostInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/zeus/hosts"

	res, err := c.Do(ctx, http.MethodPut, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterPutProfile(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_put_profile",
		"This endpoint saves the profile of a deployment to zeus.",
		gentypes.SchemaPutProfile,
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandlePutProfile))
}

func (h *Handler) genHandlePutProfile(ctx context.Context, req mcp.CallToolRequest, in gentypes.PutProfileInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/zeus/profiles"

	res, err := c.Do(ctx, http.MethodPut, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}
