// Code generated by cmd/gen-tools. DO NOT EDIT.
// Source: docs/api/openapi.yml

package tools

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strings"

	"github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"

	signozclient "github.com/SigNoz/signoz-mcp-server/internal/client"
	gentypes "github.com/SigNoz/signoz-mcp-server/pkg/types/gentools"
)

// Reference every import unconditionally so tags without (say) path or
// query params still compile. These blanks are free at runtime.
var (
	_ = context.Background
	_ = fmt.Sprintf
	_ = http.MethodGet
	_ url.Values
	_ = strings.ReplaceAll
	_ = signozclient.DefaultQueryTimeout
	_ = mcp.NewTool
	_ server.MCPServer
)

// registerPreferencesGenerated registers all generated tools for the
// "preferences" OpenAPI tag.
func (h *Handler) registerPreferencesGenerated(s *server.MCPServer) {
	h.genRegisterGetOrgPreference(s)
	h.genRegisterGetUserPreference(s)
	h.genRegisterListOrgPreferences(s)
	h.genRegisterListUserPreferences(s)
	h.genRegisterUpdateOrgPreference(s)
	h.genRegisterUpdateUserPreference(s)
}

func (h *Handler) genRegisterGetOrgPreference(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_get_org_preference",
		mcp.WithDescription("GET /api/v1/org/preferences/{name} — Get org preference"),
		mcp.WithReadOnlyHintAnnotation(true),
		withRawSchema(gentypes.SchemaGetOrgPreference),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleGetOrgPreference))
}

func (h *Handler) genHandleGetOrgPreference(ctx context.Context, req mcp.CallToolRequest, in gentypes.GetOrgPreferenceInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/org/preferences/{name}"
	if in.Name == "" {
		return mcp.NewToolResultError("missing required path parameter \"name\""), nil
	}
	path = strings.ReplaceAll(path, "{name}", url.PathEscape(in.Name))

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterGetUserPreference(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_get_user_preference",
		mcp.WithDescription("GET /api/v1/user/preferences/{name} — Get user preference"),
		mcp.WithReadOnlyHintAnnotation(true),
		withRawSchema(gentypes.SchemaGetUserPreference),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleGetUserPreference))
}

func (h *Handler) genHandleGetUserPreference(ctx context.Context, req mcp.CallToolRequest, in gentypes.GetUserPreferenceInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/user/preferences/{name}"
	if in.Name == "" {
		return mcp.NewToolResultError("missing required path parameter \"name\""), nil
	}
	path = strings.ReplaceAll(path, "{name}", url.PathEscape(in.Name))

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterListOrgPreferences(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_list_org_preferences",
		mcp.WithDescription("GET /api/v1/org/preferences — List org preferences"),
		mcp.WithReadOnlyHintAnnotation(true),
		withRawSchema(gentypes.SchemaListOrgPreferences),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleListOrgPreferences))
}

func (h *Handler) genHandleListOrgPreferences(ctx context.Context, req mcp.CallToolRequest, in gentypes.ListOrgPreferencesInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/org/preferences"

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterListUserPreferences(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_list_user_preferences",
		mcp.WithDescription("GET /api/v1/user/preferences — List user preferences"),
		mcp.WithReadOnlyHintAnnotation(true),
		withRawSchema(gentypes.SchemaListUserPreferences),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleListUserPreferences))
}

func (h *Handler) genHandleListUserPreferences(ctx context.Context, req mcp.CallToolRequest, in gentypes.ListUserPreferencesInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/user/preferences"

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterUpdateOrgPreference(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_update_org_preference",
		mcp.WithDescription("PUT /api/v1/org/preferences/{name} — Update org preference"),
		withRawSchema(gentypes.SchemaUpdateOrgPreference),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleUpdateOrgPreference))
}

func (h *Handler) genHandleUpdateOrgPreference(ctx context.Context, req mcp.CallToolRequest, in gentypes.UpdateOrgPreferenceInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/org/preferences/{name}"
	if in.Name == "" {
		return mcp.NewToolResultError("missing required path parameter \"name\""), nil
	}
	path = strings.ReplaceAll(path, "{name}", url.PathEscape(in.Name))

	res, err := c.Do(ctx, http.MethodPut, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterUpdateUserPreference(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_update_user_preference",
		mcp.WithDescription("PUT /api/v1/user/preferences/{name} — Update user preference"),
		withRawSchema(gentypes.SchemaUpdateUserPreference),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleUpdateUserPreference))
}

func (h *Handler) genHandleUpdateUserPreference(ctx context.Context, req mcp.CallToolRequest, in gentypes.UpdateUserPreferenceInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/user/preferences/{name}"
	if in.Name == "" {
		return mcp.NewToolResultError("missing required path parameter \"name\""), nil
	}
	path = strings.ReplaceAll(path, "{name}", url.PathEscape(in.Name))

	res, err := c.Do(ctx, http.MethodPut, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}
