// Code generated by cmd/gen-tools. DO NOT EDIT.
// Source: docs/api/openapi.yml

package tools

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strings"

	"github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"

	signozclient "github.com/SigNoz/signoz-mcp-server/internal/client"
	gentypes "github.com/SigNoz/signoz-mcp-server/pkg/types/gentools"
)

// Reference every import unconditionally so tags without (say) path or
// query params still compile. These blanks are free at runtime.
var (
	_ = context.Background
	_ = fmt.Sprintf
	_ = http.MethodGet
	_ url.Values
	_ = strings.ReplaceAll
	_ = signozclient.DefaultQueryTimeout
	_ = mcp.NewTool
	_ server.MCPServer
)

// registerServiceaccountGenerated registers all generated tools for the
// "serviceaccount" OpenAPI tag.
func (h *Handler) registerServiceaccountGenerated(s *server.MCPServer) {
	h.genRegisterCreateServiceAccount(s)
	h.genRegisterCreateServiceAccountKey(s)
	h.genRegisterCreateServiceAccountRole(s)
	h.genRegisterDeleteServiceAccount(s)
	h.genRegisterDeleteServiceAccountRole(s)
	h.genRegisterGetMyServiceAccount(s)
	h.genRegisterGetServiceAccount(s)
	h.genRegisterGetServiceAccountRoles(s)
	h.genRegisterListServiceAccountKeys(s)
	h.genRegisterListServiceAccounts(s)
	h.genRegisterRevokeServiceAccountKey(s)
	h.genRegisterUpdateMyServiceAccount(s)
	h.genRegisterUpdateServiceAccount(s)
	h.genRegisterUpdateServiceAccountKey(s)
}

func (h *Handler) genRegisterCreateServiceAccount(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_create_service_account",
		"This endpoint creates a service account",
		gentypes.SchemaCreateServiceAccount,
	)
	tool.RawOutputSchema = gentypes.OutputSchemaCreateServiceAccount
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleCreateServiceAccount))
}

func (h *Handler) genHandleCreateServiceAccount(ctx context.Context, req mcp.CallToolRequest, in gentypes.CreateServiceAccountInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/service_accounts"

	res, err := c.Do(ctx, http.MethodPost, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterCreateServiceAccountKey(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_create_service_account_key",
		"This endpoint creates a service account key",
		gentypes.SchemaCreateServiceAccountKey,
	)
	tool.RawOutputSchema = gentypes.OutputSchemaCreateServiceAccountKey
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleCreateServiceAccountKey))
}

func (h *Handler) genHandleCreateServiceAccountKey(ctx context.Context, req mcp.CallToolRequest, in gentypes.CreateServiceAccountKeyInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/service_accounts/{id}/keys"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	res, err := c.Do(ctx, http.MethodPost, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterCreateServiceAccountRole(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_create_service_account_role",
		"This endpoint assigns a role to a service account",
		gentypes.SchemaCreateServiceAccountRole,
	)
	tool.RawOutputSchema = gentypes.OutputSchemaCreateServiceAccountRole
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleCreateServiceAccountRole))
}

func (h *Handler) genHandleCreateServiceAccountRole(ctx context.Context, req mcp.CallToolRequest, in gentypes.CreateServiceAccountRoleInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/service_accounts/{id}/roles"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	res, err := c.Do(ctx, http.MethodPost, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterDeleteServiceAccount(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_delete_service_account",
		"This endpoint deletes an existing service account",
		gentypes.SchemaDeleteServiceAccount,
	)
	destructive := true
	tool.Annotations.DestructiveHint = &destructive
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleDeleteServiceAccount))
}

func (h *Handler) genHandleDeleteServiceAccount(ctx context.Context, req mcp.CallToolRequest, in gentypes.DeleteServiceAccountInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/service_accounts/{id}"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	res, err := c.Do(ctx, http.MethodDelete, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterDeleteServiceAccountRole(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_delete_service_account_role",
		"This endpoint revokes a role from service account",
		gentypes.SchemaDeleteServiceAccountRole,
	)
	destructive := true
	tool.Annotations.DestructiveHint = &destructive
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleDeleteServiceAccountRole))
}

func (h *Handler) genHandleDeleteServiceAccountRole(ctx context.Context, req mcp.CallToolRequest, in gentypes.DeleteServiceAccountRoleInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/service_accounts/{id}/roles/{rid}"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))
	if in.Rid == "" {
		return mcp.NewToolResultError("missing required path parameter \"rid\""), nil
	}
	path = strings.ReplaceAll(path, "{rid}", url.PathEscape(in.Rid))

	res, err := c.Do(ctx, http.MethodDelete, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterGetMyServiceAccount(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_get_my_service_account",
		"This endpoint gets my service account",
		gentypes.SchemaGetMyServiceAccount,
	)
	readOnly := true
	tool.Annotations.ReadOnlyHint = &readOnly
	tool.RawOutputSchema = gentypes.OutputSchemaGetMyServiceAccount
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleGetMyServiceAccount))
}

func (h *Handler) genHandleGetMyServiceAccount(ctx context.Context, req mcp.CallToolRequest, in gentypes.GetMyServiceAccountInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/service_accounts/me"

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterGetServiceAccount(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_get_service_account",
		"This endpoint gets an existing service account",
		gentypes.SchemaGetServiceAccount,
	)
	readOnly := true
	tool.Annotations.ReadOnlyHint = &readOnly
	tool.RawOutputSchema = gentypes.OutputSchemaGetServiceAccount
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleGetServiceAccount))
}

func (h *Handler) genHandleGetServiceAccount(ctx context.Context, req mcp.CallToolRequest, in gentypes.GetServiceAccountInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/service_accounts/{id}"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterGetServiceAccountRoles(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_get_service_account_roles",
		"This endpoint gets all the roles for the existing service account",
		gentypes.SchemaGetServiceAccountRoles,
	)
	readOnly := true
	tool.Annotations.ReadOnlyHint = &readOnly
	tool.RawOutputSchema = gentypes.OutputSchemaGetServiceAccountRoles
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleGetServiceAccountRoles))
}

func (h *Handler) genHandleGetServiceAccountRoles(ctx context.Context, req mcp.CallToolRequest, in gentypes.GetServiceAccountRolesInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/service_accounts/{id}/roles"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterListServiceAccountKeys(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_list_service_account_keys",
		"This endpoint lists the service account keys",
		gentypes.SchemaListServiceAccountKeys,
	)
	readOnly := true
	tool.Annotations.ReadOnlyHint = &readOnly
	tool.RawOutputSchema = gentypes.OutputSchemaListServiceAccountKeys
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleListServiceAccountKeys))
}

func (h *Handler) genHandleListServiceAccountKeys(ctx context.Context, req mcp.CallToolRequest, in gentypes.ListServiceAccountKeysInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/service_accounts/{id}/keys"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterListServiceAccounts(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_list_service_accounts",
		"This endpoint lists the service accounts for an organisation",
		gentypes.SchemaListServiceAccounts,
	)
	readOnly := true
	tool.Annotations.ReadOnlyHint = &readOnly
	tool.RawOutputSchema = gentypes.OutputSchemaListServiceAccounts
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleListServiceAccounts))
}

func (h *Handler) genHandleListServiceAccounts(ctx context.Context, req mcp.CallToolRequest, in gentypes.ListServiceAccountsInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/service_accounts"

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterRevokeServiceAccountKey(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_revoke_service_account_key",
		"This endpoint revokes an existing service account key",
		gentypes.SchemaRevokeServiceAccountKey,
	)
	destructive := true
	tool.Annotations.DestructiveHint = &destructive
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleRevokeServiceAccountKey))
}

func (h *Handler) genHandleRevokeServiceAccountKey(ctx context.Context, req mcp.CallToolRequest, in gentypes.RevokeServiceAccountKeyInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/service_accounts/{id}/keys/{fid}"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))
	if in.Fid == "" {
		return mcp.NewToolResultError("missing required path parameter \"fid\""), nil
	}
	path = strings.ReplaceAll(path, "{fid}", url.PathEscape(in.Fid))

	res, err := c.Do(ctx, http.MethodDelete, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterUpdateMyServiceAccount(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_update_my_service_account",
		"This endpoint gets my service account",
		gentypes.SchemaUpdateMyServiceAccount,
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleUpdateMyServiceAccount))
}

func (h *Handler) genHandleUpdateMyServiceAccount(ctx context.Context, req mcp.CallToolRequest, in gentypes.UpdateMyServiceAccountInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/service_accounts/me"

	res, err := c.Do(ctx, http.MethodPut, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterUpdateServiceAccount(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_update_service_account",
		"This endpoint updates an existing service account",
		gentypes.SchemaUpdateServiceAccount,
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleUpdateServiceAccount))
}

func (h *Handler) genHandleUpdateServiceAccount(ctx context.Context, req mcp.CallToolRequest, in gentypes.UpdateServiceAccountInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/service_accounts/{id}"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	res, err := c.Do(ctx, http.MethodPut, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterUpdateServiceAccountKey(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_update_service_account_key",
		"This endpoint updates an existing service account key",
		gentypes.SchemaUpdateServiceAccountKey,
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleUpdateServiceAccountKey))
}

func (h *Handler) genHandleUpdateServiceAccountKey(ctx context.Context, req mcp.CallToolRequest, in gentypes.UpdateServiceAccountKeyInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/service_accounts/{id}/keys/{fid}"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))
	if in.Fid == "" {
		return mcp.NewToolResultError("missing required path parameter \"fid\""), nil
	}
	path = strings.ReplaceAll(path, "{fid}", url.PathEscape(in.Fid))

	res, err := c.Do(ctx, http.MethodPut, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}
