// Code generated by cmd/gen-tools. DO NOT EDIT.
// Source: docs/api/openapi.yml

package tools

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strings"

	"github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"

	signozclient "github.com/SigNoz/signoz-mcp-server/internal/client"
	gentypes "github.com/SigNoz/signoz-mcp-server/pkg/types/gentools"
)

// Reference every import unconditionally so tags without (say) path or
// query params still compile. These blanks are free at runtime.
var (
	_ = context.Background
	_ = fmt.Sprintf
	_ = http.MethodGet
	_ url.Values
	_ = strings.ReplaceAll
	_ = signozclient.DefaultQueryTimeout
	_ = mcp.NewTool
	_ server.MCPServer
)

// registerServiceaccountGenerated registers all generated tools for the
// "serviceaccount" OpenAPI tag.
func (h *Handler) registerServiceaccountGenerated(s *server.MCPServer) {
	h.genRegisterCreateServiceAccount(s)
	h.genRegisterCreateServiceAccountKey(s)
	h.genRegisterCreateServiceAccountRole(s)
	h.genRegisterDeleteServiceAccount(s)
	h.genRegisterDeleteServiceAccountRole(s)
	h.genRegisterGetMyServiceAccount(s)
	h.genRegisterGetServiceAccount(s)
	h.genRegisterGetServiceAccountRoles(s)
	h.genRegisterListServiceAccountKeys(s)
	h.genRegisterListServiceAccounts(s)
	h.genRegisterRevokeServiceAccountKey(s)
	h.genRegisterUpdateMyServiceAccount(s)
	h.genRegisterUpdateServiceAccount(s)
	h.genRegisterUpdateServiceAccountKey(s)
}

func (h *Handler) genRegisterCreateServiceAccount(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_create_service_account",
		mcp.WithDescription("POST /api/v1/service_accounts — Create service account"),
		withRawSchema(gentypes.SchemaCreateServiceAccount),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleCreateServiceAccount))
}

func (h *Handler) genHandleCreateServiceAccount(ctx context.Context, req mcp.CallToolRequest, in gentypes.CreateServiceAccountInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/service_accounts"

	res, err := c.Do(ctx, http.MethodPost, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterCreateServiceAccountKey(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_create_service_account_key",
		mcp.WithDescription("POST /api/v1/service_accounts/{id}/keys — Create a service account key"),
		withRawSchema(gentypes.SchemaCreateServiceAccountKey),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleCreateServiceAccountKey))
}

func (h *Handler) genHandleCreateServiceAccountKey(ctx context.Context, req mcp.CallToolRequest, in gentypes.CreateServiceAccountKeyInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/service_accounts/{id}/keys"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	res, err := c.Do(ctx, http.MethodPost, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterCreateServiceAccountRole(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_create_service_account_role",
		mcp.WithDescription("POST /api/v1/service_accounts/{id}/roles — Create service account role"),
		withRawSchema(gentypes.SchemaCreateServiceAccountRole),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleCreateServiceAccountRole))
}

func (h *Handler) genHandleCreateServiceAccountRole(ctx context.Context, req mcp.CallToolRequest, in gentypes.CreateServiceAccountRoleInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/service_accounts/{id}/roles"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	res, err := c.Do(ctx, http.MethodPost, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterDeleteServiceAccount(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_delete_service_account",
		mcp.WithDescription("DELETE /api/v1/service_accounts/{id} — Deletes a service account"),
		mcp.WithDestructiveHintAnnotation(true),
		withRawSchema(gentypes.SchemaDeleteServiceAccount),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleDeleteServiceAccount))
}

func (h *Handler) genHandleDeleteServiceAccount(ctx context.Context, req mcp.CallToolRequest, in gentypes.DeleteServiceAccountInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/service_accounts/{id}"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	res, err := c.Do(ctx, http.MethodDelete, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterDeleteServiceAccountRole(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_delete_service_account_role",
		mcp.WithDescription("DELETE /api/v1/service_accounts/{id}/roles/{rid} — Delete service account role"),
		mcp.WithDestructiveHintAnnotation(true),
		withRawSchema(gentypes.SchemaDeleteServiceAccountRole),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleDeleteServiceAccountRole))
}

func (h *Handler) genHandleDeleteServiceAccountRole(ctx context.Context, req mcp.CallToolRequest, in gentypes.DeleteServiceAccountRoleInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/service_accounts/{id}/roles/{rid}"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))
	if in.Rid == "" {
		return mcp.NewToolResultError("missing required path parameter \"rid\""), nil
	}
	path = strings.ReplaceAll(path, "{rid}", url.PathEscape(in.Rid))

	res, err := c.Do(ctx, http.MethodDelete, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterGetMyServiceAccount(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_get_my_service_account",
		mcp.WithDescription("GET /api/v1/service_accounts/me — Gets my service account"),
		mcp.WithReadOnlyHintAnnotation(true),
		withRawSchema(gentypes.SchemaGetMyServiceAccount),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleGetMyServiceAccount))
}

func (h *Handler) genHandleGetMyServiceAccount(ctx context.Context, req mcp.CallToolRequest, in gentypes.GetMyServiceAccountInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/service_accounts/me"

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterGetServiceAccount(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_get_service_account",
		mcp.WithDescription("GET /api/v1/service_accounts/{id} — Gets a service account"),
		mcp.WithReadOnlyHintAnnotation(true),
		withRawSchema(gentypes.SchemaGetServiceAccount),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleGetServiceAccount))
}

func (h *Handler) genHandleGetServiceAccount(ctx context.Context, req mcp.CallToolRequest, in gentypes.GetServiceAccountInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/service_accounts/{id}"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterGetServiceAccountRoles(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_get_service_account_roles",
		mcp.WithDescription("GET /api/v1/service_accounts/{id}/roles — Gets service account roles"),
		mcp.WithReadOnlyHintAnnotation(true),
		withRawSchema(gentypes.SchemaGetServiceAccountRoles),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleGetServiceAccountRoles))
}

func (h *Handler) genHandleGetServiceAccountRoles(ctx context.Context, req mcp.CallToolRequest, in gentypes.GetServiceAccountRolesInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/service_accounts/{id}/roles"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterListServiceAccountKeys(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_list_service_account_keys",
		mcp.WithDescription("GET /api/v1/service_accounts/{id}/keys — List service account keys"),
		mcp.WithReadOnlyHintAnnotation(true),
		withRawSchema(gentypes.SchemaListServiceAccountKeys),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleListServiceAccountKeys))
}

func (h *Handler) genHandleListServiceAccountKeys(ctx context.Context, req mcp.CallToolRequest, in gentypes.ListServiceAccountKeysInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/service_accounts/{id}/keys"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterListServiceAccounts(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_list_service_accounts",
		mcp.WithDescription("GET /api/v1/service_accounts — List service accounts"),
		mcp.WithReadOnlyHintAnnotation(true),
		withRawSchema(gentypes.SchemaListServiceAccounts),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleListServiceAccounts))
}

func (h *Handler) genHandleListServiceAccounts(ctx context.Context, req mcp.CallToolRequest, in gentypes.ListServiceAccountsInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/service_accounts"

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterRevokeServiceAccountKey(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_revoke_service_account_key",
		mcp.WithDescription("DELETE /api/v1/service_accounts/{id}/keys/{fid} — Revoke a service account key"),
		mcp.WithDestructiveHintAnnotation(true),
		withRawSchema(gentypes.SchemaRevokeServiceAccountKey),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleRevokeServiceAccountKey))
}

func (h *Handler) genHandleRevokeServiceAccountKey(ctx context.Context, req mcp.CallToolRequest, in gentypes.RevokeServiceAccountKeyInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/service_accounts/{id}/keys/{fid}"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))
	if in.Fid == "" {
		return mcp.NewToolResultError("missing required path parameter \"fid\""), nil
	}
	path = strings.ReplaceAll(path, "{fid}", url.PathEscape(in.Fid))

	res, err := c.Do(ctx, http.MethodDelete, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterUpdateMyServiceAccount(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_update_my_service_account",
		mcp.WithDescription("PUT /api/v1/service_accounts/me — Updates my service account"),
		withRawSchema(gentypes.SchemaUpdateMyServiceAccount),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleUpdateMyServiceAccount))
}

func (h *Handler) genHandleUpdateMyServiceAccount(ctx context.Context, req mcp.CallToolRequest, in gentypes.UpdateMyServiceAccountInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/service_accounts/me"

	res, err := c.Do(ctx, http.MethodPut, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterUpdateServiceAccount(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_update_service_account",
		mcp.WithDescription("PUT /api/v1/service_accounts/{id} — Updates a service account"),
		withRawSchema(gentypes.SchemaUpdateServiceAccount),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleUpdateServiceAccount))
}

func (h *Handler) genHandleUpdateServiceAccount(ctx context.Context, req mcp.CallToolRequest, in gentypes.UpdateServiceAccountInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/service_accounts/{id}"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	res, err := c.Do(ctx, http.MethodPut, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterUpdateServiceAccountKey(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_update_service_account_key",
		mcp.WithDescription("PUT /api/v1/service_accounts/{id}/keys/{fid} — Updates a service account key"),
		withRawSchema(gentypes.SchemaUpdateServiceAccountKey),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleUpdateServiceAccountKey))
}

func (h *Handler) genHandleUpdateServiceAccountKey(ctx context.Context, req mcp.CallToolRequest, in gentypes.UpdateServiceAccountKeyInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/service_accounts/{id}/keys/{fid}"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))
	if in.Fid == "" {
		return mcp.NewToolResultError("missing required path parameter \"fid\""), nil
	}
	path = strings.ReplaceAll(path, "{fid}", url.PathEscape(in.Fid))

	res, err := c.Do(ctx, http.MethodPut, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}
