// Code generated by cmd/gen-tools. DO NOT EDIT.
// Source: docs/api/openapi.yml

package tools

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strings"

	"github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"

	signozclient "github.com/SigNoz/signoz-mcp-server/internal/client"
	gentypes "github.com/SigNoz/signoz-mcp-server/pkg/types/gentools"
)

// Reference every import unconditionally so tags without (say) path or
// query params still compile. These blanks are free at runtime.
var (
	_ = context.Background
	_ = fmt.Sprintf
	_ = http.MethodGet
	_ url.Values
	_ = strings.ReplaceAll
	_ = signozclient.DefaultQueryTimeout
	_ = mcp.NewTool
	_ server.MCPServer
)

// registerOrgsGenerated registers all generated tools for the
// "orgs" OpenAPI tag.
func (h *Handler) registerOrgsGenerated(s *server.MCPServer) {
	h.genRegisterGetMyOrganization(s)
	h.genRegisterUpdateMyOrganization(s)
}

func (h *Handler) genRegisterGetMyOrganization(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_get_my_organization",
		mcp.WithDescription("GET /api/v2/orgs/me — Get my organization"),
		mcp.WithReadOnlyHintAnnotation(true),
		withRawSchema(gentypes.SchemaGetMyOrganization),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleGetMyOrganization))
}

func (h *Handler) genHandleGetMyOrganization(ctx context.Context, req mcp.CallToolRequest, in gentypes.GetMyOrganizationInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/orgs/me"

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterUpdateMyOrganization(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_update_my_organization",
		mcp.WithDescription("PUT /api/v2/orgs/me — Update my organization"),
		withRawSchema(gentypes.SchemaUpdateMyOrganization),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleUpdateMyOrganization))
}

func (h *Handler) genHandleUpdateMyOrganization(ctx context.Context, req mcp.CallToolRequest, in gentypes.UpdateMyOrganizationInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/orgs/me"

	res, err := c.Do(ctx, http.MethodPut, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}
