// Code generated by cmd/gen-tools. DO NOT EDIT.
// Source: docs/api/openapi.yml

package tools

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strings"

	"github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"

	signozclient "github.com/SigNoz/signoz-mcp-server/internal/client"
	gentypes "github.com/SigNoz/signoz-mcp-server/pkg/types/gentools"
)

// Reference every import unconditionally so tags without (say) path or
// query params still compile. These blanks are free at runtime.
var (
	_ = context.Background
	_ = fmt.Sprintf
	_ = http.MethodGet
	_ url.Values
	_ = strings.ReplaceAll
	_ = signozclient.DefaultQueryTimeout
	_ = mcp.NewTool
	_ server.MCPServer
)

// registerAuthdomainsGenerated registers all generated tools for the
// "authdomains" OpenAPI tag.
func (h *Handler) registerAuthdomainsGenerated(s *server.MCPServer) {
	h.genRegisterCreateAuthDomain(s)
	h.genRegisterDeleteAuthDomain(s)
	h.genRegisterListAuthDomains(s)
	h.genRegisterUpdateAuthDomain(s)
}

func (h *Handler) genRegisterCreateAuthDomain(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_create_auth_domain",
		mcp.WithDescription("POST /api/v1/domains — Create auth domain"),
		withRawSchema(gentypes.SchemaCreateAuthDomain),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleCreateAuthDomain))
}

func (h *Handler) genHandleCreateAuthDomain(ctx context.Context, req mcp.CallToolRequest, in gentypes.CreateAuthDomainInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/domains"

	res, err := c.Do(ctx, http.MethodPost, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterDeleteAuthDomain(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_delete_auth_domain",
		mcp.WithDescription("DELETE /api/v1/domains/{id} — Delete auth domain"),
		mcp.WithDestructiveHintAnnotation(true),
		withRawSchema(gentypes.SchemaDeleteAuthDomain),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleDeleteAuthDomain))
}

func (h *Handler) genHandleDeleteAuthDomain(ctx context.Context, req mcp.CallToolRequest, in gentypes.DeleteAuthDomainInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/domains/{id}"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	res, err := c.Do(ctx, http.MethodDelete, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterListAuthDomains(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_list_auth_domains",
		mcp.WithDescription("GET /api/v1/domains — List all auth domains"),
		mcp.WithReadOnlyHintAnnotation(true),
		withRawSchema(gentypes.SchemaListAuthDomains),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleListAuthDomains))
}

func (h *Handler) genHandleListAuthDomains(ctx context.Context, req mcp.CallToolRequest, in gentypes.ListAuthDomainsInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/domains"

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterUpdateAuthDomain(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_update_auth_domain",
		mcp.WithDescription("PUT /api/v1/domains/{id} — Update auth domain"),
		withRawSchema(gentypes.SchemaUpdateAuthDomain),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleUpdateAuthDomain))
}

func (h *Handler) genHandleUpdateAuthDomain(ctx context.Context, req mcp.CallToolRequest, in gentypes.UpdateAuthDomainInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/domains/{id}"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	res, err := c.Do(ctx, http.MethodPut, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}
