// Code generated by cmd/gen-tools. DO NOT EDIT.
// Source: docs/api/openapi.yml

package tools

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strings"

	"github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"

	signozclient "github.com/SigNoz/signoz-mcp-server/internal/client"
	gentypes "github.com/SigNoz/signoz-mcp-server/pkg/types/gentools"
)

// Reference every import unconditionally so tags without (say) path or
// query params still compile. These blanks are free at runtime.
var (
	_ = context.Background
	_ = fmt.Sprintf
	_ = http.MethodGet
	_ url.Values
	_ = strings.ReplaceAll
	_ = signozclient.DefaultQueryTimeout
	_ = mcp.NewTool
	_ server.MCPServer
)

// registerRoleGenerated registers all generated tools for the
// "role" OpenAPI tag.
func (h *Handler) registerRoleGenerated(s *server.MCPServer) {
	h.genRegisterCreateRole(s)
	h.genRegisterDeleteRole(s)
	h.genRegisterGetObjects(s)
	h.genRegisterGetRole(s)
	h.genRegisterListRoles(s)
	h.genRegisterPatchObjects(s)
	h.genRegisterPatchRole(s)
}

func (h *Handler) genRegisterCreateRole(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_create_role",
		mcp.WithDescription("POST /api/v1/roles — Create role"),
		withRawSchema(gentypes.SchemaCreateRole),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleCreateRole))
}

func (h *Handler) genHandleCreateRole(ctx context.Context, req mcp.CallToolRequest, in gentypes.CreateRoleInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/roles"

	res, err := c.Do(ctx, http.MethodPost, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterDeleteRole(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_delete_role",
		mcp.WithDescription("DELETE /api/v1/roles/{id} — Delete role"),
		mcp.WithDestructiveHintAnnotation(true),
		withRawSchema(gentypes.SchemaDeleteRole),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleDeleteRole))
}

func (h *Handler) genHandleDeleteRole(ctx context.Context, req mcp.CallToolRequest, in gentypes.DeleteRoleInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/roles/{id}"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	res, err := c.Do(ctx, http.MethodDelete, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterGetObjects(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_get_objects",
		mcp.WithDescription("GET /api/v1/roles/{id}/relations/{relation}/objects — Get objects for a role by relation"),
		mcp.WithReadOnlyHintAnnotation(true),
		withRawSchema(gentypes.SchemaGetObjects),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleGetObjects))
}

func (h *Handler) genHandleGetObjects(ctx context.Context, req mcp.CallToolRequest, in gentypes.GetObjectsInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/roles/{id}/relations/{relation}/objects"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))
	if in.Relation == "" {
		return mcp.NewToolResultError("missing required path parameter \"relation\""), nil
	}
	path = strings.ReplaceAll(path, "{relation}", url.PathEscape(in.Relation))

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterGetRole(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_get_role",
		mcp.WithDescription("GET /api/v1/roles/{id} — Get role"),
		mcp.WithReadOnlyHintAnnotation(true),
		withRawSchema(gentypes.SchemaGetRole),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleGetRole))
}

func (h *Handler) genHandleGetRole(ctx context.Context, req mcp.CallToolRequest, in gentypes.GetRoleInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/roles/{id}"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterListRoles(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_list_roles",
		mcp.WithDescription("GET /api/v1/roles — List roles"),
		mcp.WithReadOnlyHintAnnotation(true),
		withRawSchema(gentypes.SchemaListRoles),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleListRoles))
}

func (h *Handler) genHandleListRoles(ctx context.Context, req mcp.CallToolRequest, in gentypes.ListRolesInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/roles"

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterPatchObjects(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_patch_objects",
		mcp.WithDescription("PATCH /api/v1/roles/{id}/relations/{relation}/objects — Patch objects for a role by relation"),
		withRawSchema(gentypes.SchemaPatchObjects),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandlePatchObjects))
}

func (h *Handler) genHandlePatchObjects(ctx context.Context, req mcp.CallToolRequest, in gentypes.PatchObjectsInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/roles/{id}/relations/{relation}/objects"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))
	if in.Relation == "" {
		return mcp.NewToolResultError("missing required path parameter \"relation\""), nil
	}
	path = strings.ReplaceAll(path, "{relation}", url.PathEscape(in.Relation))

	res, err := c.Do(ctx, http.MethodPatch, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterPatchRole(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_patch_role",
		mcp.WithDescription("PATCH /api/v1/roles/{id} — Patch role"),
		withRawSchema(gentypes.SchemaPatchRole),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandlePatchRole))
}

func (h *Handler) genHandlePatchRole(ctx context.Context, req mcp.CallToolRequest, in gentypes.PatchRoleInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/roles/{id}"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	res, err := c.Do(ctx, http.MethodPatch, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}
