// Code generated by cmd/gen-tools. DO NOT EDIT.
// Source: docs/api/openapi.yml

package tools

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strings"

	"github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"

	signozclient "github.com/SigNoz/signoz-mcp-server/internal/client"
	gentypes "github.com/SigNoz/signoz-mcp-server/pkg/types/gentools"
)

// Reference every import unconditionally so tags without (say) path or
// query params still compile. These blanks are free at runtime.
var (
	_ = context.Background
	_ = fmt.Sprintf
	_ = http.MethodGet
	_ url.Values
	_ = strings.ReplaceAll
	_ = signozclient.DefaultQueryTimeout
	_ = mcp.NewTool
	_ server.MCPServer
)

// registerGatewayGenerated registers all generated tools for the
// "gateway" OpenAPI tag.
func (h *Handler) registerGatewayGenerated(s *server.MCPServer) {
	h.genRegisterCreateIngestionKey(s)
	h.genRegisterCreateIngestionKeyLimit(s)
	h.genRegisterDeleteIngestionKey(s)
	h.genRegisterDeleteIngestionKeyLimit(s)
	h.genRegisterGetIngestionKeys(s)
	h.genRegisterSearchIngestionKeys(s)
	h.genRegisterUpdateIngestionKey(s)
	h.genRegisterUpdateIngestionKeyLimit(s)
}

func (h *Handler) genRegisterCreateIngestionKey(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_create_ingestion_key",
		"This endpoint creates an ingestion key for the workspace",
		gentypes.SchemaCreateIngestionKey,
	)
	tool.RawOutputSchema = gentypes.OutputSchemaCreateIngestionKey
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleCreateIngestionKey))
}

func (h *Handler) genHandleCreateIngestionKey(ctx context.Context, req mcp.CallToolRequest, in gentypes.CreateIngestionKeyInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/gateway/ingestion_keys"

	res, err := c.Do(ctx, http.MethodPost, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterCreateIngestionKeyLimit(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_create_ingestion_key_limit",
		"This endpoint creates an ingestion key limit",
		gentypes.SchemaCreateIngestionKeyLimit,
	)
	tool.RawOutputSchema = gentypes.OutputSchemaCreateIngestionKeyLimit
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleCreateIngestionKeyLimit))
}

func (h *Handler) genHandleCreateIngestionKeyLimit(ctx context.Context, req mcp.CallToolRequest, in gentypes.CreateIngestionKeyLimitInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/gateway/ingestion_keys/{keyId}/limits"
	if in.KeyId == "" {
		return mcp.NewToolResultError("missing required path parameter \"keyId\""), nil
	}
	path = strings.ReplaceAll(path, "{keyId}", url.PathEscape(in.KeyId))

	res, err := c.Do(ctx, http.MethodPost, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterDeleteIngestionKey(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_delete_ingestion_key",
		"This endpoint deletes an ingestion key for the workspace",
		gentypes.SchemaDeleteIngestionKey,
	)
	destructive := true
	tool.Annotations.DestructiveHint = &destructive
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleDeleteIngestionKey))
}

func (h *Handler) genHandleDeleteIngestionKey(ctx context.Context, req mcp.CallToolRequest, in gentypes.DeleteIngestionKeyInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/gateway/ingestion_keys/{keyId}"
	if in.KeyId == "" {
		return mcp.NewToolResultError("missing required path parameter \"keyId\""), nil
	}
	path = strings.ReplaceAll(path, "{keyId}", url.PathEscape(in.KeyId))

	res, err := c.Do(ctx, http.MethodDelete, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterDeleteIngestionKeyLimit(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_delete_ingestion_key_limit",
		"This endpoint deletes an ingestion key limit",
		gentypes.SchemaDeleteIngestionKeyLimit,
	)
	destructive := true
	tool.Annotations.DestructiveHint = &destructive
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleDeleteIngestionKeyLimit))
}

func (h *Handler) genHandleDeleteIngestionKeyLimit(ctx context.Context, req mcp.CallToolRequest, in gentypes.DeleteIngestionKeyLimitInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/gateway/ingestion_keys/limits/{limitId}"
	if in.LimitId == "" {
		return mcp.NewToolResultError("missing required path parameter \"limitId\""), nil
	}
	path = strings.ReplaceAll(path, "{limitId}", url.PathEscape(in.LimitId))

	res, err := c.Do(ctx, http.MethodDelete, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterGetIngestionKeys(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_get_ingestion_keys",
		"This endpoint returns the ingestion keys for a workspace",
		gentypes.SchemaGetIngestionKeys,
	)
	readOnly := true
	tool.Annotations.ReadOnlyHint = &readOnly
	tool.RawOutputSchema = gentypes.OutputSchemaGetIngestionKeys
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleGetIngestionKeys))
}

func (h *Handler) genHandleGetIngestionKeys(ctx context.Context, req mcp.CallToolRequest, in gentypes.GetIngestionKeysInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/gateway/ingestion_keys"

	q := url.Values{}
	if in.Page != 0 {
		q.Set("page", fmt.Sprintf("%d", in.Page))
	}
	if in.PerPage != 0 {
		q.Set("per_page", fmt.Sprintf("%d", in.PerPage))
	}
	if len(q) > 0 {
		path += "?" + q.Encode()
	}

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterSearchIngestionKeys(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_search_ingestion_keys",
		"This endpoint returns the ingestion keys for a workspace",
		gentypes.SchemaSearchIngestionKeys,
	)
	readOnly := true
	tool.Annotations.ReadOnlyHint = &readOnly
	tool.RawOutputSchema = gentypes.OutputSchemaSearchIngestionKeys
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleSearchIngestionKeys))
}

func (h *Handler) genHandleSearchIngestionKeys(ctx context.Context, req mcp.CallToolRequest, in gentypes.SearchIngestionKeysInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/gateway/ingestion_keys/search"

	q := url.Values{}
	if in.Name != "" {
		q.Set("name", in.Name)
	}
	if in.Page != 0 {
		q.Set("page", fmt.Sprintf("%d", in.Page))
	}
	if in.PerPage != 0 {
		q.Set("per_page", fmt.Sprintf("%d", in.PerPage))
	}
	if len(q) > 0 {
		path += "?" + q.Encode()
	}

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterUpdateIngestionKey(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_update_ingestion_key",
		"This endpoint updates an ingestion key for the workspace",
		gentypes.SchemaUpdateIngestionKey,
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleUpdateIngestionKey))
}

func (h *Handler) genHandleUpdateIngestionKey(ctx context.Context, req mcp.CallToolRequest, in gentypes.UpdateIngestionKeyInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/gateway/ingestion_keys/{keyId}"
	if in.KeyId == "" {
		return mcp.NewToolResultError("missing required path parameter \"keyId\""), nil
	}
	path = strings.ReplaceAll(path, "{keyId}", url.PathEscape(in.KeyId))

	res, err := c.Do(ctx, http.MethodPatch, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterUpdateIngestionKeyLimit(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_update_ingestion_key_limit",
		"This endpoint updates an ingestion key limit",
		gentypes.SchemaUpdateIngestionKeyLimit,
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleUpdateIngestionKeyLimit))
}

func (h *Handler) genHandleUpdateIngestionKeyLimit(ctx context.Context, req mcp.CallToolRequest, in gentypes.UpdateIngestionKeyLimitInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/gateway/ingestion_keys/limits/{limitId}"
	if in.LimitId == "" {
		return mcp.NewToolResultError("missing required path parameter \"limitId\""), nil
	}
	path = strings.ReplaceAll(path, "{limitId}", url.PathEscape(in.LimitId))

	res, err := c.Do(ctx, http.MethodPatch, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}
