// Code generated by cmd/gen-tools. DO NOT EDIT.
// Source: docs/api/openapi.yml

package tools

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strings"

	"github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"

	signozclient "github.com/SigNoz/signoz-mcp-server/internal/client"
	gentypes "github.com/SigNoz/signoz-mcp-server/pkg/types/gentools"
)

// Reference every import unconditionally so tags without (say) path or
// query params still compile. These blanks are free at runtime.
var (
	_ = context.Background
	_ = fmt.Sprintf
	_ = http.MethodGet
	_ url.Values
	_ = strings.ReplaceAll
	_ = signozclient.DefaultQueryTimeout
	_ = mcp.NewTool
	_ server.MCPServer
)

// registerInframonitoringGenerated registers all generated tools for the
// "inframonitoring" OpenAPI tag.
func (h *Handler) registerInframonitoringGenerated(s *server.MCPServer) {
	h.genRegisterListHosts(s)
}

func (h *Handler) genRegisterListHosts(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_list_hosts",
		mcp.WithDescription("POST /api/v2/infra_monitoring/hosts — List Hosts for Infra Monitoring"),
		withRawSchema(gentypes.SchemaListHosts),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleListHosts))
}

func (h *Handler) genHandleListHosts(ctx context.Context, req mcp.CallToolRequest, in gentypes.ListHostsInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/infra_monitoring/hosts"

	res, err := c.Do(ctx, http.MethodPost, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}
