// Code generated by cmd/gen-tools. DO NOT EDIT.
// Source: docs/api/openapi.yml

package tools

import "github.com/mark3labs/mcp-go/server"

// RegisterGeneratedHandlers registers every MCP tool emitted by the OpenAPI
// code generator. It is wired from internal/mcp-server/server.go after the
// curated handlers so curated tools always take precedence on name
// collisions (the generator also skips such collisions at emit time).
func (h *Handler) RegisterGeneratedHandlers(s *server.MCPServer) {
	h.registerAlertsGenerated(s)
	h.registerAuthdomainsGenerated(s)
	h.registerAuthzGenerated(s)
	h.registerChannelsGenerated(s)
	h.registerCloudintegrationGenerated(s)
	h.registerDashboardGenerated(s)
	h.registerDowntimeschedulesGenerated(s)
	h.registerFeaturesGenerated(s)
	h.registerFieldsGenerated(s)
	h.registerGatewayGenerated(s)
	h.registerGlobalGenerated(s)
	h.registerHealthGenerated(s)
	h.registerInframonitoringGenerated(s)
	h.registerLogsGenerated(s)
	h.registerMetricsGenerated(s)
	h.registerOrgsGenerated(s)
	h.registerPreferencesGenerated(s)
	h.registerQuerierGenerated(s)
	h.registerRoleGenerated(s)
	h.registerRoutepoliciesGenerated(s)
	h.registerRulesGenerated(s)
	h.registerServiceaccountGenerated(s)
	h.registerSessionsGenerated(s)
	h.registerTracedetailGenerated(s)
	h.registerUsersGenerated(s)
	h.registerZeusGenerated(s)
}
