// Code generated by cmd/gen-tools. DO NOT EDIT.
// Source: docs/api/openapi.yml

package tools

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strings"

	"github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"

	signozclient "github.com/SigNoz/signoz-mcp-server/internal/client"
	gentypes "github.com/SigNoz/signoz-mcp-server/pkg/types/gentools"
)

// Reference every import unconditionally so tags without (say) path or
// query params still compile. These blanks are free at runtime.
var (
	_ = context.Background
	_ = fmt.Sprintf
	_ = http.MethodGet
	_ url.Values
	_ = strings.ReplaceAll
	_ = signozclient.DefaultQueryTimeout
	_ = mcp.NewTool
	_ server.MCPServer
)

// registerUsersGenerated registers all generated tools for the
// "users" OpenAPI tag.
func (h *Handler) registerUsersGenerated(s *server.MCPServer) {
	h.genRegisterCreateBulkInvite(s)
	h.genRegisterCreateInvite(s)
	h.genRegisterCreateResetPasswordToken(s)
	h.genRegisterDeleteUser(s)
	h.genRegisterForgotPassword(s)
	h.genRegisterGetMyUser(s)
	h.genRegisterGetResetPasswordToken(s)
	h.genRegisterGetRolesByUserID(s)
	h.genRegisterGetUser(s)
	h.genRegisterGetUsersByRoleID(s)
	h.genRegisterListUsers(s)
	h.genRegisterRemoveUserRoleByUserIDAndRoleID(s)
	h.genRegisterSetRoleByUserID(s)
	h.genRegisterUpdateMyPassword(s)
	h.genRegisterUpdateMyUserV2(s)
	h.genRegisterUpdateUser(s)
}

func (h *Handler) genRegisterCreateBulkInvite(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_create_bulk_invite",
		mcp.WithDescription("POST /api/v1/invite/bulk — Create bulk invite"),
		withRawSchema(gentypes.SchemaCreateBulkInvite),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleCreateBulkInvite))
}

func (h *Handler) genHandleCreateBulkInvite(ctx context.Context, req mcp.CallToolRequest, in gentypes.CreateBulkInviteInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/invite/bulk"

	res, err := c.Do(ctx, http.MethodPost, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterCreateInvite(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_create_invite",
		mcp.WithDescription("POST /api/v1/invite — Create invite"),
		withRawSchema(gentypes.SchemaCreateInvite),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleCreateInvite))
}

func (h *Handler) genHandleCreateInvite(ctx context.Context, req mcp.CallToolRequest, in gentypes.CreateInviteInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/invite"

	res, err := c.Do(ctx, http.MethodPost, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterCreateResetPasswordToken(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_create_reset_password_token",
		mcp.WithDescription("PUT /api/v2/users/{id}/reset_password_tokens — Create or regenerate reset password token for a user"),
		withRawSchema(gentypes.SchemaCreateResetPasswordToken),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleCreateResetPasswordToken))
}

func (h *Handler) genHandleCreateResetPasswordToken(ctx context.Context, req mcp.CallToolRequest, in gentypes.CreateResetPasswordTokenInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/users/{id}/reset_password_tokens"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	res, err := c.Do(ctx, http.MethodPut, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterDeleteUser(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_delete_user",
		mcp.WithDescription("DELETE /api/v1/user/{id} — Delete user"),
		mcp.WithDestructiveHintAnnotation(true),
		withRawSchema(gentypes.SchemaDeleteUser),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleDeleteUser))
}

func (h *Handler) genHandleDeleteUser(ctx context.Context, req mcp.CallToolRequest, in gentypes.DeleteUserInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/user/{id}"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	res, err := c.Do(ctx, http.MethodDelete, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterForgotPassword(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_forgot_password",
		mcp.WithDescription("POST /api/v2/factor_password/forgot — Forgot password"),
		withRawSchema(gentypes.SchemaForgotPassword),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleForgotPassword))
}

func (h *Handler) genHandleForgotPassword(ctx context.Context, req mcp.CallToolRequest, in gentypes.ForgotPasswordInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/factor_password/forgot"

	res, err := c.Do(ctx, http.MethodPost, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterGetMyUser(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_get_my_user",
		mcp.WithDescription("GET /api/v2/users/me — Get my user v2"),
		mcp.WithReadOnlyHintAnnotation(true),
		withRawSchema(gentypes.SchemaGetMyUser),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleGetMyUser))
}

func (h *Handler) genHandleGetMyUser(ctx context.Context, req mcp.CallToolRequest, in gentypes.GetMyUserInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/users/me"

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterGetResetPasswordToken(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_get_reset_password_token",
		mcp.WithDescription("GET /api/v2/users/{id}/reset_password_tokens — Get reset password token for a user"),
		mcp.WithReadOnlyHintAnnotation(true),
		withRawSchema(gentypes.SchemaGetResetPasswordToken),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleGetResetPasswordToken))
}

func (h *Handler) genHandleGetResetPasswordToken(ctx context.Context, req mcp.CallToolRequest, in gentypes.GetResetPasswordTokenInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/users/{id}/reset_password_tokens"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterGetRolesByUserID(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_get_roles_by_user_id",
		mcp.WithDescription("GET /api/v2/users/{id}/roles — Get user roles"),
		mcp.WithReadOnlyHintAnnotation(true),
		withRawSchema(gentypes.SchemaGetRolesByUserID),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleGetRolesByUserID))
}

func (h *Handler) genHandleGetRolesByUserID(ctx context.Context, req mcp.CallToolRequest, in gentypes.GetRolesByUserIDInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/users/{id}/roles"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterGetUser(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_get_user",
		mcp.WithDescription("GET /api/v2/users/{id} — Get user by user id"),
		mcp.WithReadOnlyHintAnnotation(true),
		withRawSchema(gentypes.SchemaGetUser),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleGetUser))
}

func (h *Handler) genHandleGetUser(ctx context.Context, req mcp.CallToolRequest, in gentypes.GetUserInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/users/{id}"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterGetUsersByRoleID(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_get_users_by_role_id",
		mcp.WithDescription("GET /api/v2/roles/{id}/users — Get users by role id"),
		mcp.WithReadOnlyHintAnnotation(true),
		withRawSchema(gentypes.SchemaGetUsersByRoleID),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleGetUsersByRoleID))
}

func (h *Handler) genHandleGetUsersByRoleID(ctx context.Context, req mcp.CallToolRequest, in gentypes.GetUsersByRoleIDInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/roles/{id}/users"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterListUsers(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_list_users",
		mcp.WithDescription("GET /api/v2/users — List users v2"),
		mcp.WithReadOnlyHintAnnotation(true),
		withRawSchema(gentypes.SchemaListUsers),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleListUsers))
}

func (h *Handler) genHandleListUsers(ctx context.Context, req mcp.CallToolRequest, in gentypes.ListUsersInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/users"

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterRemoveUserRoleByUserIDAndRoleID(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_remove_user_role_by_user_id_and_role_id",
		mcp.WithDescription("DELETE /api/v2/users/{id}/roles/{roleId} — Remove a role from user"),
		mcp.WithDestructiveHintAnnotation(true),
		withRawSchema(gentypes.SchemaRemoveUserRoleByUserIDAndRoleID),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleRemoveUserRoleByUserIDAndRoleID))
}

func (h *Handler) genHandleRemoveUserRoleByUserIDAndRoleID(ctx context.Context, req mcp.CallToolRequest, in gentypes.RemoveUserRoleByUserIDAndRoleIDInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/users/{id}/roles/{roleId}"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))
	if in.RoleId == "" {
		return mcp.NewToolResultError("missing required path parameter \"roleId\""), nil
	}
	path = strings.ReplaceAll(path, "{roleId}", url.PathEscape(in.RoleId))

	res, err := c.Do(ctx, http.MethodDelete, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterSetRoleByUserID(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_set_role_by_user_id",
		mcp.WithDescription("POST /api/v2/users/{id}/roles — Set user roles"),
		withRawSchema(gentypes.SchemaSetRoleByUserID),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleSetRoleByUserID))
}

func (h *Handler) genHandleSetRoleByUserID(ctx context.Context, req mcp.CallToolRequest, in gentypes.SetRoleByUserIDInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/users/{id}/roles"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	res, err := c.Do(ctx, http.MethodPost, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterUpdateMyPassword(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_update_my_password",
		mcp.WithDescription("PUT /api/v2/users/me/factor_password — Updates my password"),
		withRawSchema(gentypes.SchemaUpdateMyPassword),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleUpdateMyPassword))
}

func (h *Handler) genHandleUpdateMyPassword(ctx context.Context, req mcp.CallToolRequest, in gentypes.UpdateMyPasswordInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/users/me/factor_password"

	res, err := c.Do(ctx, http.MethodPut, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterUpdateMyUserV2(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_update_my_user_v2",
		mcp.WithDescription("PUT /api/v2/users/me — Update my user v2"),
		withRawSchema(gentypes.SchemaUpdateMyUserV2),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleUpdateMyUserV2))
}

func (h *Handler) genHandleUpdateMyUserV2(ctx context.Context, req mcp.CallToolRequest, in gentypes.UpdateMyUserV2Input) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/users/me"

	res, err := c.Do(ctx, http.MethodPut, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterUpdateUser(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_update_user",
		mcp.WithDescription("PUT /api/v2/users/{id} — Update user v2"),
		withRawSchema(gentypes.SchemaUpdateUser),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleUpdateUser))
}

func (h *Handler) genHandleUpdateUser(ctx context.Context, req mcp.CallToolRequest, in gentypes.UpdateUserInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/users/{id}"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	res, err := c.Do(ctx, http.MethodPut, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}
