// Code generated by cmd/gen-tools. DO NOT EDIT.
// Source: docs/api/openapi.yml

package tools

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strings"

	"github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"

	signozclient "github.com/SigNoz/signoz-mcp-server/internal/client"
	gentypes "github.com/SigNoz/signoz-mcp-server/pkg/types/gentools"
)

// Reference every import unconditionally so tags without (say) path or
// query params still compile. These blanks are free at runtime.
var (
	_ = context.Background
	_ = fmt.Sprintf
	_ = http.MethodGet
	_ url.Values
	_ = strings.ReplaceAll
	_ = signozclient.DefaultQueryTimeout
	_ = mcp.NewTool
	_ server.MCPServer
)

// registerRulesGenerated registers all generated tools for the
// "rules" OpenAPI tag.
func (h *Handler) registerRulesGenerated(s *server.MCPServer) {
	h.genRegisterCreateRule(s)
	h.genRegisterDeleteRuleByID(s)
	h.genRegisterGetRuleByID(s)
	h.genRegisterGetRuleHistoryFilterKeys(s)
	h.genRegisterGetRuleHistoryFilterValues(s)
	h.genRegisterGetRuleHistoryOverallStatus(s)
	h.genRegisterGetRuleHistoryStats(s)
	h.genRegisterGetRuleHistoryTimeline(s)
	h.genRegisterGetRuleHistoryTopContributors(s)
	h.genRegisterListRules(s)
	h.genRegisterPatchRuleByID(s)
	h.genRegisterTestRule(s)
	h.genRegisterUpdateRuleByID(s)
}

func (h *Handler) genRegisterCreateRule(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_create_rule",
		"This endpoint creates a new alert rule",
		gentypes.SchemaCreateRule,
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleCreateRule))
}

func (h *Handler) genHandleCreateRule(ctx context.Context, req mcp.CallToolRequest, in gentypes.CreateRuleInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/rules"

	res, err := c.Do(ctx, http.MethodPost, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterDeleteRuleByID(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_delete_rule_by_id",
		"This endpoint deletes an alert rule by ID",
		gentypes.SchemaDeleteRuleByID,
	)
	destructive := true
	tool.Annotations.DestructiveHint = &destructive
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleDeleteRuleByID))
}

func (h *Handler) genHandleDeleteRuleByID(ctx context.Context, req mcp.CallToolRequest, in gentypes.DeleteRuleByIDInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/rules/{id}"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	res, err := c.Do(ctx, http.MethodDelete, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterGetRuleByID(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_get_rule_by_id",
		"This endpoint returns an alert rule by ID",
		gentypes.SchemaGetRuleByID,
	)
	readOnly := true
	tool.Annotations.ReadOnlyHint = &readOnly
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleGetRuleByID))
}

func (h *Handler) genHandleGetRuleByID(ctx context.Context, req mcp.CallToolRequest, in gentypes.GetRuleByIDInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/rules/{id}"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterGetRuleHistoryFilterKeys(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_get_rule_history_filter_keys",
		"Returns distinct label keys from rule history entries for the selected range.",
		gentypes.SchemaGetRuleHistoryFilterKeys,
	)
	readOnly := true
	tool.Annotations.ReadOnlyHint = &readOnly
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleGetRuleHistoryFilterKeys))
}

func (h *Handler) genHandleGetRuleHistoryFilterKeys(ctx context.Context, req mcp.CallToolRequest, in gentypes.GetRuleHistoryFilterKeysInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/rules/{id}/history/filter_keys"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	q := url.Values{}
	if in.Signal != "" {
		q.Set("signal", in.Signal)
	}
	if in.Source != "" {
		q.Set("source", in.Source)
	}
	if in.Limit != 0 {
		q.Set("limit", fmt.Sprintf("%d", in.Limit))
	}
	if in.StartUnixMilli != 0 {
		q.Set("startUnixMilli", fmt.Sprintf("%d", in.StartUnixMilli))
	}
	if in.EndUnixMilli != 0 {
		q.Set("endUnixMilli", fmt.Sprintf("%d", in.EndUnixMilli))
	}
	if in.FieldContext != "" {
		q.Set("fieldContext", in.FieldContext)
	}
	if in.FieldDataType != "" {
		q.Set("fieldDataType", in.FieldDataType)
	}
	if in.MetricName != "" {
		q.Set("metricName", in.MetricName)
	}
	if in.MetricNamespace != "" {
		q.Set("metricNamespace", in.MetricNamespace)
	}
	if in.SearchText != "" {
		q.Set("searchText", in.SearchText)
	}
	if len(q) > 0 {
		path += "?" + q.Encode()
	}

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterGetRuleHistoryFilterValues(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_get_rule_history_filter_values",
		"Returns distinct label values for a given key from rule history entries.",
		gentypes.SchemaGetRuleHistoryFilterValues,
	)
	readOnly := true
	tool.Annotations.ReadOnlyHint = &readOnly
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleGetRuleHistoryFilterValues))
}

func (h *Handler) genHandleGetRuleHistoryFilterValues(ctx context.Context, req mcp.CallToolRequest, in gentypes.GetRuleHistoryFilterValuesInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/rules/{id}/history/filter_values"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	q := url.Values{}
	if in.Signal != "" {
		q.Set("signal", in.Signal)
	}
	if in.Source != "" {
		q.Set("source", in.Source)
	}
	if in.Limit != 0 {
		q.Set("limit", fmt.Sprintf("%d", in.Limit))
	}
	if in.StartUnixMilli != 0 {
		q.Set("startUnixMilli", fmt.Sprintf("%d", in.StartUnixMilli))
	}
	if in.EndUnixMilli != 0 {
		q.Set("endUnixMilli", fmt.Sprintf("%d", in.EndUnixMilli))
	}
	if in.FieldContext != "" {
		q.Set("fieldContext", in.FieldContext)
	}
	if in.FieldDataType != "" {
		q.Set("fieldDataType", in.FieldDataType)
	}
	if in.MetricName != "" {
		q.Set("metricName", in.MetricName)
	}
	if in.MetricNamespace != "" {
		q.Set("metricNamespace", in.MetricNamespace)
	}
	if in.SearchText != "" {
		q.Set("searchText", in.SearchText)
	}
	if in.Name != "" {
		q.Set("name", in.Name)
	}
	if in.ExistingQuery != "" {
		q.Set("existingQuery", in.ExistingQuery)
	}
	if len(q) > 0 {
		path += "?" + q.Encode()
	}

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterGetRuleHistoryOverallStatus(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_get_rule_history_overall_status",
		"Returns overall firing/inactive intervals for a rule in the selected time range.",
		gentypes.SchemaGetRuleHistoryOverallStatus,
	)
	readOnly := true
	tool.Annotations.ReadOnlyHint = &readOnly
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleGetRuleHistoryOverallStatus))
}

func (h *Handler) genHandleGetRuleHistoryOverallStatus(ctx context.Context, req mcp.CallToolRequest, in gentypes.GetRuleHistoryOverallStatusInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/rules/{id}/history/overall_status"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	q := url.Values{}
	if in.Start != 0 {
		q.Set("start", fmt.Sprintf("%d", in.Start))
	}
	if in.End != 0 {
		q.Set("end", fmt.Sprintf("%d", in.End))
	}
	if len(q) > 0 {
		path += "?" + q.Encode()
	}

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterGetRuleHistoryStats(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_get_rule_history_stats",
		"Returns trigger and resolution statistics for a rule in the selected time range.",
		gentypes.SchemaGetRuleHistoryStats,
	)
	readOnly := true
	tool.Annotations.ReadOnlyHint = &readOnly
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleGetRuleHistoryStats))
}

func (h *Handler) genHandleGetRuleHistoryStats(ctx context.Context, req mcp.CallToolRequest, in gentypes.GetRuleHistoryStatsInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/rules/{id}/history/stats"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	q := url.Values{}
	if in.Start != 0 {
		q.Set("start", fmt.Sprintf("%d", in.Start))
	}
	if in.End != 0 {
		q.Set("end", fmt.Sprintf("%d", in.End))
	}
	if len(q) > 0 {
		path += "?" + q.Encode()
	}

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterGetRuleHistoryTimeline(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_get_rule_history_timeline",
		"Returns paginated timeline entries for rule state transitions.",
		gentypes.SchemaGetRuleHistoryTimeline,
	)
	readOnly := true
	tool.Annotations.ReadOnlyHint = &readOnly
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleGetRuleHistoryTimeline))
}

func (h *Handler) genHandleGetRuleHistoryTimeline(ctx context.Context, req mcp.CallToolRequest, in gentypes.GetRuleHistoryTimelineInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/rules/{id}/history/timeline"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	q := url.Values{}
	if in.Start != 0 {
		q.Set("start", fmt.Sprintf("%d", in.Start))
	}
	if in.End != 0 {
		q.Set("end", fmt.Sprintf("%d", in.End))
	}
	if in.State != "" {
		q.Set("state", in.State)
	}
	if in.FilterExpression != "" {
		q.Set("filterExpression", in.FilterExpression)
	}
	if in.Limit != 0 {
		q.Set("limit", fmt.Sprintf("%d", in.Limit))
	}
	if in.Order != "" {
		q.Set("order", in.Order)
	}
	if in.Cursor != "" {
		q.Set("cursor", in.Cursor)
	}
	if len(q) > 0 {
		path += "?" + q.Encode()
	}

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterGetRuleHistoryTopContributors(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_get_rule_history_top_contributors",
		"Returns top label combinations contributing to rule firing in the selected time range.",
		gentypes.SchemaGetRuleHistoryTopContributors,
	)
	readOnly := true
	tool.Annotations.ReadOnlyHint = &readOnly
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleGetRuleHistoryTopContributors))
}

func (h *Handler) genHandleGetRuleHistoryTopContributors(ctx context.Context, req mcp.CallToolRequest, in gentypes.GetRuleHistoryTopContributorsInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/rules/{id}/history/top_contributors"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	q := url.Values{}
	if in.Start != 0 {
		q.Set("start", fmt.Sprintf("%d", in.Start))
	}
	if in.End != 0 {
		q.Set("end", fmt.Sprintf("%d", in.End))
	}
	if len(q) > 0 {
		path += "?" + q.Encode()
	}

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterListRules(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_list_rules",
		"This endpoint lists all alert rules with their current evaluation state",
		gentypes.SchemaListRules,
	)
	readOnly := true
	tool.Annotations.ReadOnlyHint = &readOnly
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleListRules))
}

func (h *Handler) genHandleListRules(ctx context.Context, req mcp.CallToolRequest, in gentypes.ListRulesInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/rules"

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterPatchRuleByID(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_patch_rule_by_id",
		"This endpoint applies a partial update to an alert rule by ID",
		gentypes.SchemaPatchRuleByID,
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandlePatchRuleByID))
}

func (h *Handler) genHandlePatchRuleByID(ctx context.Context, req mcp.CallToolRequest, in gentypes.PatchRuleByIDInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/rules/{id}"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	res, err := c.Do(ctx, http.MethodPatch, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterTestRule(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_test_rule",
		"This endpoint fires a test notification for the given rule definition",
		gentypes.SchemaTestRule,
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleTestRule))
}

func (h *Handler) genHandleTestRule(ctx context.Context, req mcp.CallToolRequest, in gentypes.TestRuleInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/rules/test"

	res, err := c.Do(ctx, http.MethodPost, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterUpdateRuleByID(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_update_rule_by_id",
		"This endpoint updates an alert rule by ID",
		gentypes.SchemaUpdateRuleByID,
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleUpdateRuleByID))
}

func (h *Handler) genHandleUpdateRuleByID(ctx context.Context, req mcp.CallToolRequest, in gentypes.UpdateRuleByIDInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/rules/{id}"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	res, err := c.Do(ctx, http.MethodPut, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}
