// Code generated by cmd/gen-tools. DO NOT EDIT.
// Source: docs/api/openapi.yml

package tools

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strings"

	"github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"

	signozclient "github.com/SigNoz/signoz-mcp-server/internal/client"
	gentypes "github.com/SigNoz/signoz-mcp-server/pkg/types/gentools"
)

// Reference every import unconditionally so tags without (say) path or
// query params still compile. These blanks are free at runtime.
var (
	_ = context.Background
	_ = fmt.Sprintf
	_ = http.MethodGet
	_ url.Values
	_ = strings.ReplaceAll
	_ = signozclient.DefaultQueryTimeout
	_ = mcp.NewTool
	_ server.MCPServer
)

// registerFieldsGenerated registers all generated tools for the
// "fields" OpenAPI tag.
func (h *Handler) registerFieldsGenerated(s *server.MCPServer) {
	h.genRegisterGetFieldsKeys(s)
	h.genRegisterGetFieldsValues(s)
}

func (h *Handler) genRegisterGetFieldsKeys(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_get_fields_keys",
		"This endpoint returns field keys",
		gentypes.SchemaGetFieldsKeys,
	)
	readOnly := true
	tool.Annotations.ReadOnlyHint = &readOnly
	tool.RawOutputSchema = gentypes.OutputSchemaGetFieldsKeys
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleGetFieldsKeys))
}

func (h *Handler) genHandleGetFieldsKeys(ctx context.Context, req mcp.CallToolRequest, in gentypes.GetFieldsKeysInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/fields/keys"

	q := url.Values{}
	if in.Signal != "" {
		q.Set("signal", in.Signal)
	}
	if in.Source != "" {
		q.Set("source", in.Source)
	}
	if in.Limit != 0 {
		q.Set("limit", fmt.Sprintf("%d", in.Limit))
	}
	if in.StartUnixMilli != 0 {
		q.Set("startUnixMilli", fmt.Sprintf("%d", in.StartUnixMilli))
	}
	if in.EndUnixMilli != 0 {
		q.Set("endUnixMilli", fmt.Sprintf("%d", in.EndUnixMilli))
	}
	if in.FieldContext != "" {
		q.Set("fieldContext", in.FieldContext)
	}
	if in.FieldDataType != "" {
		q.Set("fieldDataType", in.FieldDataType)
	}
	if in.MetricName != "" {
		q.Set("metricName", in.MetricName)
	}
	if in.MetricNamespace != "" {
		q.Set("metricNamespace", in.MetricNamespace)
	}
	if in.SearchText != "" {
		q.Set("searchText", in.SearchText)
	}
	if len(q) > 0 {
		path += "?" + q.Encode()
	}

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterGetFieldsValues(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_get_fields_values",
		"This endpoint returns field values",
		gentypes.SchemaGetFieldsValues,
	)
	readOnly := true
	tool.Annotations.ReadOnlyHint = &readOnly
	tool.RawOutputSchema = gentypes.OutputSchemaGetFieldsValues
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleGetFieldsValues))
}

func (h *Handler) genHandleGetFieldsValues(ctx context.Context, req mcp.CallToolRequest, in gentypes.GetFieldsValuesInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/fields/values"

	q := url.Values{}
	if in.Signal != "" {
		q.Set("signal", in.Signal)
	}
	if in.Source != "" {
		q.Set("source", in.Source)
	}
	if in.Limit != 0 {
		q.Set("limit", fmt.Sprintf("%d", in.Limit))
	}
	if in.StartUnixMilli != 0 {
		q.Set("startUnixMilli", fmt.Sprintf("%d", in.StartUnixMilli))
	}
	if in.EndUnixMilli != 0 {
		q.Set("endUnixMilli", fmt.Sprintf("%d", in.EndUnixMilli))
	}
	if in.FieldContext != "" {
		q.Set("fieldContext", in.FieldContext)
	}
	if in.FieldDataType != "" {
		q.Set("fieldDataType", in.FieldDataType)
	}
	if in.MetricName != "" {
		q.Set("metricName", in.MetricName)
	}
	if in.MetricNamespace != "" {
		q.Set("metricNamespace", in.MetricNamespace)
	}
	if in.SearchText != "" {
		q.Set("searchText", in.SearchText)
	}
	if in.Name != "" {
		q.Set("name", in.Name)
	}
	if in.ExistingQuery != "" {
		q.Set("existingQuery", in.ExistingQuery)
	}
	if len(q) > 0 {
		path += "?" + q.Encode()
	}

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}
