// Code generated by cmd/gen-tools. DO NOT EDIT.
// Source: docs/api/openapi.yml

package tools

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strings"

	"github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"

	signozclient "github.com/SigNoz/signoz-mcp-server/internal/client"
	gentypes "github.com/SigNoz/signoz-mcp-server/pkg/types/gentools"
)

// Reference every import unconditionally so tags without (say) path or
// query params still compile. These blanks are free at runtime.
var (
	_ = context.Background
	_ = fmt.Sprintf
	_ = http.MethodGet
	_ url.Values
	_ = strings.ReplaceAll
	_ = signozclient.DefaultQueryTimeout
	_ = mcp.NewTool
	_ server.MCPServer
)

// registerSessionsGenerated registers all generated tools for the
// "sessions" OpenAPI tag.
func (h *Handler) registerSessionsGenerated(s *server.MCPServer) {
	h.genRegisterCreateSessionByEmailPassword(s)
	h.genRegisterCreateSessionByGoogleCallback(s)
	h.genRegisterCreateSessionByOIDCCallback(s)
	h.genRegisterDeleteSession(s)
	h.genRegisterGetSessionContext(s)
	h.genRegisterRotateSession(s)
}

func (h *Handler) genRegisterCreateSessionByEmailPassword(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_create_session_by_email_password",
		"This endpoint creates a session for a user using email and password.",
		gentypes.SchemaCreateSessionByEmailPassword,
	)
	tool.RawOutputSchema = gentypes.OutputSchemaCreateSessionByEmailPassword
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleCreateSessionByEmailPassword))
}

func (h *Handler) genHandleCreateSessionByEmailPassword(ctx context.Context, req mcp.CallToolRequest, in gentypes.CreateSessionByEmailPasswordInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/sessions/email_password"

	res, err := c.Do(ctx, http.MethodPost, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterCreateSessionByGoogleCallback(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_create_session_by_google_callback",
		"This endpoint creates a session for a user using google callback",
		gentypes.SchemaCreateSessionByGoogleCallback,
	)
	readOnly := true
	tool.Annotations.ReadOnlyHint = &readOnly
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleCreateSessionByGoogleCallback))
}

func (h *Handler) genHandleCreateSessionByGoogleCallback(ctx context.Context, req mcp.CallToolRequest, in gentypes.CreateSessionByGoogleCallbackInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/complete/google"

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterCreateSessionByOIDCCallback(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_create_session_by_oidc_callback",
		"This endpoint creates a session for a user using oidc callback",
		gentypes.SchemaCreateSessionByOIDCCallback,
	)
	readOnly := true
	tool.Annotations.ReadOnlyHint = &readOnly
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleCreateSessionByOIDCCallback))
}

func (h *Handler) genHandleCreateSessionByOIDCCallback(ctx context.Context, req mcp.CallToolRequest, in gentypes.CreateSessionByOIDCCallbackInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/complete/oidc"

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterDeleteSession(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_delete_session",
		"This endpoint deletes the session",
		gentypes.SchemaDeleteSession,
	)
	destructive := true
	tool.Annotations.DestructiveHint = &destructive
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleDeleteSession))
}

func (h *Handler) genHandleDeleteSession(ctx context.Context, req mcp.CallToolRequest, in gentypes.DeleteSessionInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/sessions"

	res, err := c.Do(ctx, http.MethodDelete, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterGetSessionContext(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_get_session_context",
		"This endpoint returns the context for the session",
		gentypes.SchemaGetSessionContext,
	)
	readOnly := true
	tool.Annotations.ReadOnlyHint = &readOnly
	tool.RawOutputSchema = gentypes.OutputSchemaGetSessionContext
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleGetSessionContext))
}

func (h *Handler) genHandleGetSessionContext(ctx context.Context, req mcp.CallToolRequest, in gentypes.GetSessionContextInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/sessions/context"

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterRotateSession(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_rotate_session",
		"This endpoint rotates the session",
		gentypes.SchemaRotateSession,
	)
	tool.RawOutputSchema = gentypes.OutputSchemaRotateSession
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleRotateSession))
}

func (h *Handler) genHandleRotateSession(ctx context.Context, req mcp.CallToolRequest, in gentypes.RotateSessionInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/sessions/rotate"

	res, err := c.Do(ctx, http.MethodPost, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}
