// Code generated by cmd/gen-tools. DO NOT EDIT.
// Source: docs/api/openapi.yml

package tools

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strings"

	"github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"

	signozclient "github.com/SigNoz/signoz-mcp-server/internal/client"
	gentypes "github.com/SigNoz/signoz-mcp-server/pkg/types/gentools"
)

// Reference every import unconditionally so tags without (say) path or
// query params still compile. These blanks are free at runtime.
var (
	_ = context.Background
	_ = fmt.Sprintf
	_ = http.MethodGet
	_ url.Values
	_ = strings.ReplaceAll
	_ = signozclient.DefaultQueryTimeout
	_ = mcp.NewTool
	_ server.MCPServer
)

// registerLogsGenerated registers all generated tools for the
// "logs" OpenAPI tag.
func (h *Handler) registerLogsGenerated(s *server.MCPServer) {
	h.genRegisterHandleExportRawDataPOST(s)
	h.genRegisterHandlePromoteAndIndexPaths(s)
	h.genRegisterListPromotedAndIndexedPaths(s)
}

func (h *Handler) genRegisterHandleExportRawDataPOST(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_handle_export_raw_data_post",
		mcp.WithDescription("POST /api/v1/export_raw_data — Export raw data"),
		withRawSchema(gentypes.SchemaHandleExportRawDataPOST),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleHandleExportRawDataPOST))
}

func (h *Handler) genHandleHandleExportRawDataPOST(ctx context.Context, req mcp.CallToolRequest, in gentypes.HandleExportRawDataPOSTInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/export_raw_data"

	q := url.Values{}
	if in.Format != "" {
		q.Set("format", in.Format)
	}
	if len(q) > 0 {
		path += "?" + q.Encode()
	}

	res, err := c.Do(ctx, http.MethodPost, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterHandlePromoteAndIndexPaths(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_handle_promote_and_index_paths",
		mcp.WithDescription("POST /api/v1/logs/promote_paths — Promote and index paths"),
		withRawSchema(gentypes.SchemaHandlePromoteAndIndexPaths),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleHandlePromoteAndIndexPaths))
}

func (h *Handler) genHandleHandlePromoteAndIndexPaths(ctx context.Context, req mcp.CallToolRequest, in gentypes.HandlePromoteAndIndexPathsInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/logs/promote_paths"

	res, err := c.Do(ctx, http.MethodPost, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterListPromotedAndIndexedPaths(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_list_promoted_and_indexed_paths",
		mcp.WithDescription("GET /api/v1/logs/promote_paths — Promote and index paths"),
		mcp.WithReadOnlyHintAnnotation(true),
		withRawSchema(gentypes.SchemaListPromotedAndIndexedPaths),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleListPromotedAndIndexedPaths))
}

func (h *Handler) genHandleListPromotedAndIndexedPaths(ctx context.Context, req mcp.CallToolRequest, in gentypes.ListPromotedAndIndexedPathsInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/logs/promote_paths"

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}
