// Code generated by cmd/gen-tools. DO NOT EDIT.
// Source: docs/api/openapi.yml

package tools

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strings"

	"github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"

	signozclient "github.com/SigNoz/signoz-mcp-server/internal/client"
	gentypes "github.com/SigNoz/signoz-mcp-server/pkg/types/gentools"
)

// Reference every import unconditionally so tags without (say) path or
// query params still compile. These blanks are free at runtime.
var (
	_ = context.Background
	_ = fmt.Sprintf
	_ = http.MethodGet
	_ url.Values
	_ = strings.ReplaceAll
	_ = signozclient.DefaultQueryTimeout
	_ = mcp.NewTool
	_ server.MCPServer
)

// registerCloudintegrationGenerated registers all generated tools for the
// "cloudintegration" OpenAPI tag.
func (h *Handler) registerCloudintegrationGenerated(s *server.MCPServer) {
	h.genRegisterAgentCheckIn(s)
	h.genRegisterCreateAccount(s)
	h.genRegisterDisconnectAccount(s)
	h.genRegisterGetAccount(s)
	h.genRegisterGetConnectionCredentials(s)
	h.genRegisterGetService(s)
	h.genRegisterListAccounts(s)
	h.genRegisterListServicesMetadata(s)
	h.genRegisterUpdateAccount(s)
	h.genRegisterUpdateService(s)
}

func (h *Handler) genRegisterAgentCheckIn(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_agent_check_in",
		"This endpoint is called by the deployed agent to check in",
		gentypes.SchemaAgentCheckIn,
	)
	tool.RawOutputSchema = gentypes.OutputSchemaAgentCheckIn
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleAgentCheckIn))
}

func (h *Handler) genHandleAgentCheckIn(ctx context.Context, req mcp.CallToolRequest, in gentypes.AgentCheckInInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/cloud_integrations/{cloud_provider}/accounts/check_in"
	if in.CloudProvider == "" {
		return mcp.NewToolResultError("missing required path parameter \"cloud_provider\""), nil
	}
	path = strings.ReplaceAll(path, "{cloud_provider}", url.PathEscape(in.CloudProvider))

	res, err := c.Do(ctx, http.MethodPost, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterCreateAccount(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_create_account",
		"This endpoint creates a new cloud integration account for the specified cloud provider",
		gentypes.SchemaCreateAccount,
	)
	tool.RawOutputSchema = gentypes.OutputSchemaCreateAccount
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleCreateAccount))
}

func (h *Handler) genHandleCreateAccount(ctx context.Context, req mcp.CallToolRequest, in gentypes.CreateAccountInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/cloud_integrations/{cloud_provider}/accounts"
	if in.CloudProvider == "" {
		return mcp.NewToolResultError("missing required path parameter \"cloud_provider\""), nil
	}
	path = strings.ReplaceAll(path, "{cloud_provider}", url.PathEscape(in.CloudProvider))

	res, err := c.Do(ctx, http.MethodPost, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterDisconnectAccount(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_disconnect_account",
		"This endpoint disconnects an account for the specified cloud provider",
		gentypes.SchemaDisconnectAccount,
	)
	destructive := true
	tool.Annotations.DestructiveHint = &destructive
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleDisconnectAccount))
}

func (h *Handler) genHandleDisconnectAccount(ctx context.Context, req mcp.CallToolRequest, in gentypes.DisconnectAccountInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/cloud_integrations/{cloud_provider}/accounts/{id}"
	if in.CloudProvider == "" {
		return mcp.NewToolResultError("missing required path parameter \"cloud_provider\""), nil
	}
	path = strings.ReplaceAll(path, "{cloud_provider}", url.PathEscape(in.CloudProvider))
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	res, err := c.Do(ctx, http.MethodDelete, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterGetAccount(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_get_account",
		"This endpoint gets an account for the specified cloud provider",
		gentypes.SchemaGetAccount,
	)
	readOnly := true
	tool.Annotations.ReadOnlyHint = &readOnly
	tool.RawOutputSchema = gentypes.OutputSchemaGetAccount
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleGetAccount))
}

func (h *Handler) genHandleGetAccount(ctx context.Context, req mcp.CallToolRequest, in gentypes.GetAccountInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/cloud_integrations/{cloud_provider}/accounts/{id}"
	if in.CloudProvider == "" {
		return mcp.NewToolResultError("missing required path parameter \"cloud_provider\""), nil
	}
	path = strings.ReplaceAll(path, "{cloud_provider}", url.PathEscape(in.CloudProvider))
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterGetConnectionCredentials(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_get_connection_credentials",
		"This endpoint retrieves the connection credentials required for integration",
		gentypes.SchemaGetConnectionCredentials,
	)
	readOnly := true
	tool.Annotations.ReadOnlyHint = &readOnly
	tool.RawOutputSchema = gentypes.OutputSchemaGetConnectionCredentials
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleGetConnectionCredentials))
}

func (h *Handler) genHandleGetConnectionCredentials(ctx context.Context, req mcp.CallToolRequest, in gentypes.GetConnectionCredentialsInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/cloud_integrations/{cloud_provider}/credentials"
	if in.CloudProvider == "" {
		return mcp.NewToolResultError("missing required path parameter \"cloud_provider\""), nil
	}
	path = strings.ReplaceAll(path, "{cloud_provider}", url.PathEscape(in.CloudProvider))

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterGetService(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_get_service",
		"This endpoint gets a service for the specified cloud provider",
		gentypes.SchemaGetService,
	)
	readOnly := true
	tool.Annotations.ReadOnlyHint = &readOnly
	tool.RawOutputSchema = gentypes.OutputSchemaGetService
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleGetService))
}

func (h *Handler) genHandleGetService(ctx context.Context, req mcp.CallToolRequest, in gentypes.GetServiceInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/cloud_integrations/{cloud_provider}/services/{service_id}"
	if in.CloudProvider == "" {
		return mcp.NewToolResultError("missing required path parameter \"cloud_provider\""), nil
	}
	path = strings.ReplaceAll(path, "{cloud_provider}", url.PathEscape(in.CloudProvider))
	if in.ServiceId == "" {
		return mcp.NewToolResultError("missing required path parameter \"service_id\""), nil
	}
	path = strings.ReplaceAll(path, "{service_id}", url.PathEscape(in.ServiceId))

	q := url.Values{}
	if in.CloudIntegrationId != "" {
		q.Set("cloud_integration_id", in.CloudIntegrationId)
	}
	if len(q) > 0 {
		path += "?" + q.Encode()
	}

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterListAccounts(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_list_accounts",
		"This endpoint lists the accounts for the specified cloud provider",
		gentypes.SchemaListAccounts,
	)
	readOnly := true
	tool.Annotations.ReadOnlyHint = &readOnly
	tool.RawOutputSchema = gentypes.OutputSchemaListAccounts
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleListAccounts))
}

func (h *Handler) genHandleListAccounts(ctx context.Context, req mcp.CallToolRequest, in gentypes.ListAccountsInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/cloud_integrations/{cloud_provider}/accounts"
	if in.CloudProvider == "" {
		return mcp.NewToolResultError("missing required path parameter \"cloud_provider\""), nil
	}
	path = strings.ReplaceAll(path, "{cloud_provider}", url.PathEscape(in.CloudProvider))

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterListServicesMetadata(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_list_services_metadata",
		"This endpoint lists the services metadata for the specified cloud provider",
		gentypes.SchemaListServicesMetadata,
	)
	readOnly := true
	tool.Annotations.ReadOnlyHint = &readOnly
	tool.RawOutputSchema = gentypes.OutputSchemaListServicesMetadata
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleListServicesMetadata))
}

func (h *Handler) genHandleListServicesMetadata(ctx context.Context, req mcp.CallToolRequest, in gentypes.ListServicesMetadataInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/cloud_integrations/{cloud_provider}/services"
	if in.CloudProvider == "" {
		return mcp.NewToolResultError("missing required path parameter \"cloud_provider\""), nil
	}
	path = strings.ReplaceAll(path, "{cloud_provider}", url.PathEscape(in.CloudProvider))

	q := url.Values{}
	if in.CloudIntegrationId != "" {
		q.Set("cloud_integration_id", in.CloudIntegrationId)
	}
	if len(q) > 0 {
		path += "?" + q.Encode()
	}

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterUpdateAccount(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_update_account",
		"This endpoint updates an account for the specified cloud provider",
		gentypes.SchemaUpdateAccount,
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleUpdateAccount))
}

func (h *Handler) genHandleUpdateAccount(ctx context.Context, req mcp.CallToolRequest, in gentypes.UpdateAccountInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/cloud_integrations/{cloud_provider}/accounts/{id}"
	if in.CloudProvider == "" {
		return mcp.NewToolResultError("missing required path parameter \"cloud_provider\""), nil
	}
	path = strings.ReplaceAll(path, "{cloud_provider}", url.PathEscape(in.CloudProvider))
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	res, err := c.Do(ctx, http.MethodPut, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterUpdateService(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_update_service",
		"This endpoint updates a service for the specified cloud provider",
		gentypes.SchemaUpdateService,
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleUpdateService))
}

func (h *Handler) genHandleUpdateService(ctx context.Context, req mcp.CallToolRequest, in gentypes.UpdateServiceInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/cloud_integrations/{cloud_provider}/accounts/{id}/services/{service_id}"
	if in.CloudProvider == "" {
		return mcp.NewToolResultError("missing required path parameter \"cloud_provider\""), nil
	}
	path = strings.ReplaceAll(path, "{cloud_provider}", url.PathEscape(in.CloudProvider))
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))
	if in.ServiceId == "" {
		return mcp.NewToolResultError("missing required path parameter \"service_id\""), nil
	}
	path = strings.ReplaceAll(path, "{service_id}", url.PathEscape(in.ServiceId))

	res, err := c.Do(ctx, http.MethodPut, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}
