// Code generated by cmd/gen-tools. DO NOT EDIT.
// Source: docs/api/openapi.yml

package tools

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strings"

	"github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"

	signozclient "github.com/SigNoz/signoz-mcp-server/internal/client"
	gentypes "github.com/SigNoz/signoz-mcp-server/pkg/types/gentools"
)

// Reference every import unconditionally so tags without (say) path or
// query params still compile. These blanks are free at runtime.
var (
	_ = context.Background
	_ = fmt.Sprintf
	_ = http.MethodGet
	_ url.Values
	_ = strings.ReplaceAll
	_ = signozclient.DefaultQueryTimeout
	_ = mcp.NewTool
	_ server.MCPServer
)

// registerDowntimeschedulesGenerated registers all generated tools for the
// "downtimeschedules" OpenAPI tag.
func (h *Handler) registerDowntimeschedulesGenerated(s *server.MCPServer) {
	h.genRegisterCreateDowntimeSchedule(s)
	h.genRegisterDeleteDowntimeScheduleByID(s)
	h.genRegisterGetDowntimeScheduleByID(s)
	h.genRegisterListDowntimeSchedules(s)
	h.genRegisterUpdateDowntimeScheduleByID(s)
}

func (h *Handler) genRegisterCreateDowntimeSchedule(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_create_downtime_schedule",
		mcp.WithDescription("POST /api/v1/downtime_schedules — Create downtime schedule"),
		withRawSchema(gentypes.SchemaCreateDowntimeSchedule),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleCreateDowntimeSchedule))
}

func (h *Handler) genHandleCreateDowntimeSchedule(ctx context.Context, req mcp.CallToolRequest, in gentypes.CreateDowntimeScheduleInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/downtime_schedules"

	res, err := c.Do(ctx, http.MethodPost, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterDeleteDowntimeScheduleByID(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_delete_downtime_schedule_by_id",
		mcp.WithDescription("DELETE /api/v1/downtime_schedules/{id} — Delete downtime schedule"),
		mcp.WithDestructiveHintAnnotation(true),
		withRawSchema(gentypes.SchemaDeleteDowntimeScheduleByID),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleDeleteDowntimeScheduleByID))
}

func (h *Handler) genHandleDeleteDowntimeScheduleByID(ctx context.Context, req mcp.CallToolRequest, in gentypes.DeleteDowntimeScheduleByIDInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/downtime_schedules/{id}"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	res, err := c.Do(ctx, http.MethodDelete, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterGetDowntimeScheduleByID(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_get_downtime_schedule_by_id",
		mcp.WithDescription("GET /api/v1/downtime_schedules/{id} — Get downtime schedule by ID"),
		mcp.WithReadOnlyHintAnnotation(true),
		withRawSchema(gentypes.SchemaGetDowntimeScheduleByID),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleGetDowntimeScheduleByID))
}

func (h *Handler) genHandleGetDowntimeScheduleByID(ctx context.Context, req mcp.CallToolRequest, in gentypes.GetDowntimeScheduleByIDInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/downtime_schedules/{id}"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterListDowntimeSchedules(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_list_downtime_schedules",
		mcp.WithDescription("GET /api/v1/downtime_schedules — List downtime schedules"),
		mcp.WithReadOnlyHintAnnotation(true),
		withRawSchema(gentypes.SchemaListDowntimeSchedules),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleListDowntimeSchedules))
}

func (h *Handler) genHandleListDowntimeSchedules(ctx context.Context, req mcp.CallToolRequest, in gentypes.ListDowntimeSchedulesInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/downtime_schedules"

	q := url.Values{}
	if in.Active != false {
		q.Set("active", fmt.Sprintf("%t", in.Active))
	}
	if in.Recurring != false {
		q.Set("recurring", fmt.Sprintf("%t", in.Recurring))
	}
	if len(q) > 0 {
		path += "?" + q.Encode()
	}

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterUpdateDowntimeScheduleByID(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_update_downtime_schedule_by_id",
		mcp.WithDescription("PUT /api/v1/downtime_schedules/{id} — Update downtime schedule"),
		withRawSchema(gentypes.SchemaUpdateDowntimeScheduleByID),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleUpdateDowntimeScheduleByID))
}

func (h *Handler) genHandleUpdateDowntimeScheduleByID(ctx context.Context, req mcp.CallToolRequest, in gentypes.UpdateDowntimeScheduleByIDInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/downtime_schedules/{id}"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	res, err := c.Do(ctx, http.MethodPut, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}
