// Code generated by cmd/gen-tools. DO NOT EDIT.
// Source: docs/api/openapi.yml

package tools

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strings"

	"github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"

	signozclient "github.com/SigNoz/signoz-mcp-server/internal/client"
	gentypes "github.com/SigNoz/signoz-mcp-server/pkg/types/gentools"
)

// Reference every import unconditionally so tags without (say) path or
// query params still compile. These blanks are free at runtime.
var (
	_ = context.Background
	_ = fmt.Sprintf
	_ = http.MethodGet
	_ url.Values
	_ = strings.ReplaceAll
	_ = signozclient.DefaultQueryTimeout
	_ = mcp.NewTool
	_ server.MCPServer
)

// registerAuthzGenerated registers all generated tools for the
// "authz" OpenAPI tag.
func (h *Handler) registerAuthzGenerated(s *server.MCPServer) {
	h.genRegisterAuthzCheck(s)
	h.genRegisterAuthzResources(s)
}

func (h *Handler) genRegisterAuthzCheck(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_authz_check",
		"Checks if the authenticated user has permissions for given transactions",
		gentypes.SchemaAuthzCheck,
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleAuthzCheck))
}

func (h *Handler) genHandleAuthzCheck(ctx context.Context, req mcp.CallToolRequest, in gentypes.AuthzCheckInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/authz/check"

	res, err := c.Do(ctx, http.MethodPost, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterAuthzResources(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_authz_resources",
		"Gets all the available resources",
		gentypes.SchemaAuthzResources,
	)
	readOnly := true
	tool.Annotations.ReadOnlyHint = &readOnly
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleAuthzResources))
}

func (h *Handler) genHandleAuthzResources(ctx context.Context, req mcp.CallToolRequest, in gentypes.AuthzResourcesInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v1/authz/resources"

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}
