// Code generated by cmd/gen-tools. DO NOT EDIT.
// Source: docs/api/openapi.yml

package tools

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strings"

	"github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"

	signozclient "github.com/SigNoz/signoz-mcp-server/internal/client"
	gentypes "github.com/SigNoz/signoz-mcp-server/pkg/types/gentools"
)

// Reference every import unconditionally so tags without (say) path or
// query params still compile. These blanks are free at runtime.
var (
	_ = context.Background
	_ = fmt.Sprintf
	_ = http.MethodGet
	_ url.Values
	_ = strings.ReplaceAll
	_ = signozclient.DefaultQueryTimeout
	_ = mcp.NewTool
	_ server.MCPServer
)

// registerRulesGenerated registers all generated tools for the
// "rules" OpenAPI tag.
func (h *Handler) registerRulesGenerated(s *server.MCPServer) {
	h.genRegisterCreateRule(s)
	h.genRegisterDeleteRuleByID(s)
	h.genRegisterGetRuleByID(s)
	h.genRegisterGetRuleHistoryFilterKeys(s)
	h.genRegisterGetRuleHistoryFilterValues(s)
	h.genRegisterGetRuleHistoryOverallStatus(s)
	h.genRegisterGetRuleHistoryStats(s)
	h.genRegisterGetRuleHistoryTimeline(s)
	h.genRegisterGetRuleHistoryTopContributors(s)
	h.genRegisterListRules(s)
	h.genRegisterPatchRuleByID(s)
	h.genRegisterTestRule(s)
	h.genRegisterUpdateRuleByID(s)
}

func (h *Handler) genRegisterCreateRule(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_create_rule",
		mcp.WithDescription("POST /api/v2/rules — Create alert rule"),
		withRawSchema(gentypes.SchemaCreateRule),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleCreateRule))
}

func (h *Handler) genHandleCreateRule(ctx context.Context, req mcp.CallToolRequest, in gentypes.CreateRuleInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/rules"

	res, err := c.Do(ctx, http.MethodPost, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterDeleteRuleByID(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_delete_rule_by_id",
		mcp.WithDescription("DELETE /api/v2/rules/{id} — Delete alert rule"),
		mcp.WithDestructiveHintAnnotation(true),
		withRawSchema(gentypes.SchemaDeleteRuleByID),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleDeleteRuleByID))
}

func (h *Handler) genHandleDeleteRuleByID(ctx context.Context, req mcp.CallToolRequest, in gentypes.DeleteRuleByIDInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/rules/{id}"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	res, err := c.Do(ctx, http.MethodDelete, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterGetRuleByID(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_get_rule_by_id",
		mcp.WithDescription("GET /api/v2/rules/{id} — Get alert rule by ID"),
		mcp.WithReadOnlyHintAnnotation(true),
		withRawSchema(gentypes.SchemaGetRuleByID),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleGetRuleByID))
}

func (h *Handler) genHandleGetRuleByID(ctx context.Context, req mcp.CallToolRequest, in gentypes.GetRuleByIDInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/rules/{id}"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterGetRuleHistoryFilterKeys(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_get_rule_history_filter_keys",
		mcp.WithDescription("GET /api/v2/rules/{id}/history/filter_keys — Get rule history filter keys"),
		mcp.WithReadOnlyHintAnnotation(true),
		withRawSchema(gentypes.SchemaGetRuleHistoryFilterKeys),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleGetRuleHistoryFilterKeys))
}

func (h *Handler) genHandleGetRuleHistoryFilterKeys(ctx context.Context, req mcp.CallToolRequest, in gentypes.GetRuleHistoryFilterKeysInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/rules/{id}/history/filter_keys"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	q := url.Values{}
	if in.Signal != "" {
		q.Set("signal", in.Signal)
	}
	if in.Source != "" {
		q.Set("source", in.Source)
	}
	if in.Limit != 0 {
		q.Set("limit", fmt.Sprintf("%d", in.Limit))
	}
	if in.StartUnixMilli != 0 {
		q.Set("startUnixMilli", fmt.Sprintf("%d", in.StartUnixMilli))
	}
	if in.EndUnixMilli != 0 {
		q.Set("endUnixMilli", fmt.Sprintf("%d", in.EndUnixMilli))
	}
	if in.FieldContext != "" {
		q.Set("fieldContext", in.FieldContext)
	}
	if in.FieldDataType != "" {
		q.Set("fieldDataType", in.FieldDataType)
	}
	if in.MetricName != "" {
		q.Set("metricName", in.MetricName)
	}
	if in.MetricNamespace != "" {
		q.Set("metricNamespace", in.MetricNamespace)
	}
	if in.SearchText != "" {
		q.Set("searchText", in.SearchText)
	}
	if len(q) > 0 {
		path += "?" + q.Encode()
	}

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterGetRuleHistoryFilterValues(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_get_rule_history_filter_values",
		mcp.WithDescription("GET /api/v2/rules/{id}/history/filter_values — Get rule history filter values"),
		mcp.WithReadOnlyHintAnnotation(true),
		withRawSchema(gentypes.SchemaGetRuleHistoryFilterValues),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleGetRuleHistoryFilterValues))
}

func (h *Handler) genHandleGetRuleHistoryFilterValues(ctx context.Context, req mcp.CallToolRequest, in gentypes.GetRuleHistoryFilterValuesInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/rules/{id}/history/filter_values"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	q := url.Values{}
	if in.Signal != "" {
		q.Set("signal", in.Signal)
	}
	if in.Source != "" {
		q.Set("source", in.Source)
	}
	if in.Limit != 0 {
		q.Set("limit", fmt.Sprintf("%d", in.Limit))
	}
	if in.StartUnixMilli != 0 {
		q.Set("startUnixMilli", fmt.Sprintf("%d", in.StartUnixMilli))
	}
	if in.EndUnixMilli != 0 {
		q.Set("endUnixMilli", fmt.Sprintf("%d", in.EndUnixMilli))
	}
	if in.FieldContext != "" {
		q.Set("fieldContext", in.FieldContext)
	}
	if in.FieldDataType != "" {
		q.Set("fieldDataType", in.FieldDataType)
	}
	if in.MetricName != "" {
		q.Set("metricName", in.MetricName)
	}
	if in.MetricNamespace != "" {
		q.Set("metricNamespace", in.MetricNamespace)
	}
	if in.SearchText != "" {
		q.Set("searchText", in.SearchText)
	}
	if in.Name != "" {
		q.Set("name", in.Name)
	}
	if in.ExistingQuery != "" {
		q.Set("existingQuery", in.ExistingQuery)
	}
	if len(q) > 0 {
		path += "?" + q.Encode()
	}

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterGetRuleHistoryOverallStatus(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_get_rule_history_overall_status",
		mcp.WithDescription("GET /api/v2/rules/{id}/history/overall_status — Get rule overall status timeline"),
		mcp.WithReadOnlyHintAnnotation(true),
		withRawSchema(gentypes.SchemaGetRuleHistoryOverallStatus),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleGetRuleHistoryOverallStatus))
}

func (h *Handler) genHandleGetRuleHistoryOverallStatus(ctx context.Context, req mcp.CallToolRequest, in gentypes.GetRuleHistoryOverallStatusInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/rules/{id}/history/overall_status"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	q := url.Values{}
	if in.Start != 0 {
		q.Set("start", fmt.Sprintf("%d", in.Start))
	}
	if in.End != 0 {
		q.Set("end", fmt.Sprintf("%d", in.End))
	}
	if len(q) > 0 {
		path += "?" + q.Encode()
	}

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterGetRuleHistoryStats(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_get_rule_history_stats",
		mcp.WithDescription("GET /api/v2/rules/{id}/history/stats — Get rule history stats"),
		mcp.WithReadOnlyHintAnnotation(true),
		withRawSchema(gentypes.SchemaGetRuleHistoryStats),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleGetRuleHistoryStats))
}

func (h *Handler) genHandleGetRuleHistoryStats(ctx context.Context, req mcp.CallToolRequest, in gentypes.GetRuleHistoryStatsInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/rules/{id}/history/stats"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	q := url.Values{}
	if in.Start != 0 {
		q.Set("start", fmt.Sprintf("%d", in.Start))
	}
	if in.End != 0 {
		q.Set("end", fmt.Sprintf("%d", in.End))
	}
	if len(q) > 0 {
		path += "?" + q.Encode()
	}

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterGetRuleHistoryTimeline(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_get_rule_history_timeline",
		mcp.WithDescription("GET /api/v2/rules/{id}/history/timeline — Get rule history timeline"),
		mcp.WithReadOnlyHintAnnotation(true),
		withRawSchema(gentypes.SchemaGetRuleHistoryTimeline),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleGetRuleHistoryTimeline))
}

func (h *Handler) genHandleGetRuleHistoryTimeline(ctx context.Context, req mcp.CallToolRequest, in gentypes.GetRuleHistoryTimelineInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/rules/{id}/history/timeline"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	q := url.Values{}
	if in.Start != 0 {
		q.Set("start", fmt.Sprintf("%d", in.Start))
	}
	if in.End != 0 {
		q.Set("end", fmt.Sprintf("%d", in.End))
	}
	if in.State != "" {
		q.Set("state", in.State)
	}
	if in.FilterExpression != "" {
		q.Set("filterExpression", in.FilterExpression)
	}
	if in.Limit != 0 {
		q.Set("limit", fmt.Sprintf("%d", in.Limit))
	}
	if in.Order != "" {
		q.Set("order", in.Order)
	}
	if in.Cursor != "" {
		q.Set("cursor", in.Cursor)
	}
	if len(q) > 0 {
		path += "?" + q.Encode()
	}

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterGetRuleHistoryTopContributors(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_get_rule_history_top_contributors",
		mcp.WithDescription("GET /api/v2/rules/{id}/history/top_contributors — Get top contributors to rule firing"),
		mcp.WithReadOnlyHintAnnotation(true),
		withRawSchema(gentypes.SchemaGetRuleHistoryTopContributors),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleGetRuleHistoryTopContributors))
}

func (h *Handler) genHandleGetRuleHistoryTopContributors(ctx context.Context, req mcp.CallToolRequest, in gentypes.GetRuleHistoryTopContributorsInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/rules/{id}/history/top_contributors"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	q := url.Values{}
	if in.Start != 0 {
		q.Set("start", fmt.Sprintf("%d", in.Start))
	}
	if in.End != 0 {
		q.Set("end", fmt.Sprintf("%d", in.End))
	}
	if len(q) > 0 {
		path += "?" + q.Encode()
	}

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterListRules(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_list_rules",
		mcp.WithDescription("GET /api/v2/rules — List alert rules"),
		mcp.WithReadOnlyHintAnnotation(true),
		withRawSchema(gentypes.SchemaListRules),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleListRules))
}

func (h *Handler) genHandleListRules(ctx context.Context, req mcp.CallToolRequest, in gentypes.ListRulesInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/rules"

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterPatchRuleByID(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_patch_rule_by_id",
		mcp.WithDescription("PATCH /api/v2/rules/{id} — Patch alert rule"),
		withRawSchema(gentypes.SchemaPatchRuleByID),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandlePatchRuleByID))
}

func (h *Handler) genHandlePatchRuleByID(ctx context.Context, req mcp.CallToolRequest, in gentypes.PatchRuleByIDInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/rules/{id}"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	res, err := c.Do(ctx, http.MethodPatch, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterTestRule(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_test_rule",
		mcp.WithDescription("POST /api/v2/rules/test — Test alert rule"),
		withRawSchema(gentypes.SchemaTestRule),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleTestRule))
}

func (h *Handler) genHandleTestRule(ctx context.Context, req mcp.CallToolRequest, in gentypes.TestRuleInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/rules/test"

	res, err := c.Do(ctx, http.MethodPost, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterUpdateRuleByID(s *server.MCPServer) {
	tool := mcp.NewTool("signoz_update_rule_by_id",
		mcp.WithDescription("PUT /api/v2/rules/{id} — Update alert rule"),
		withRawSchema(gentypes.SchemaUpdateRuleByID),
	)
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleUpdateRuleByID))
}

func (h *Handler) genHandleUpdateRuleByID(ctx context.Context, req mcp.CallToolRequest, in gentypes.UpdateRuleByIDInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/rules/{id}"
	if in.Id == "" {
		return mcp.NewToolResultError("missing required path parameter \"id\""), nil
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(in.Id))

	res, err := c.Do(ctx, http.MethodPut, path, in.Body, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}
