// Code generated by cmd/gen-tools. DO NOT EDIT.
// Source: docs/api/openapi.yml

package tools

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strings"

	"github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"

	signozclient "github.com/SigNoz/signoz-mcp-server/internal/client"
	gentypes "github.com/SigNoz/signoz-mcp-server/pkg/types/gentools"
)

// Reference every import unconditionally so tags without (say) path or
// query params still compile. These blanks are free at runtime.
var (
	_ = context.Background
	_ = fmt.Sprintf
	_ = http.MethodGet
	_ url.Values
	_ = strings.ReplaceAll
	_ = signozclient.DefaultQueryTimeout
	_ = mcp.NewTool
	_ server.MCPServer
)

// registerHealthGenerated registers all generated tools for the
// "health" OpenAPI tag.
func (h *Handler) registerHealthGenerated(s *server.MCPServer) {
	h.genRegisterHealthz(s)
	h.genRegisterLivez(s)
	h.genRegisterReadyz(s)
}

func (h *Handler) genRegisterHealthz(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_healthz",
		"Health check",
		gentypes.SchemaHealthz,
	)
	readOnly := true
	tool.Annotations.ReadOnlyHint = &readOnly
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleHealthz))
}

func (h *Handler) genHandleHealthz(ctx context.Context, req mcp.CallToolRequest, in gentypes.HealthzInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/healthz"

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterLivez(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_livez",
		"Liveness check",
		gentypes.SchemaLivez,
	)
	readOnly := true
	tool.Annotations.ReadOnlyHint = &readOnly
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleLivez))
}

func (h *Handler) genHandleLivez(ctx context.Context, req mcp.CallToolRequest, in gentypes.LivezInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/livez"

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}

func (h *Handler) genRegisterReadyz(s *server.MCPServer) {
	tool := mcp.NewToolWithRawSchema(
		"signoz_readyz",
		"Readiness check",
		gentypes.SchemaReadyz,
	)
	readOnly := true
	tool.Annotations.ReadOnlyHint = &readOnly
	s.AddTool(tool, mcp.NewTypedToolHandler(h.genHandleReadyz))
}

func (h *Handler) genHandleReadyz(ctx context.Context, req mcp.CallToolRequest, in gentypes.ReadyzInput) (*mcp.CallToolResult, error) {
	c, err := h.GetClient(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	path := "/api/v2/readyz"

	res, err := c.Do(ctx, http.MethodGet, path, nil, signozclient.DefaultQueryTimeout)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(res)), nil
}
