// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apitypes

// TelemetrytypesTelemetryFieldValues defines model for TelemetrytypesTelemetryFieldValues.
type TelemetrytypesTelemetryFieldValues struct {
	BoolValues    *[]bool    `json:"boolValues,omitempty"`
	NumberValues  *[]float64 `json:"numberValues,omitempty"`
	RelatedValues *[]string  `json:"relatedValues,omitempty"`
	StringValues  *[]string  `json:"stringValues,omitempty"`
}
