// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apitypes

// Defines values for DashboardtypesListSort.
const (
	DashboardtypesListSortCreatedAt DashboardtypesListSort = "created_at"
	DashboardtypesListSortName      DashboardtypesListSort = "name"
	DashboardtypesListSortUpdatedAt DashboardtypesListSort = "updated_at"
)

// Valid indicates whether the value is a known member of the DashboardtypesListSort enum.
func (e DashboardtypesListSort) Valid() bool {
	switch e {
	case DashboardtypesListSortCreatedAt:
		return true
	case DashboardtypesListSortName:
		return true
	case DashboardtypesListSortUpdatedAt:
		return true
	default:
		return false
	}
}

// DashboardtypesListSort defines model for DashboardtypesListSort.
type DashboardtypesListSort string
