// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apitypes

// RuletypesListableRules defines model for RuletypesListableRules.
type RuletypesListableRules struct {
	Labels           []RuletypesLabelPair    `json:"labels"`
	ReservedKeywords []string                `json:"reservedKeywords"`
	Rules            []RuletypesListableRule `json:"rules"`
	Total            int64                   `json:"total"`
}
