// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apitypes

// MetricsexplorertypesMetricAlert defines model for MetricsexplorertypesMetricAlert.
type MetricsexplorertypesMetricAlert struct {
	AlertId   string `json:"alertId"`
	AlertName string `json:"alertName"`
}
