// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apitypes

// Defines values for MetricsexplorertypesTreemapMode.
const (
	MetricsexplorertypesTreemapModeSamples    MetricsexplorertypesTreemapMode = "samples"
	MetricsexplorertypesTreemapModeTimeseries MetricsexplorertypesTreemapMode = "timeseries"
)

// Valid indicates whether the value is a known member of the MetricsexplorertypesTreemapMode enum.
func (e MetricsexplorertypesTreemapMode) Valid() bool {
	switch e {
	case MetricsexplorertypesTreemapModeSamples:
		return true
	case MetricsexplorertypesTreemapModeTimeseries:
		return true
	default:
		return false
	}
}

// MetricsexplorertypesTreemapMode defines model for MetricsexplorertypesTreemapMode.
type MetricsexplorertypesTreemapMode string
