// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apitypes

// Defines values for RuletypesListSort.
const (
	RuletypesListSortCreatedAt RuletypesListSort = "created_at"
	RuletypesListSortName      RuletypesListSort = "name"
	RuletypesListSortSeverity  RuletypesListSort = "severity"
	RuletypesListSortState     RuletypesListSort = "state"
	RuletypesListSortUpdatedAt RuletypesListSort = "updated_at"
)

// Valid indicates whether the value is a known member of the RuletypesListSort enum.
func (e RuletypesListSort) Valid() bool {
	switch e {
	case RuletypesListSortCreatedAt:
		return true
	case RuletypesListSortName:
		return true
	case RuletypesListSortSeverity:
		return true
	case RuletypesListSortState:
		return true
	case RuletypesListSortUpdatedAt:
		return true
	default:
		return false
	}
}

// RuletypesListSort defines model for RuletypesListSort.
type RuletypesListSort string
