// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apitypes

// Defines values for MetrictypesType.
const (
	MetrictypesTypeExponentialhistogram MetrictypesType = "exponentialhistogram"
	MetrictypesTypeGauge                MetrictypesType = "gauge"
	MetrictypesTypeHistogram            MetrictypesType = "histogram"
	MetrictypesTypeSum                  MetrictypesType = "sum"
	MetrictypesTypeSummary              MetrictypesType = "summary"
)

// Valid indicates whether the value is a known member of the MetrictypesType enum.
func (e MetrictypesType) Valid() bool {
	switch e {
	case MetrictypesTypeExponentialhistogram:
		return true
	case MetrictypesTypeGauge:
		return true
	case MetrictypesTypeHistogram:
		return true
	case MetrictypesTypeSum:
		return true
	case MetrictypesTypeSummary:
		return true
	default:
		return false
	}
}

// MetrictypesType defines model for MetrictypesType.
type MetrictypesType string
