// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apitypes

// Querybuildertypesv5TimeSeriesValue defines model for Querybuildertypesv5TimeSeriesValue.
type Querybuildertypesv5TimeSeriesValue struct {
	Partial   *bool      `json:"partial,omitempty"`
	Timestamp *int64     `json:"timestamp,omitempty"`
	Value     *float64   `json:"value,omitempty"`
	Values    *[]float64 `json:"values,omitempty"`
}
