// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apitypes

// RulestatehistorytypesGettableRuleStateHistory defines model for RulestatehistorytypesGettableRuleStateHistory.
type RulestatehistorytypesGettableRuleStateHistory struct {
	Fingerprint         int                         `json:"fingerprint"`
	Labels              *[]Querybuildertypesv5Label `json:"labels"`
	OverallState        RuletypesAlertState         `json:"overallState"`
	OverallStateChanged bool                        `json:"overallStateChanged"`
	RelatedAITracesLink *string                     `json:"relatedAITracesLink,omitempty"`
	RelatedLogsLink     *string                     `json:"relatedLogsLink,omitempty"`
	RelatedTracesLink   *string                     `json:"relatedTracesLink,omitempty"`
	RuleId              string                      `json:"ruleId"`
	RuleName            string                      `json:"ruleName"`
	State               RuletypesAlertState         `json:"state"`
	StateChanged        bool                        `json:"stateChanged"`
	UnixMilli           int64                       `json:"unixMilli"`
	Value               float64                     `json:"value"`
}
