// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apitypes

// Defines values for AlertmanagertypesChannelListSort.
const (
	AlertmanagertypesChannelListSortCreatedAt AlertmanagertypesChannelListSort = "created_at"
	AlertmanagertypesChannelListSortName      AlertmanagertypesChannelListSort = "name"
	AlertmanagertypesChannelListSortUpdatedAt AlertmanagertypesChannelListSort = "updated_at"
)

// Valid indicates whether the value is a known member of the AlertmanagertypesChannelListSort enum.
func (e AlertmanagertypesChannelListSort) Valid() bool {
	switch e {
	case AlertmanagertypesChannelListSortCreatedAt:
		return true
	case AlertmanagertypesChannelListSortName:
		return true
	case AlertmanagertypesChannelListSortUpdatedAt:
		return true
	default:
		return false
	}
}

// AlertmanagertypesChannelListSort defines model for AlertmanagertypesChannelListSort.
type AlertmanagertypesChannelListSort string
