// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apitypes

// Querybuildertypesv5TimeSeriesData defines model for Querybuildertypesv5TimeSeriesData.
type Querybuildertypesv5TimeSeriesData struct {
	Aggregations *[]Querybuildertypesv5AggregationBucket `json:"aggregations,omitempty"`
	QueryName    *string                                 `json:"queryName,omitempty"`
}
