// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apitypes

// Defines values for RuletypesListOrder.
const (
	RuletypesListOrderAsc  RuletypesListOrder = "asc"
	RuletypesListOrderDesc RuletypesListOrder = "desc"
)

// Valid indicates whether the value is a known member of the RuletypesListOrder enum.
func (e RuletypesListOrder) Valid() bool {
	switch e {
	case RuletypesListOrderAsc:
		return true
	case RuletypesListOrderDesc:
		return true
	default:
		return false
	}
}

// RuletypesListOrder defines model for RuletypesListOrder.
type RuletypesListOrder string
