// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apitypes

// Querybuildertypesv5RawData defines model for Querybuildertypesv5RawData.
type Querybuildertypesv5RawData struct {
	NextCursor *string                      `json:"nextCursor,omitempty"`
	QueryName  *string                      `json:"queryName,omitempty"`
	Rows       *[]Querybuildertypesv5RawRow `json:"rows,omitempty"`
}
