// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apitypes

// Defines values for DashboardtypesListOrder.
const (
	DashboardtypesListOrderAsc  DashboardtypesListOrder = "asc"
	DashboardtypesListOrderDesc DashboardtypesListOrder = "desc"
)

// Valid indicates whether the value is a known member of the DashboardtypesListOrder enum.
func (e DashboardtypesListOrder) Valid() bool {
	switch e {
	case DashboardtypesListOrderAsc:
		return true
	case DashboardtypesListOrderDesc:
		return true
	default:
		return false
	}
}

// DashboardtypesListOrder defines model for DashboardtypesListOrder.
type DashboardtypesListOrder string
