// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apitypes

// Querybuildertypesv5ScalarData defines model for Querybuildertypesv5ScalarData.
type Querybuildertypesv5ScalarData struct {
	Columns   *[]Querybuildertypesv5ColumnDescriptor `json:"columns,omitempty"`
	Data      *[][]interface{}                       `json:"data,omitempty"`
	QueryName *string                                `json:"queryName,omitempty"`
}
