// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apitypes

// Querybuildertypesv5QueryWarnDataAdditional defines model for Querybuildertypesv5QueryWarnDataAdditional.
type Querybuildertypesv5QueryWarnDataAdditional struct {
	Message *string `json:"message,omitempty"`
}
