// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apitypes

// AlertmanagertypesChannelSlackField defines model for AlertmanagertypesChannelSlackField.
type AlertmanagertypesChannelSlackField struct {
	Short *bool  `json:"short,omitempty"`
	Title string `json:"title"`
	Value string `json:"value"`
}
