// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apitypes

// RuletypesLabelPair defines model for RuletypesLabelPair.
type RuletypesLabelPair struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}
