// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apitypes

// Querybuildertypesv5AggregationBucket defines model for Querybuildertypesv5AggregationBucket.
type Querybuildertypesv5AggregationBucket struct {
	Alias            *string                             `json:"alias,omitempty"`
	AnomalyScores    *[]Querybuildertypesv5TimeSeries    `json:"anomalyScores,omitempty"`
	Index            *int                                `json:"index,omitempty"`
	LowerBoundSeries *[]Querybuildertypesv5TimeSeries    `json:"lowerBoundSeries,omitempty"`
	Meta             *Querybuildertypesv5AggregationMeta `json:"meta,omitempty"`
	PredictedSeries  *[]Querybuildertypesv5TimeSeries    `json:"predictedSeries,omitempty"`
	Series           *[]Querybuildertypesv5TimeSeries    `json:"series,omitempty"`
	UpperBoundSeries *[]Querybuildertypesv5TimeSeries    `json:"upperBoundSeries,omitempty"`
}
