// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apitypes

// MetricsexplorertypesTreemapRequest defines model for MetricsexplorertypesTreemapRequest.
type MetricsexplorertypesTreemapRequest struct {
	End    int64                           `json:"end"`
	Filter *Querybuildertypesv5Filter      `json:"filter,omitempty"`
	Limit  int                             `json:"limit"`
	Mode   MetricsexplorertypesTreemapMode `json:"mode"`
	Start  int64                           `json:"start"`
}
