// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apitypes

// Querybuildertypesv5AggregationMeta defines model for Querybuildertypesv5AggregationMeta.
type Querybuildertypesv5AggregationMeta struct {
	Buckets *[]float64 `json:"buckets,omitempty"`
	Unit    *string    `json:"unit,omitempty"`
}
