// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apitypes

// Querybuildertypesv5TimeSeries defines model for Querybuildertypesv5TimeSeries.
type Querybuildertypesv5TimeSeries struct {
	Labels *[]Querybuildertypesv5Label           `json:"labels,omitempty"`
	Values *[]Querybuildertypesv5TimeSeriesValue `json:"values,omitempty"`
}
