// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apitypes

import (
	"encoding/json"

	"github.com/oapi-codegen/runtime"
)

// Querybuildertypesv5Label defines model for Querybuildertypesv5Label.
type Querybuildertypesv5Label struct {
	Key   *TelemetrytypesTelemetryFieldKey `json:"key,omitempty"`
	Value *Querybuildertypesv5Label_Value  `json:"value,omitempty"`
}

// Querybuildertypesv5LabelValue0 defines model for .
type Querybuildertypesv5LabelValue0 = string

// Querybuildertypesv5LabelValue1 defines model for .
type Querybuildertypesv5LabelValue1 = float32

// Querybuildertypesv5LabelValue2 defines model for .
type Querybuildertypesv5LabelValue2 = bool

// Querybuildertypesv5Label_Value defines model for Querybuildertypesv5Label.Value.
type Querybuildertypesv5Label_Value struct {
	union json.RawMessage
}

// AsQuerybuildertypesv5LabelValue0 returns the union data inside the Querybuildertypesv5Label_Value as a Querybuildertypesv5LabelValue0
func (t Querybuildertypesv5Label_Value) AsQuerybuildertypesv5LabelValue0() (Querybuildertypesv5LabelValue0, error) {
	var body Querybuildertypesv5LabelValue0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromQuerybuildertypesv5LabelValue0 overwrites any union data inside the Querybuildertypesv5Label_Value as the provided Querybuildertypesv5LabelValue0
func (t *Querybuildertypesv5Label_Value) FromQuerybuildertypesv5LabelValue0(v Querybuildertypesv5LabelValue0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeQuerybuildertypesv5LabelValue0 performs a merge with any union data inside the Querybuildertypesv5Label_Value, using the provided Querybuildertypesv5LabelValue0
func (t *Querybuildertypesv5Label_Value) MergeQuerybuildertypesv5LabelValue0(v Querybuildertypesv5LabelValue0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsQuerybuildertypesv5LabelValue1 returns the union data inside the Querybuildertypesv5Label_Value as a Querybuildertypesv5LabelValue1
func (t Querybuildertypesv5Label_Value) AsQuerybuildertypesv5LabelValue1() (Querybuildertypesv5LabelValue1, error) {
	var body Querybuildertypesv5LabelValue1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromQuerybuildertypesv5LabelValue1 overwrites any union data inside the Querybuildertypesv5Label_Value as the provided Querybuildertypesv5LabelValue1
func (t *Querybuildertypesv5Label_Value) FromQuerybuildertypesv5LabelValue1(v Querybuildertypesv5LabelValue1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeQuerybuildertypesv5LabelValue1 performs a merge with any union data inside the Querybuildertypesv5Label_Value, using the provided Querybuildertypesv5LabelValue1
func (t *Querybuildertypesv5Label_Value) MergeQuerybuildertypesv5LabelValue1(v Querybuildertypesv5LabelValue1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsQuerybuildertypesv5LabelValue2 returns the union data inside the Querybuildertypesv5Label_Value as a Querybuildertypesv5LabelValue2
func (t Querybuildertypesv5Label_Value) AsQuerybuildertypesv5LabelValue2() (Querybuildertypesv5LabelValue2, error) {
	var body Querybuildertypesv5LabelValue2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromQuerybuildertypesv5LabelValue2 overwrites any union data inside the Querybuildertypesv5Label_Value as the provided Querybuildertypesv5LabelValue2
func (t *Querybuildertypesv5Label_Value) FromQuerybuildertypesv5LabelValue2(v Querybuildertypesv5LabelValue2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeQuerybuildertypesv5LabelValue2 performs a merge with any union data inside the Querybuildertypesv5Label_Value, using the provided Querybuildertypesv5LabelValue2
func (t *Querybuildertypesv5Label_Value) MergeQuerybuildertypesv5LabelValue2(v Querybuildertypesv5LabelValue2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Querybuildertypesv5Label_Value) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Querybuildertypesv5Label_Value) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
