// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apitypes

// MetricsexplorertypesTreemapResponse defines model for MetricsexplorertypesTreemapResponse.
type MetricsexplorertypesTreemapResponse struct {
	Samples    *[]MetricsexplorertypesTreemapEntry `json:"samples"`
	Timeseries *[]MetricsexplorertypesTreemapEntry `json:"timeseries"`
}
