// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apitypes

// Defines values for AlertmanagertypesChannelListOrder.
const (
	AlertmanagertypesChannelListOrderAsc  AlertmanagertypesChannelListOrder = "asc"
	AlertmanagertypesChannelListOrderDesc AlertmanagertypesChannelListOrder = "desc"
)

// Valid indicates whether the value is a known member of the AlertmanagertypesChannelListOrder enum.
func (e AlertmanagertypesChannelListOrder) Valid() bool {
	switch e {
	case AlertmanagertypesChannelListOrderAsc:
		return true
	case AlertmanagertypesChannelListOrderDesc:
		return true
	default:
		return false
	}
}

// AlertmanagertypesChannelListOrder defines model for AlertmanagertypesChannelListOrder.
type AlertmanagertypesChannelListOrder string
