// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apitypes

// AlertmanagertypesChannelSlackAction defines model for AlertmanagertypesChannelSlackAction.
type AlertmanagertypesChannelSlackAction struct {
	Confirm *AlertmanagertypesChannelSlackConfirmation `json:"confirm,omitempty"`
	Name    *string                                    `json:"name,omitempty"`
	Style   *string                                    `json:"style,omitempty"`
	Text    string                                     `json:"text"`
	Type    string                                     `json:"type"`
	Url     *string                                    `json:"url,omitempty"`
	Value   *string                                    `json:"value,omitempty"`
}
