// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apitypes

import (
	"encoding/json"
	"fmt"

	"github.com/oapi-codegen/runtime"
)

// Querybuildertypesv5QueryData defines model for Querybuildertypesv5QueryData.
type Querybuildertypesv5QueryData struct {
	Results *[]interface{} `json:"results,omitempty"`
	union   json.RawMessage
}

// AsQuerybuildertypesv5TimeSeriesData returns the union data inside the Querybuildertypesv5QueryData as a Querybuildertypesv5TimeSeriesData
func (t Querybuildertypesv5QueryData) AsQuerybuildertypesv5TimeSeriesData() (Querybuildertypesv5TimeSeriesData, error) {
	var body Querybuildertypesv5TimeSeriesData
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromQuerybuildertypesv5TimeSeriesData overwrites any union data inside the Querybuildertypesv5QueryData as the provided Querybuildertypesv5TimeSeriesData
func (t *Querybuildertypesv5QueryData) FromQuerybuildertypesv5TimeSeriesData(v Querybuildertypesv5TimeSeriesData) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeQuerybuildertypesv5TimeSeriesData performs a merge with any union data inside the Querybuildertypesv5QueryData, using the provided Querybuildertypesv5TimeSeriesData
func (t *Querybuildertypesv5QueryData) MergeQuerybuildertypesv5TimeSeriesData(v Querybuildertypesv5TimeSeriesData) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsQuerybuildertypesv5ScalarData returns the union data inside the Querybuildertypesv5QueryData as a Querybuildertypesv5ScalarData
func (t Querybuildertypesv5QueryData) AsQuerybuildertypesv5ScalarData() (Querybuildertypesv5ScalarData, error) {
	var body Querybuildertypesv5ScalarData
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromQuerybuildertypesv5ScalarData overwrites any union data inside the Querybuildertypesv5QueryData as the provided Querybuildertypesv5ScalarData
func (t *Querybuildertypesv5QueryData) FromQuerybuildertypesv5ScalarData(v Querybuildertypesv5ScalarData) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeQuerybuildertypesv5ScalarData performs a merge with any union data inside the Querybuildertypesv5QueryData, using the provided Querybuildertypesv5ScalarData
func (t *Querybuildertypesv5QueryData) MergeQuerybuildertypesv5ScalarData(v Querybuildertypesv5ScalarData) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsQuerybuildertypesv5RawData returns the union data inside the Querybuildertypesv5QueryData as a Querybuildertypesv5RawData
func (t Querybuildertypesv5QueryData) AsQuerybuildertypesv5RawData() (Querybuildertypesv5RawData, error) {
	var body Querybuildertypesv5RawData
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromQuerybuildertypesv5RawData overwrites any union data inside the Querybuildertypesv5QueryData as the provided Querybuildertypesv5RawData
func (t *Querybuildertypesv5QueryData) FromQuerybuildertypesv5RawData(v Querybuildertypesv5RawData) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeQuerybuildertypesv5RawData performs a merge with any union data inside the Querybuildertypesv5QueryData, using the provided Querybuildertypesv5RawData
func (t *Querybuildertypesv5QueryData) MergeQuerybuildertypesv5RawData(v Querybuildertypesv5RawData) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Querybuildertypesv5QueryData) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.Results != nil {
		object["results"], err = json.Marshal(t.Results)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'results': %w", err)
		}
	}
	b, err = json.Marshal(object)
	return b, err
}

func (t *Querybuildertypesv5QueryData) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["results"]; found {
		err = json.Unmarshal(raw, &t.Results)
		if err != nil {
			return fmt.Errorf("error reading 'results': %w", err)
		}
	}

	return err
}
