// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apitypes

// Querybuildertypesv5ColumnDescriptor defines model for Querybuildertypesv5ColumnDescriptor.
type Querybuildertypesv5ColumnDescriptor struct {
	AggregationIndex *int64                         `json:"aggregationIndex,omitempty"`
	ColumnType       *Querybuildertypesv5ColumnType `json:"columnType,omitempty"`
	Description      *string                        `json:"description,omitempty"`
	FieldContext     *TelemetrytypesFieldContext    `json:"fieldContext,omitempty"`
	FieldDataType    *TelemetrytypesFieldDataType   `json:"fieldDataType,omitempty"`
	Meta             *struct {
		Unit *string `json:"unit,omitempty"`
	} `json:"meta,omitempty"`
	Name      string                `json:"name"`
	QueryName *string               `json:"queryName,omitempty"`
	Signal    *TelemetrytypesSignal `json:"signal,omitempty"`
	Unit      *string               `json:"unit,omitempty"`
}
