// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apitypes

// DashboardtypesPatchableDashboardV2 defines model for DashboardtypesPatchableDashboardV2.
type DashboardtypesPatchableDashboardV2 = []DashboardtypesJSONPatchOperation
