// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apitypes

// RulestatehistorytypesGettableRuleStateTimeline defines model for RulestatehistorytypesGettableRuleStateTimeline.
type RulestatehistorytypesGettableRuleStateTimeline struct {
	Items      *[]RulestatehistorytypesGettableRuleStateHistory `json:"items"`
	NextCursor *string                                          `json:"nextCursor,omitempty"`
	Total      int                                              `json:"total"`
}
