// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apitypes

import (
	"encoding/json"

	"github.com/oapi-codegen/runtime"
)

// Querybuildertypesv5VariableItem defines model for Querybuildertypesv5VariableItem.
type Querybuildertypesv5VariableItem struct {
	Type  *Querybuildertypesv5VariableType       `json:"type,omitempty"`
	Value *Querybuildertypesv5VariableItem_Value `json:"value,omitempty"`
}

// Querybuildertypesv5VariableItemValue0 defines model for .
type Querybuildertypesv5VariableItemValue0 = string

// Querybuildertypesv5VariableItemValue1 defines model for .
type Querybuildertypesv5VariableItemValue1 = float32

// Querybuildertypesv5VariableItemValue2 defines model for .
type Querybuildertypesv5VariableItemValue2 = bool

// Querybuildertypesv5VariableItemValue3 defines model for .
type Querybuildertypesv5VariableItemValue3 = []Querybuildertypesv5VariableItem_Value_3_Item

// Querybuildertypesv5VariableItemValue30 defines model for .
type Querybuildertypesv5VariableItemValue30 = string

// Querybuildertypesv5VariableItemValue31 defines model for .
type Querybuildertypesv5VariableItemValue31 = float32

// Querybuildertypesv5VariableItemValue32 defines model for .
type Querybuildertypesv5VariableItemValue32 = bool

// Querybuildertypesv5VariableItem_Value_3_Item defines model for Querybuildertypesv5VariableItem.Value.3.Item.
type Querybuildertypesv5VariableItem_Value_3_Item struct {
	union json.RawMessage
}

// Querybuildertypesv5VariableItem_Value defines model for Querybuildertypesv5VariableItem.Value.
type Querybuildertypesv5VariableItem_Value struct {
	union json.RawMessage
}

// AsQuerybuildertypesv5VariableItemValue30 returns the union data inside the Querybuildertypesv5VariableItem_Value_3_Item as a Querybuildertypesv5VariableItemValue30
func (t Querybuildertypesv5VariableItem_Value_3_Item) AsQuerybuildertypesv5VariableItemValue30() (Querybuildertypesv5VariableItemValue30, error) {
	var body Querybuildertypesv5VariableItemValue30
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromQuerybuildertypesv5VariableItemValue30 overwrites any union data inside the Querybuildertypesv5VariableItem_Value_3_Item as the provided Querybuildertypesv5VariableItemValue30
func (t *Querybuildertypesv5VariableItem_Value_3_Item) FromQuerybuildertypesv5VariableItemValue30(v Querybuildertypesv5VariableItemValue30) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeQuerybuildertypesv5VariableItemValue30 performs a merge with any union data inside the Querybuildertypesv5VariableItem_Value_3_Item, using the provided Querybuildertypesv5VariableItemValue30
func (t *Querybuildertypesv5VariableItem_Value_3_Item) MergeQuerybuildertypesv5VariableItemValue30(v Querybuildertypesv5VariableItemValue30) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsQuerybuildertypesv5VariableItemValue31 returns the union data inside the Querybuildertypesv5VariableItem_Value_3_Item as a Querybuildertypesv5VariableItemValue31
func (t Querybuildertypesv5VariableItem_Value_3_Item) AsQuerybuildertypesv5VariableItemValue31() (Querybuildertypesv5VariableItemValue31, error) {
	var body Querybuildertypesv5VariableItemValue31
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromQuerybuildertypesv5VariableItemValue31 overwrites any union data inside the Querybuildertypesv5VariableItem_Value_3_Item as the provided Querybuildertypesv5VariableItemValue31
func (t *Querybuildertypesv5VariableItem_Value_3_Item) FromQuerybuildertypesv5VariableItemValue31(v Querybuildertypesv5VariableItemValue31) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeQuerybuildertypesv5VariableItemValue31 performs a merge with any union data inside the Querybuildertypesv5VariableItem_Value_3_Item, using the provided Querybuildertypesv5VariableItemValue31
func (t *Querybuildertypesv5VariableItem_Value_3_Item) MergeQuerybuildertypesv5VariableItemValue31(v Querybuildertypesv5VariableItemValue31) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsQuerybuildertypesv5VariableItemValue32 returns the union data inside the Querybuildertypesv5VariableItem_Value_3_Item as a Querybuildertypesv5VariableItemValue32
func (t Querybuildertypesv5VariableItem_Value_3_Item) AsQuerybuildertypesv5VariableItemValue32() (Querybuildertypesv5VariableItemValue32, error) {
	var body Querybuildertypesv5VariableItemValue32
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromQuerybuildertypesv5VariableItemValue32 overwrites any union data inside the Querybuildertypesv5VariableItem_Value_3_Item as the provided Querybuildertypesv5VariableItemValue32
func (t *Querybuildertypesv5VariableItem_Value_3_Item) FromQuerybuildertypesv5VariableItemValue32(v Querybuildertypesv5VariableItemValue32) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeQuerybuildertypesv5VariableItemValue32 performs a merge with any union data inside the Querybuildertypesv5VariableItem_Value_3_Item, using the provided Querybuildertypesv5VariableItemValue32
func (t *Querybuildertypesv5VariableItem_Value_3_Item) MergeQuerybuildertypesv5VariableItemValue32(v Querybuildertypesv5VariableItemValue32) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Querybuildertypesv5VariableItem_Value_3_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Querybuildertypesv5VariableItem_Value_3_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsQuerybuildertypesv5VariableItemValue0 returns the union data inside the Querybuildertypesv5VariableItem_Value as a Querybuildertypesv5VariableItemValue0
func (t Querybuildertypesv5VariableItem_Value) AsQuerybuildertypesv5VariableItemValue0() (Querybuildertypesv5VariableItemValue0, error) {
	var body Querybuildertypesv5VariableItemValue0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromQuerybuildertypesv5VariableItemValue0 overwrites any union data inside the Querybuildertypesv5VariableItem_Value as the provided Querybuildertypesv5VariableItemValue0
func (t *Querybuildertypesv5VariableItem_Value) FromQuerybuildertypesv5VariableItemValue0(v Querybuildertypesv5VariableItemValue0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeQuerybuildertypesv5VariableItemValue0 performs a merge with any union data inside the Querybuildertypesv5VariableItem_Value, using the provided Querybuildertypesv5VariableItemValue0
func (t *Querybuildertypesv5VariableItem_Value) MergeQuerybuildertypesv5VariableItemValue0(v Querybuildertypesv5VariableItemValue0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsQuerybuildertypesv5VariableItemValue1 returns the union data inside the Querybuildertypesv5VariableItem_Value as a Querybuildertypesv5VariableItemValue1
func (t Querybuildertypesv5VariableItem_Value) AsQuerybuildertypesv5VariableItemValue1() (Querybuildertypesv5VariableItemValue1, error) {
	var body Querybuildertypesv5VariableItemValue1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromQuerybuildertypesv5VariableItemValue1 overwrites any union data inside the Querybuildertypesv5VariableItem_Value as the provided Querybuildertypesv5VariableItemValue1
func (t *Querybuildertypesv5VariableItem_Value) FromQuerybuildertypesv5VariableItemValue1(v Querybuildertypesv5VariableItemValue1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeQuerybuildertypesv5VariableItemValue1 performs a merge with any union data inside the Querybuildertypesv5VariableItem_Value, using the provided Querybuildertypesv5VariableItemValue1
func (t *Querybuildertypesv5VariableItem_Value) MergeQuerybuildertypesv5VariableItemValue1(v Querybuildertypesv5VariableItemValue1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsQuerybuildertypesv5VariableItemValue2 returns the union data inside the Querybuildertypesv5VariableItem_Value as a Querybuildertypesv5VariableItemValue2
func (t Querybuildertypesv5VariableItem_Value) AsQuerybuildertypesv5VariableItemValue2() (Querybuildertypesv5VariableItemValue2, error) {
	var body Querybuildertypesv5VariableItemValue2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromQuerybuildertypesv5VariableItemValue2 overwrites any union data inside the Querybuildertypesv5VariableItem_Value as the provided Querybuildertypesv5VariableItemValue2
func (t *Querybuildertypesv5VariableItem_Value) FromQuerybuildertypesv5VariableItemValue2(v Querybuildertypesv5VariableItemValue2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeQuerybuildertypesv5VariableItemValue2 performs a merge with any union data inside the Querybuildertypesv5VariableItem_Value, using the provided Querybuildertypesv5VariableItemValue2
func (t *Querybuildertypesv5VariableItem_Value) MergeQuerybuildertypesv5VariableItemValue2(v Querybuildertypesv5VariableItemValue2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsQuerybuildertypesv5VariableItemValue3 returns the union data inside the Querybuildertypesv5VariableItem_Value as a Querybuildertypesv5VariableItemValue3
func (t Querybuildertypesv5VariableItem_Value) AsQuerybuildertypesv5VariableItemValue3() (Querybuildertypesv5VariableItemValue3, error) {
	var body Querybuildertypesv5VariableItemValue3
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromQuerybuildertypesv5VariableItemValue3 overwrites any union data inside the Querybuildertypesv5VariableItem_Value as the provided Querybuildertypesv5VariableItemValue3
func (t *Querybuildertypesv5VariableItem_Value) FromQuerybuildertypesv5VariableItemValue3(v Querybuildertypesv5VariableItemValue3) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeQuerybuildertypesv5VariableItemValue3 performs a merge with any union data inside the Querybuildertypesv5VariableItem_Value, using the provided Querybuildertypesv5VariableItemValue3
func (t *Querybuildertypesv5VariableItem_Value) MergeQuerybuildertypesv5VariableItemValue3(v Querybuildertypesv5VariableItemValue3) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Querybuildertypesv5VariableItem_Value) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Querybuildertypesv5VariableItem_Value) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
