// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apitypes

// Defines values for DashboardtypesStackMode.
const (
	DashboardtypesStackModeNone    DashboardtypesStackMode = "none"
	DashboardtypesStackModeNormal  DashboardtypesStackMode = "normal"
	DashboardtypesStackModePercent DashboardtypesStackMode = "percent"
)

// Valid indicates whether the value is a known member of the DashboardtypesStackMode enum.
func (e DashboardtypesStackMode) Valid() bool {
	switch e {
	case DashboardtypesStackModeNone:
		return true
	case DashboardtypesStackModeNormal:
		return true
	case DashboardtypesStackModePercent:
		return true
	default:
		return false
	}
}

// DashboardtypesStackMode defines model for DashboardtypesStackMode.
type DashboardtypesStackMode string
