// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apitypes

// MetricsexplorertypesTreemapEntry defines model for MetricsexplorertypesTreemapEntry.
type MetricsexplorertypesTreemapEntry struct {
	MetricName string  `json:"metricName"`
	Percentage float64 `json:"percentage"`
	TotalValue int     `json:"totalValue"`
}
