// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apitypes

// MetricsexplorertypesMetricAttribute defines model for MetricsexplorertypesMetricAttribute.
type MetricsexplorertypesMetricAttribute struct {
	Key        string    `json:"key"`
	ValueCount int       `json:"valueCount"`
	Values     *[]string `json:"values"`
}
