// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apitypes

// Defines values for DashboardtypesPatchOp.
const (
	DashboardtypesPatchOpAdd     DashboardtypesPatchOp = "add"
	DashboardtypesPatchOpCopy    DashboardtypesPatchOp = "copy"
	DashboardtypesPatchOpMove    DashboardtypesPatchOp = "move"
	DashboardtypesPatchOpRemove  DashboardtypesPatchOp = "remove"
	DashboardtypesPatchOpReplace DashboardtypesPatchOp = "replace"
	DashboardtypesPatchOpTest    DashboardtypesPatchOp = "test"
)

// Valid indicates whether the value is a known member of the DashboardtypesPatchOp enum.
func (e DashboardtypesPatchOp) Valid() bool {
	switch e {
	case DashboardtypesPatchOpAdd:
		return true
	case DashboardtypesPatchOpCopy:
		return true
	case DashboardtypesPatchOpMove:
		return true
	case DashboardtypesPatchOpRemove:
		return true
	case DashboardtypesPatchOpReplace:
		return true
	case DashboardtypesPatchOpTest:
		return true
	default:
		return false
	}
}

// DashboardtypesPatchOp defines model for DashboardtypesPatchOp.
type DashboardtypesPatchOp string
