// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apitypes

// TypesAlertStatus defines model for TypesAlertStatus.
type TypesAlertStatus struct {
	InhibitedBy *[]string `json:"inhibitedBy,omitempty"`
	SilencedBy  *[]string `json:"silencedBy,omitempty"`
	State       *string   `json:"state,omitempty"`
}
