// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apitypes

import (
	"time"
)

// RuletypesListableRule defines model for RuletypesListableRule.
type RuletypesListableRule struct {
	Alert       string              `json:"alert"`
	AlertType   RuletypesAlertType  `json:"alertType"`
	CreatedAt   *time.Time          `json:"createdAt,omitempty"`
	CreatedBy   *string             `json:"createdBy,omitempty"`
	Description *string             `json:"description,omitempty"`
	Disabled    *bool               `json:"disabled,omitempty"`
	Id          string              `json:"id"`
	Labels      *map[string]string  `json:"labels,omitempty"`
	RuleType    RuletypesRuleType   `json:"ruleType"`
	State       RuletypesAlertState `json:"state"`
	UpdatedAt   *time.Time          `json:"updatedAt,omitempty"`
	UpdatedBy   *string             `json:"updatedBy,omitempty"`
}
