// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apitypes

import (
	"time"
)

// AlertmanagertypesListedNotificationChannel defines model for AlertmanagertypesListedNotificationChannel.
type AlertmanagertypesListedNotificationChannel struct {
	CreatedAt   time.Time                    `json:"createdAt"`
	DisplayName string                       `json:"displayName"`
	Id          string                       `json:"id"`
	Kind        AlertmanagertypesChannelKind `json:"kind"`
	Name        string                       `json:"name"`
	UpdatedAt   time.Time                    `json:"updatedAt"`
}
