// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apitypes

// DashboardtypesListedDashboardV2Spec defines model for DashboardtypesListedDashboardV2Spec.
type DashboardtypesListedDashboardV2Spec struct {
	Display *DashboardtypesDisplay `json:"display,omitempty"`
}
