// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apitypes

// Defines values for DashboardtypesAreaFillMode.
const (
	DashboardtypesAreaFillModeGradient DashboardtypesAreaFillMode = "gradient"
	DashboardtypesAreaFillModeSolid    DashboardtypesAreaFillMode = "solid"
)

// Valid indicates whether the value is a known member of the DashboardtypesAreaFillMode enum.
func (e DashboardtypesAreaFillMode) Valid() bool {
	switch e {
	case DashboardtypesAreaFillModeGradient:
		return true
	case DashboardtypesAreaFillModeSolid:
		return true
	default:
		return false
	}
}

// DashboardtypesAreaFillMode defines model for DashboardtypesAreaFillMode.
type DashboardtypesAreaFillMode string
