// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apitypes

// Defines values for AlertmanagertypesChannelKind.
const (
	AlertmanagertypesChannelKindEmail      AlertmanagertypesChannelKind = "email"
	AlertmanagertypesChannelKindGooglechat AlertmanagertypesChannelKind = "googlechat"
	AlertmanagertypesChannelKindIncidentio AlertmanagertypesChannelKind = "incidentio"
	AlertmanagertypesChannelKindJira       AlertmanagertypesChannelKind = "jira"
	AlertmanagertypesChannelKindJsmops     AlertmanagertypesChannelKind = "jsmops"
	AlertmanagertypesChannelKindMsteams    AlertmanagertypesChannelKind = "msteams"
	AlertmanagertypesChannelKindOpsgenie   AlertmanagertypesChannelKind = "opsgenie"
	AlertmanagertypesChannelKindPagerduty  AlertmanagertypesChannelKind = "pagerduty"
	AlertmanagertypesChannelKindSlack      AlertmanagertypesChannelKind = "slack"
	AlertmanagertypesChannelKindWebhook    AlertmanagertypesChannelKind = "webhook"
)

// Valid indicates whether the value is a known member of the AlertmanagertypesChannelKind enum.
func (e AlertmanagertypesChannelKind) Valid() bool {
	switch e {
	case AlertmanagertypesChannelKindEmail:
		return true
	case AlertmanagertypesChannelKindGooglechat:
		return true
	case AlertmanagertypesChannelKindIncidentio:
		return true
	case AlertmanagertypesChannelKindJira:
		return true
	case AlertmanagertypesChannelKindJsmops:
		return true
	case AlertmanagertypesChannelKindMsteams:
		return true
	case AlertmanagertypesChannelKindOpsgenie:
		return true
	case AlertmanagertypesChannelKindPagerduty:
		return true
	case AlertmanagertypesChannelKindSlack:
		return true
	case AlertmanagertypesChannelKindWebhook:
		return true
	default:
		return false
	}
}

// AlertmanagertypesChannelKind defines model for AlertmanagertypesChannelKind.
type AlertmanagertypesChannelKind string
