// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apitypes

// DashboardtypesJSONPatchOperation defines model for DashboardtypesJSONPatchOperation.
type DashboardtypesJSONPatchOperation struct {
	// From Source JSON Pointer for move/copy ops; ignored for other ops.
	From *string               `json:"from,omitempty"`
	Op   DashboardtypesPatchOp `json:"op"`

	// Path JSON Pointer (RFC 6901) into the dashboard's postable shape — e.g. /spec/display/name, /spec/panels/<id>, /spec/panels/<id>/spec/queries/0, /tags/-.
	Path string `json:"path"`

	// Value Value to add/replace/test against. The expected type depends on the path. Common shapes (see referenced schemas for the exact field set): /spec/panels/<id> takes a DashboardtypesPanel; /spec/panels/<id>/spec/queries/N (or /-) takes a DashboardtypesQuery; /spec/variables/N takes a DashboardtypesVariable; /spec/layouts/N takes a DashboardtypesLayout; /tags/N (or /-) takes a TagtypesPostableTag; /spec/display/name and other leaf string fields take a string. Required for add/replace/test; ignored for remove/move/copy.
	Value interface{} `json:"value,omitempty"`
}
