// Code generated by cmd/gen-tools. DO NOT EDIT.
// Source: docs/api/openapi.yml

package gentools

import (
	_ "embed"
	"encoding/json"
)

var _ = json.RawMessage(nil)

// CreateRoutePolicyInput is the MCP tool input for POST /api/v1/route_policies (CreateRoutePolicy).
// Tool name: signoz_create_route_policy.
type CreateRoutePolicyInput struct {
	Body json.RawMessage `json:"body,omitempty" jsonschema:"AlertmanagertypesPostableRoutePolicy"`
}

//go:embed tools/zz_generated_signoz_create_route_policy.json
var rawSchemaCreateRoutePolicy []byte

// SchemaCreateRoutePolicy is the self-contained JSON Schema for signoz_create_route_policy,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_create_route_policy.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaCreateRoutePolicy = ComposeSchema(rawSchemaCreateRoutePolicy)

// DeleteRoutePolicyByIDInput is the MCP tool input for DELETE /api/v1/route_policies/{id} (DeleteRoutePolicyByID).
// Tool name: signoz_delete_route_policy_by_id.
type DeleteRoutePolicyByIDInput struct {
	Id string `json:"id" jsonschema:"path parameter id"`
}

//go:embed tools/zz_generated_signoz_delete_route_policy_by_id.json
var rawSchemaDeleteRoutePolicyByID []byte

// SchemaDeleteRoutePolicyByID is the self-contained JSON Schema for signoz_delete_route_policy_by_id,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_delete_route_policy_by_id.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaDeleteRoutePolicyByID = ComposeSchema(rawSchemaDeleteRoutePolicyByID)

// GetAllRoutePoliciesInput is the MCP tool input for GET /api/v1/route_policies (GetAllRoutePolicies).
// Tool name: signoz_get_all_route_policies.
type GetAllRoutePoliciesInput struct {
}

//go:embed tools/zz_generated_signoz_get_all_route_policies.json
var rawSchemaGetAllRoutePolicies []byte

// SchemaGetAllRoutePolicies is the self-contained JSON Schema for signoz_get_all_route_policies,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_get_all_route_policies.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaGetAllRoutePolicies = ComposeSchema(rawSchemaGetAllRoutePolicies)

// GetRoutePolicyByIDInput is the MCP tool input for GET /api/v1/route_policies/{id} (GetRoutePolicyByID).
// Tool name: signoz_get_route_policy_by_id.
type GetRoutePolicyByIDInput struct {
	Id string `json:"id" jsonschema:"path parameter id"`
}

//go:embed tools/zz_generated_signoz_get_route_policy_by_id.json
var rawSchemaGetRoutePolicyByID []byte

// SchemaGetRoutePolicyByID is the self-contained JSON Schema for signoz_get_route_policy_by_id,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_get_route_policy_by_id.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaGetRoutePolicyByID = ComposeSchema(rawSchemaGetRoutePolicyByID)

// UpdateRoutePolicyInput is the MCP tool input for PUT /api/v1/route_policies/{id} (UpdateRoutePolicy).
// Tool name: signoz_update_route_policy.
type UpdateRoutePolicyInput struct {
	Id   string          `json:"id" jsonschema:"path parameter id"`
	Body json.RawMessage `json:"body,omitempty" jsonschema:"AlertmanagertypesPostableRoutePolicy"`
}

//go:embed tools/zz_generated_signoz_update_route_policy.json
var rawSchemaUpdateRoutePolicy []byte

// SchemaUpdateRoutePolicy is the self-contained JSON Schema for signoz_update_route_policy,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_update_route_policy.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaUpdateRoutePolicy = ComposeSchema(rawSchemaUpdateRoutePolicy)
