// Code generated by cmd/gen-tools. DO NOT EDIT.
// Source: docs/api/openapi.yml

package gentools

import (
	_ "embed"
	"encoding/json"
)

var _ = json.RawMessage(nil)

// QueryRangeV5Input is the MCP tool input for POST /api/v5/query_range (QueryRangeV5).
// Tool name: signoz_query_range_v5.
type QueryRangeV5Input struct {
	Body json.RawMessage `json:"body,omitempty" jsonschema:"Querybuildertypesv5QueryRangeRequest"`
}

//go:embed tools/zz_generated_signoz_query_range_v5.json
var rawSchemaQueryRangeV5 []byte

// SchemaQueryRangeV5 is the self-contained JSON Schema for signoz_query_range_v5,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_query_range_v5.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaQueryRangeV5 = ComposeSchema(rawSchemaQueryRangeV5)

// ReplaceVariablesInput is the MCP tool input for POST /api/v5/substitute_vars (ReplaceVariables).
// Tool name: signoz_replace_variables.
type ReplaceVariablesInput struct {
	Body json.RawMessage `json:"body,omitempty" jsonschema:"Querybuildertypesv5QueryRangeRequest"`
}

//go:embed tools/zz_generated_signoz_replace_variables.json
var rawSchemaReplaceVariables []byte

// SchemaReplaceVariables is the self-contained JSON Schema for signoz_replace_variables,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_replace_variables.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaReplaceVariables = ComposeSchema(rawSchemaReplaceVariables)
