// Code generated by cmd/gen-tools. DO NOT EDIT.
// Source: docs/api/openapi.yml

package gentools

import (
	_ "embed"
	"encoding/json"
)

var _ = json.RawMessage(nil)

// GetFeaturesInput is the MCP tool input for GET /api/v2/features (GetFeatures).
// Tool name: signoz_get_features.
type GetFeaturesInput struct {
}

//go:embed tools/zz_generated_signoz_get_features.input.json
var rawSchemaGetFeatures []byte

// SchemaGetFeatures is the self-contained JSON Schema for signoz_get_features,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_get_features.input.json. Hand it to
// mcp.WithRawInputSchema directly.
var SchemaGetFeatures = ComposeSchema(rawSchemaGetFeatures)

//go:embed tools/zz_generated_signoz_get_features.output.json
var rawOutputSchemaGetFeatures []byte

// OutputSchemaGetFeatures is the self-contained JSON Schema describing
// the response body of signoz_get_features (GET /api/v2/features's success
// status). Composed at init from tools/zz_generated_signoz_get_features.output.json
// against the same components/ catalogue.
var OutputSchemaGetFeatures = ComposeSchema(rawOutputSchemaGetFeatures)
