// Code generated by cmd/gen-tools. DO NOT EDIT.
// Source: docs/api/openapi.yml

package gentools

import (
	_ "embed"
	"encoding/json"
)

var _ = json.RawMessage(nil)

// CreateChannelInput is the MCP tool input for POST /api/v1/channels (CreateChannel).
// Tool name: signoz_create_channel.
type CreateChannelInput struct {
	Body json.RawMessage `json:"body,omitempty" jsonschema:"ConfigReceiver"`
}

//go:embed tools/zz_generated_signoz_create_channel.json
var rawSchemaCreateChannel []byte

// SchemaCreateChannel is the self-contained JSON Schema for signoz_create_channel,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_create_channel.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaCreateChannel = ComposeSchema(rawSchemaCreateChannel)

// DeleteChannelByIDInput is the MCP tool input for DELETE /api/v1/channels/{id} (DeleteChannelByID).
// Tool name: signoz_delete_channel_by_id.
type DeleteChannelByIDInput struct {
	Id string `json:"id" jsonschema:"path parameter id"`
}

//go:embed tools/zz_generated_signoz_delete_channel_by_id.json
var rawSchemaDeleteChannelByID []byte

// SchemaDeleteChannelByID is the self-contained JSON Schema for signoz_delete_channel_by_id,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_delete_channel_by_id.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaDeleteChannelByID = ComposeSchema(rawSchemaDeleteChannelByID)

// GetChannelByIDInput is the MCP tool input for GET /api/v1/channels/{id} (GetChannelByID).
// Tool name: signoz_get_channel_by_id.
type GetChannelByIDInput struct {
	Id string `json:"id" jsonschema:"path parameter id"`
}

//go:embed tools/zz_generated_signoz_get_channel_by_id.json
var rawSchemaGetChannelByID []byte

// SchemaGetChannelByID is the self-contained JSON Schema for signoz_get_channel_by_id,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_get_channel_by_id.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaGetChannelByID = ComposeSchema(rawSchemaGetChannelByID)

// ListChannelsInput is the MCP tool input for GET /api/v1/channels (ListChannels).
// Tool name: signoz_list_channels.
type ListChannelsInput struct {
}

//go:embed tools/zz_generated_signoz_list_channels.json
var rawSchemaListChannels []byte

// SchemaListChannels is the self-contained JSON Schema for signoz_list_channels,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_list_channels.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaListChannels = ComposeSchema(rawSchemaListChannels)

// TestChannelInput is the MCP tool input for POST /api/v1/channels/test (TestChannel).
// Tool name: signoz_test_channel.
type TestChannelInput struct {
	Body json.RawMessage `json:"body,omitempty" jsonschema:"ConfigReceiver"`
}

//go:embed tools/zz_generated_signoz_test_channel.json
var rawSchemaTestChannel []byte

// SchemaTestChannel is the self-contained JSON Schema for signoz_test_channel,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_test_channel.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaTestChannel = ComposeSchema(rawSchemaTestChannel)

// UpdateChannelByIDInput is the MCP tool input for PUT /api/v1/channels/{id} (UpdateChannelByID).
// Tool name: signoz_update_channel_by_id.
type UpdateChannelByIDInput struct {
	Id   string          `json:"id" jsonschema:"path parameter id"`
	Body json.RawMessage `json:"body,omitempty" jsonschema:"ConfigReceiver"`
}

//go:embed tools/zz_generated_signoz_update_channel_by_id.json
var rawSchemaUpdateChannelByID []byte

// SchemaUpdateChannelByID is the self-contained JSON Schema for signoz_update_channel_by_id,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_update_channel_by_id.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaUpdateChannelByID = ComposeSchema(rawSchemaUpdateChannelByID)
