// Code generated by cmd/gen-tools. DO NOT EDIT.
// Source: docs/api/openapi.yml

package gentools

import (
	_ "embed"
	"encoding/json"
)

var _ = json.RawMessage(nil)

// ListHostsInput is the MCP tool input for POST /api/v2/infra_monitoring/hosts (ListHosts).
// Tool name: signoz_list_hosts.
type ListHostsInput struct {
	Body json.RawMessage `json:"body,omitempty" jsonschema:"InframonitoringtypesPostableHosts"`
}

//go:embed tools/zz_generated_signoz_list_hosts.json
var rawSchemaListHosts []byte

// SchemaListHosts is the self-contained JSON Schema for signoz_list_hosts,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_list_hosts.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaListHosts = ComposeSchema(rawSchemaListHosts)
