// Code generated by cmd/gen-tools. DO NOT EDIT.
// Source: docs/api/openapi.yml

package gentools

import (
	_ "embed"
	"encoding/json"
)

var _ = json.RawMessage(nil)

// AgentCheckInInput is the MCP tool input for POST /api/v1/cloud_integrations/{cloud_provider}/accounts/check_in (AgentCheckIn).
// Tool name: signoz_agent_check_in.
type AgentCheckInInput struct {
	CloudProvider string          `json:"cloud_provider" jsonschema:"path parameter cloud_provider"`
	Body          json.RawMessage `json:"body,omitempty" jsonschema:"CloudintegrationtypesPostableAgentCheckIn"`
}

//go:embed tools/zz_generated_signoz_agent_check_in.json
var rawSchemaAgentCheckIn []byte

// SchemaAgentCheckIn is the self-contained JSON Schema for signoz_agent_check_in,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_agent_check_in.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaAgentCheckIn = ComposeSchema(rawSchemaAgentCheckIn)

// CreateAccountInput is the MCP tool input for POST /api/v1/cloud_integrations/{cloud_provider}/accounts (CreateAccount).
// Tool name: signoz_create_account.
type CreateAccountInput struct {
	CloudProvider string          `json:"cloud_provider" jsonschema:"path parameter cloud_provider"`
	Body          json.RawMessage `json:"body,omitempty" jsonschema:"CloudintegrationtypesPostableAccount"`
}

//go:embed tools/zz_generated_signoz_create_account.json
var rawSchemaCreateAccount []byte

// SchemaCreateAccount is the self-contained JSON Schema for signoz_create_account,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_create_account.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaCreateAccount = ComposeSchema(rawSchemaCreateAccount)

// DisconnectAccountInput is the MCP tool input for DELETE /api/v1/cloud_integrations/{cloud_provider}/accounts/{id} (DisconnectAccount).
// Tool name: signoz_disconnect_account.
type DisconnectAccountInput struct {
	CloudProvider string `json:"cloud_provider" jsonschema:"path parameter cloud_provider"`
	Id            string `json:"id" jsonschema:"path parameter id"`
}

//go:embed tools/zz_generated_signoz_disconnect_account.json
var rawSchemaDisconnectAccount []byte

// SchemaDisconnectAccount is the self-contained JSON Schema for signoz_disconnect_account,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_disconnect_account.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaDisconnectAccount = ComposeSchema(rawSchemaDisconnectAccount)

// GetAccountInput is the MCP tool input for GET /api/v1/cloud_integrations/{cloud_provider}/accounts/{id} (GetAccount).
// Tool name: signoz_get_account.
type GetAccountInput struct {
	CloudProvider string `json:"cloud_provider" jsonschema:"path parameter cloud_provider"`
	Id            string `json:"id" jsonschema:"path parameter id"`
}

//go:embed tools/zz_generated_signoz_get_account.json
var rawSchemaGetAccount []byte

// SchemaGetAccount is the self-contained JSON Schema for signoz_get_account,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_get_account.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaGetAccount = ComposeSchema(rawSchemaGetAccount)

// GetConnectionCredentialsInput is the MCP tool input for GET /api/v1/cloud_integrations/{cloud_provider}/credentials (GetConnectionCredentials).
// Tool name: signoz_get_connection_credentials.
type GetConnectionCredentialsInput struct {
	CloudProvider string `json:"cloud_provider" jsonschema:"path parameter cloud_provider"`
}

//go:embed tools/zz_generated_signoz_get_connection_credentials.json
var rawSchemaGetConnectionCredentials []byte

// SchemaGetConnectionCredentials is the self-contained JSON Schema for signoz_get_connection_credentials,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_get_connection_credentials.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaGetConnectionCredentials = ComposeSchema(rawSchemaGetConnectionCredentials)

// GetServiceInput is the MCP tool input for GET /api/v1/cloud_integrations/{cloud_provider}/services/{service_id} (GetService).
// Tool name: signoz_get_service.
type GetServiceInput struct {
	CloudProvider      string `json:"cloud_provider" jsonschema:"path parameter cloud_provider"`
	ServiceId          string `json:"service_id" jsonschema:"path parameter service_id"`
	CloudIntegrationId string `json:"cloud_integration_id,omitempty" jsonschema:"query parameter cloud_integration_id"`
}

//go:embed tools/zz_generated_signoz_get_service.json
var rawSchemaGetService []byte

// SchemaGetService is the self-contained JSON Schema for signoz_get_service,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_get_service.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaGetService = ComposeSchema(rawSchemaGetService)

// ListAccountsInput is the MCP tool input for GET /api/v1/cloud_integrations/{cloud_provider}/accounts (ListAccounts).
// Tool name: signoz_list_accounts.
type ListAccountsInput struct {
	CloudProvider string `json:"cloud_provider" jsonschema:"path parameter cloud_provider"`
}

//go:embed tools/zz_generated_signoz_list_accounts.json
var rawSchemaListAccounts []byte

// SchemaListAccounts is the self-contained JSON Schema for signoz_list_accounts,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_list_accounts.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaListAccounts = ComposeSchema(rawSchemaListAccounts)

// ListServicesMetadataInput is the MCP tool input for GET /api/v1/cloud_integrations/{cloud_provider}/services (ListServicesMetadata).
// Tool name: signoz_list_services_metadata.
type ListServicesMetadataInput struct {
	CloudProvider      string `json:"cloud_provider" jsonschema:"path parameter cloud_provider"`
	CloudIntegrationId string `json:"cloud_integration_id,omitempty" jsonschema:"query parameter cloud_integration_id"`
}

//go:embed tools/zz_generated_signoz_list_services_metadata.json
var rawSchemaListServicesMetadata []byte

// SchemaListServicesMetadata is the self-contained JSON Schema for signoz_list_services_metadata,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_list_services_metadata.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaListServicesMetadata = ComposeSchema(rawSchemaListServicesMetadata)

// UpdateAccountInput is the MCP tool input for PUT /api/v1/cloud_integrations/{cloud_provider}/accounts/{id} (UpdateAccount).
// Tool name: signoz_update_account.
type UpdateAccountInput struct {
	CloudProvider string          `json:"cloud_provider" jsonschema:"path parameter cloud_provider"`
	Id            string          `json:"id" jsonschema:"path parameter id"`
	Body          json.RawMessage `json:"body,omitempty" jsonschema:"CloudintegrationtypesUpdatableAccount"`
}

//go:embed tools/zz_generated_signoz_update_account.json
var rawSchemaUpdateAccount []byte

// SchemaUpdateAccount is the self-contained JSON Schema for signoz_update_account,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_update_account.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaUpdateAccount = ComposeSchema(rawSchemaUpdateAccount)

// UpdateServiceInput is the MCP tool input for PUT /api/v1/cloud_integrations/{cloud_provider}/accounts/{id}/services/{service_id} (UpdateService).
// Tool name: signoz_update_service.
type UpdateServiceInput struct {
	CloudProvider string          `json:"cloud_provider" jsonschema:"path parameter cloud_provider"`
	Id            string          `json:"id" jsonschema:"path parameter id"`
	ServiceId     string          `json:"service_id" jsonschema:"path parameter service_id"`
	Body          json.RawMessage `json:"body,omitempty" jsonschema:"CloudintegrationtypesUpdatableService"`
}

//go:embed tools/zz_generated_signoz_update_service.json
var rawSchemaUpdateService []byte

// SchemaUpdateService is the self-contained JSON Schema for signoz_update_service,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_update_service.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaUpdateService = ComposeSchema(rawSchemaUpdateService)
