// Code generated by cmd/gen-tools. DO NOT EDIT.
// Source: docs/api/openapi.yml

package gentools

import (
	_ "embed"
	"encoding/json"
)

var _ = json.RawMessage(nil)

// CreateIngestionKeyInput is the MCP tool input for POST /api/v2/gateway/ingestion_keys (CreateIngestionKey).
// Tool name: signoz_create_ingestion_key.
type CreateIngestionKeyInput struct {
	Body json.RawMessage `json:"body,omitempty" jsonschema:"GatewaytypesPostableIngestionKey"`
}

//go:embed tools/zz_generated_signoz_create_ingestion_key.json
var rawSchemaCreateIngestionKey []byte

// SchemaCreateIngestionKey is the self-contained JSON Schema for signoz_create_ingestion_key,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_create_ingestion_key.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaCreateIngestionKey = ComposeSchema(rawSchemaCreateIngestionKey)

// CreateIngestionKeyLimitInput is the MCP tool input for POST /api/v2/gateway/ingestion_keys/{keyId}/limits (CreateIngestionKeyLimit).
// Tool name: signoz_create_ingestion_key_limit.
type CreateIngestionKeyLimitInput struct {
	KeyId string          `json:"keyId" jsonschema:"path parameter keyId"`
	Body  json.RawMessage `json:"body,omitempty" jsonschema:"GatewaytypesPostableIngestionKeyLimit"`
}

//go:embed tools/zz_generated_signoz_create_ingestion_key_limit.json
var rawSchemaCreateIngestionKeyLimit []byte

// SchemaCreateIngestionKeyLimit is the self-contained JSON Schema for signoz_create_ingestion_key_limit,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_create_ingestion_key_limit.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaCreateIngestionKeyLimit = ComposeSchema(rawSchemaCreateIngestionKeyLimit)

// DeleteIngestionKeyInput is the MCP tool input for DELETE /api/v2/gateway/ingestion_keys/{keyId} (DeleteIngestionKey).
// Tool name: signoz_delete_ingestion_key.
type DeleteIngestionKeyInput struct {
	KeyId string `json:"keyId" jsonschema:"path parameter keyId"`
}

//go:embed tools/zz_generated_signoz_delete_ingestion_key.json
var rawSchemaDeleteIngestionKey []byte

// SchemaDeleteIngestionKey is the self-contained JSON Schema for signoz_delete_ingestion_key,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_delete_ingestion_key.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaDeleteIngestionKey = ComposeSchema(rawSchemaDeleteIngestionKey)

// DeleteIngestionKeyLimitInput is the MCP tool input for DELETE /api/v2/gateway/ingestion_keys/limits/{limitId} (DeleteIngestionKeyLimit).
// Tool name: signoz_delete_ingestion_key_limit.
type DeleteIngestionKeyLimitInput struct {
	LimitId string `json:"limitId" jsonschema:"path parameter limitId"`
}

//go:embed tools/zz_generated_signoz_delete_ingestion_key_limit.json
var rawSchemaDeleteIngestionKeyLimit []byte

// SchemaDeleteIngestionKeyLimit is the self-contained JSON Schema for signoz_delete_ingestion_key_limit,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_delete_ingestion_key_limit.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaDeleteIngestionKeyLimit = ComposeSchema(rawSchemaDeleteIngestionKeyLimit)

// GetIngestionKeysInput is the MCP tool input for GET /api/v2/gateway/ingestion_keys (GetIngestionKeys).
// Tool name: signoz_get_ingestion_keys.
type GetIngestionKeysInput struct {
	Page    int64 `json:"page,omitempty" jsonschema:"query parameter page"`
	PerPage int64 `json:"per_page,omitempty" jsonschema:"query parameter per_page"`
}

//go:embed tools/zz_generated_signoz_get_ingestion_keys.json
var rawSchemaGetIngestionKeys []byte

// SchemaGetIngestionKeys is the self-contained JSON Schema for signoz_get_ingestion_keys,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_get_ingestion_keys.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaGetIngestionKeys = ComposeSchema(rawSchemaGetIngestionKeys)

// SearchIngestionKeysInput is the MCP tool input for GET /api/v2/gateway/ingestion_keys/search (SearchIngestionKeys).
// Tool name: signoz_search_ingestion_keys.
type SearchIngestionKeysInput struct {
	Name    string `json:"name" jsonschema:"query parameter name"`
	Page    int64  `json:"page,omitempty" jsonschema:"query parameter page"`
	PerPage int64  `json:"per_page,omitempty" jsonschema:"query parameter per_page"`
}

//go:embed tools/zz_generated_signoz_search_ingestion_keys.json
var rawSchemaSearchIngestionKeys []byte

// SchemaSearchIngestionKeys is the self-contained JSON Schema for signoz_search_ingestion_keys,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_search_ingestion_keys.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaSearchIngestionKeys = ComposeSchema(rawSchemaSearchIngestionKeys)

// UpdateIngestionKeyInput is the MCP tool input for PATCH /api/v2/gateway/ingestion_keys/{keyId} (UpdateIngestionKey).
// Tool name: signoz_update_ingestion_key.
type UpdateIngestionKeyInput struct {
	KeyId string          `json:"keyId" jsonschema:"path parameter keyId"`
	Body  json.RawMessage `json:"body,omitempty" jsonschema:"GatewaytypesPostableIngestionKey"`
}

//go:embed tools/zz_generated_signoz_update_ingestion_key.json
var rawSchemaUpdateIngestionKey []byte

// SchemaUpdateIngestionKey is the self-contained JSON Schema for signoz_update_ingestion_key,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_update_ingestion_key.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaUpdateIngestionKey = ComposeSchema(rawSchemaUpdateIngestionKey)

// UpdateIngestionKeyLimitInput is the MCP tool input for PATCH /api/v2/gateway/ingestion_keys/limits/{limitId} (UpdateIngestionKeyLimit).
// Tool name: signoz_update_ingestion_key_limit.
type UpdateIngestionKeyLimitInput struct {
	LimitId string          `json:"limitId" jsonschema:"path parameter limitId"`
	Body    json.RawMessage `json:"body,omitempty" jsonschema:"GatewaytypesUpdatableIngestionKeyLimit"`
}

//go:embed tools/zz_generated_signoz_update_ingestion_key_limit.json
var rawSchemaUpdateIngestionKeyLimit []byte

// SchemaUpdateIngestionKeyLimit is the self-contained JSON Schema for signoz_update_ingestion_key_limit,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_update_ingestion_key_limit.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaUpdateIngestionKeyLimit = ComposeSchema(rawSchemaUpdateIngestionKeyLimit)
