// Code generated by cmd/gen-tools. DO NOT EDIT.
// Source: docs/api/openapi.yml

package gentools

import (
	_ "embed"
	"encoding/json"
)

var _ = json.RawMessage(nil)

// GetWaterfallInput is the MCP tool input for POST /api/v3/traces/{traceID}/waterfall (GetWaterfall).
// Tool name: signoz_get_waterfall.
type GetWaterfallInput struct {
	TraceID string          `json:"traceID" jsonschema:"path parameter traceID"`
	Body    json.RawMessage `json:"body,omitempty" jsonschema:"TracedetailtypesPostableWaterfall"`
}

//go:embed tools/zz_generated_signoz_get_waterfall.json
var rawSchemaGetWaterfall []byte

// SchemaGetWaterfall is the self-contained JSON Schema for signoz_get_waterfall,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_get_waterfall.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaGetWaterfall = ComposeSchema(rawSchemaGetWaterfall)
