// Code generated by cmd/gen-tools. DO NOT EDIT.
// Source: docs/api/openapi.yml

package gentools

import (
	_ "embed"
	"encoding/json"
)

var _ = json.RawMessage(nil)

// CreateSessionByEmailPasswordInput is the MCP tool input for POST /api/v2/sessions/email_password (CreateSessionByEmailPassword).
// Tool name: signoz_create_session_by_email_password.
type CreateSessionByEmailPasswordInput struct {
	Body json.RawMessage `json:"body,omitempty" jsonschema:"AuthtypesPostableEmailPasswordSession"`
}

//go:embed tools/zz_generated_signoz_create_session_by_email_password.input.json
var rawSchemaCreateSessionByEmailPassword []byte

// SchemaCreateSessionByEmailPassword is the self-contained JSON Schema for signoz_create_session_by_email_password,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_create_session_by_email_password.input.json. Hand it to
// mcp.WithRawInputSchema directly.
var SchemaCreateSessionByEmailPassword = ComposeSchema(rawSchemaCreateSessionByEmailPassword)

//go:embed tools/zz_generated_signoz_create_session_by_email_password.output.json
var rawOutputSchemaCreateSessionByEmailPassword []byte

// OutputSchemaCreateSessionByEmailPassword is the self-contained JSON Schema describing
// the response body of signoz_create_session_by_email_password (POST /api/v2/sessions/email_password's success
// status). Composed at init from tools/zz_generated_signoz_create_session_by_email_password.output.json
// against the same components/ catalogue.
var OutputSchemaCreateSessionByEmailPassword = ComposeSchema(rawOutputSchemaCreateSessionByEmailPassword)

// CreateSessionByGoogleCallbackInput is the MCP tool input for GET /api/v1/complete/google (CreateSessionByGoogleCallback).
// Tool name: signoz_create_session_by_google_callback.
type CreateSessionByGoogleCallbackInput struct {
}

//go:embed tools/zz_generated_signoz_create_session_by_google_callback.input.json
var rawSchemaCreateSessionByGoogleCallback []byte

// SchemaCreateSessionByGoogleCallback is the self-contained JSON Schema for signoz_create_session_by_google_callback,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_create_session_by_google_callback.input.json. Hand it to
// mcp.WithRawInputSchema directly.
var SchemaCreateSessionByGoogleCallback = ComposeSchema(rawSchemaCreateSessionByGoogleCallback)

// CreateSessionByOIDCCallbackInput is the MCP tool input for GET /api/v1/complete/oidc (CreateSessionByOIDCCallback).
// Tool name: signoz_create_session_by_oidc_callback.
type CreateSessionByOIDCCallbackInput struct {
}

//go:embed tools/zz_generated_signoz_create_session_by_oidc_callback.input.json
var rawSchemaCreateSessionByOIDCCallback []byte

// SchemaCreateSessionByOIDCCallback is the self-contained JSON Schema for signoz_create_session_by_oidc_callback,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_create_session_by_oidc_callback.input.json. Hand it to
// mcp.WithRawInputSchema directly.
var SchemaCreateSessionByOIDCCallback = ComposeSchema(rawSchemaCreateSessionByOIDCCallback)

// DeleteSessionInput is the MCP tool input for DELETE /api/v2/sessions (DeleteSession).
// Tool name: signoz_delete_session.
type DeleteSessionInput struct {
}

//go:embed tools/zz_generated_signoz_delete_session.input.json
var rawSchemaDeleteSession []byte

// SchemaDeleteSession is the self-contained JSON Schema for signoz_delete_session,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_delete_session.input.json. Hand it to
// mcp.WithRawInputSchema directly.
var SchemaDeleteSession = ComposeSchema(rawSchemaDeleteSession)

// GetSessionContextInput is the MCP tool input for GET /api/v2/sessions/context (GetSessionContext).
// Tool name: signoz_get_session_context.
type GetSessionContextInput struct {
}

//go:embed tools/zz_generated_signoz_get_session_context.input.json
var rawSchemaGetSessionContext []byte

// SchemaGetSessionContext is the self-contained JSON Schema for signoz_get_session_context,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_get_session_context.input.json. Hand it to
// mcp.WithRawInputSchema directly.
var SchemaGetSessionContext = ComposeSchema(rawSchemaGetSessionContext)

//go:embed tools/zz_generated_signoz_get_session_context.output.json
var rawOutputSchemaGetSessionContext []byte

// OutputSchemaGetSessionContext is the self-contained JSON Schema describing
// the response body of signoz_get_session_context (GET /api/v2/sessions/context's success
// status). Composed at init from tools/zz_generated_signoz_get_session_context.output.json
// against the same components/ catalogue.
var OutputSchemaGetSessionContext = ComposeSchema(rawOutputSchemaGetSessionContext)

// RotateSessionInput is the MCP tool input for POST /api/v2/sessions/rotate (RotateSession).
// Tool name: signoz_rotate_session.
type RotateSessionInput struct {
	Body json.RawMessage `json:"body,omitempty" jsonschema:"AuthtypesPostableRotateToken"`
}

//go:embed tools/zz_generated_signoz_rotate_session.input.json
var rawSchemaRotateSession []byte

// SchemaRotateSession is the self-contained JSON Schema for signoz_rotate_session,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_rotate_session.input.json. Hand it to
// mcp.WithRawInputSchema directly.
var SchemaRotateSession = ComposeSchema(rawSchemaRotateSession)

//go:embed tools/zz_generated_signoz_rotate_session.output.json
var rawOutputSchemaRotateSession []byte

// OutputSchemaRotateSession is the self-contained JSON Schema describing
// the response body of signoz_rotate_session (POST /api/v2/sessions/rotate's success
// status). Composed at init from tools/zz_generated_signoz_rotate_session.output.json
// against the same components/ catalogue.
var OutputSchemaRotateSession = ComposeSchema(rawOutputSchemaRotateSession)
