// Code generated by cmd/gen-tools. DO NOT EDIT.
// Source: docs/api/openapi.yml

package gentools

import (
	_ "embed"
	"encoding/json"
)

var _ = json.RawMessage(nil)

// GetGlobalConfigInput is the MCP tool input for GET /api/v1/global/config (GetGlobalConfig).
// Tool name: signoz_get_global_config.
type GetGlobalConfigInput struct {
}

//go:embed tools/zz_generated_signoz_get_global_config.json
var rawSchemaGetGlobalConfig []byte

// SchemaGetGlobalConfig is the self-contained JSON Schema for signoz_get_global_config,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_get_global_config.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaGetGlobalConfig = ComposeSchema(rawSchemaGetGlobalConfig)
