// Code generated by cmd/gen-tools. DO NOT EDIT.
// Source: docs/api/openapi.yml

package gentools

import (
	_ "embed"
	"encoding/json"
)

var _ = json.RawMessage(nil)

// GetFieldsKeysInput is the MCP tool input for GET /api/v1/fields/keys (GetFieldsKeys).
// Tool name: signoz_get_fields_keys.
type GetFieldsKeysInput struct {
	Signal          string `json:"signal,omitempty" jsonschema:"query parameter signal"`
	Source          string `json:"source,omitempty" jsonschema:"query parameter source"`
	Limit           int64  `json:"limit,omitempty" jsonschema:"query parameter limit"`
	StartUnixMilli  int64  `json:"startUnixMilli,omitempty" jsonschema:"query parameter startUnixMilli"`
	EndUnixMilli    int64  `json:"endUnixMilli,omitempty" jsonschema:"query parameter endUnixMilli"`
	FieldContext    string `json:"fieldContext,omitempty" jsonschema:"query parameter fieldContext"`
	FieldDataType   string `json:"fieldDataType,omitempty" jsonschema:"query parameter fieldDataType"`
	MetricName      string `json:"metricName,omitempty" jsonschema:"query parameter metricName"`
	MetricNamespace string `json:"metricNamespace,omitempty" jsonschema:"query parameter metricNamespace"`
	SearchText      string `json:"searchText,omitempty" jsonschema:"query parameter searchText"`
}

//go:embed tools/zz_generated_signoz_get_fields_keys.input.json
var rawSchemaGetFieldsKeys []byte

// SchemaGetFieldsKeys is the self-contained JSON Schema for signoz_get_fields_keys,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_get_fields_keys.input.json. Hand it to
// mcp.WithRawInputSchema directly.
var SchemaGetFieldsKeys = ComposeSchema(rawSchemaGetFieldsKeys)

//go:embed tools/zz_generated_signoz_get_fields_keys.output.json
var rawOutputSchemaGetFieldsKeys []byte

// OutputSchemaGetFieldsKeys is the self-contained JSON Schema describing
// the response body of signoz_get_fields_keys (GET /api/v1/fields/keys's success
// status). Composed at init from tools/zz_generated_signoz_get_fields_keys.output.json
// against the same components/ catalogue.
var OutputSchemaGetFieldsKeys = ComposeSchema(rawOutputSchemaGetFieldsKeys)

// GetFieldsValuesInput is the MCP tool input for GET /api/v1/fields/values (GetFieldsValues).
// Tool name: signoz_get_fields_values.
type GetFieldsValuesInput struct {
	Signal          string `json:"signal,omitempty" jsonschema:"query parameter signal"`
	Source          string `json:"source,omitempty" jsonschema:"query parameter source"`
	Limit           int64  `json:"limit,omitempty" jsonschema:"query parameter limit"`
	StartUnixMilli  int64  `json:"startUnixMilli,omitempty" jsonschema:"query parameter startUnixMilli"`
	EndUnixMilli    int64  `json:"endUnixMilli,omitempty" jsonschema:"query parameter endUnixMilli"`
	FieldContext    string `json:"fieldContext,omitempty" jsonschema:"query parameter fieldContext"`
	FieldDataType   string `json:"fieldDataType,omitempty" jsonschema:"query parameter fieldDataType"`
	MetricName      string `json:"metricName,omitempty" jsonschema:"query parameter metricName"`
	MetricNamespace string `json:"metricNamespace,omitempty" jsonschema:"query parameter metricNamespace"`
	SearchText      string `json:"searchText,omitempty" jsonschema:"query parameter searchText"`
	Name            string `json:"name,omitempty" jsonschema:"query parameter name"`
	ExistingQuery   string `json:"existingQuery,omitempty" jsonschema:"query parameter existingQuery"`
}

//go:embed tools/zz_generated_signoz_get_fields_values.input.json
var rawSchemaGetFieldsValues []byte

// SchemaGetFieldsValues is the self-contained JSON Schema for signoz_get_fields_values,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_get_fields_values.input.json. Hand it to
// mcp.WithRawInputSchema directly.
var SchemaGetFieldsValues = ComposeSchema(rawSchemaGetFieldsValues)

//go:embed tools/zz_generated_signoz_get_fields_values.output.json
var rawOutputSchemaGetFieldsValues []byte

// OutputSchemaGetFieldsValues is the self-contained JSON Schema describing
// the response body of signoz_get_fields_values (GET /api/v1/fields/values's success
// status). Composed at init from tools/zz_generated_signoz_get_fields_values.output.json
// against the same components/ catalogue.
var OutputSchemaGetFieldsValues = ComposeSchema(rawOutputSchemaGetFieldsValues)
