// Code generated by cmd/gen-tools. DO NOT EDIT.
// Source: docs/api/openapi.yml

package gentools

import (
	_ "embed"
	"encoding/json"
)

var _ = json.RawMessage(nil)

// HealthzInput is the MCP tool input for GET /api/v2/healthz (Healthz).
// Tool name: signoz_healthz.
type HealthzInput struct {
}

//go:embed tools/zz_generated_signoz_healthz.json
var rawSchemaHealthz []byte

// SchemaHealthz is the self-contained JSON Schema for signoz_healthz,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_healthz.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaHealthz = ComposeSchema(rawSchemaHealthz)

// LivezInput is the MCP tool input for GET /api/v2/livez (Livez).
// Tool name: signoz_livez.
type LivezInput struct {
}

//go:embed tools/zz_generated_signoz_livez.json
var rawSchemaLivez []byte

// SchemaLivez is the self-contained JSON Schema for signoz_livez,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_livez.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaLivez = ComposeSchema(rawSchemaLivez)

// ReadyzInput is the MCP tool input for GET /api/v2/readyz (Readyz).
// Tool name: signoz_readyz.
type ReadyzInput struct {
}

//go:embed tools/zz_generated_signoz_readyz.json
var rawSchemaReadyz []byte

// SchemaReadyz is the self-contained JSON Schema for signoz_readyz,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_readyz.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaReadyz = ComposeSchema(rawSchemaReadyz)
