// Code generated by cmd/gen-tools. DO NOT EDIT.
// Source: docs/api/openapi.yml

package gentools

import (
	_ "embed"
	"encoding/json"
)

var _ = json.RawMessage(nil)

// GetMetricAlertsInput is the MCP tool input for GET /api/v2/metrics/{metric_name}/alerts (GetMetricAlerts).
// Tool name: signoz_get_metric_alerts.
type GetMetricAlertsInput struct {
	MetricName string `json:"metric_name" jsonschema:"path parameter metric_name"`
}

//go:embed tools/zz_generated_signoz_get_metric_alerts.json
var rawSchemaGetMetricAlerts []byte

// SchemaGetMetricAlerts is the self-contained JSON Schema for signoz_get_metric_alerts,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_get_metric_alerts.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaGetMetricAlerts = ComposeSchema(rawSchemaGetMetricAlerts)

// GetMetricAttributesInput is the MCP tool input for GET /api/v2/metrics/{metric_name}/attributes (GetMetricAttributes).
// Tool name: signoz_get_metric_attributes.
type GetMetricAttributesInput struct {
	MetricName string `json:"metric_name" jsonschema:"path parameter metric_name"`
	Start      int64  `json:"start,omitempty" jsonschema:"query parameter start"`
	End        int64  `json:"end,omitempty" jsonschema:"query parameter end"`
}

//go:embed tools/zz_generated_signoz_get_metric_attributes.json
var rawSchemaGetMetricAttributes []byte

// SchemaGetMetricAttributes is the self-contained JSON Schema for signoz_get_metric_attributes,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_get_metric_attributes.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaGetMetricAttributes = ComposeSchema(rawSchemaGetMetricAttributes)

// GetMetricDashboardsInput is the MCP tool input for GET /api/v2/metrics/{metric_name}/dashboards (GetMetricDashboards).
// Tool name: signoz_get_metric_dashboards.
type GetMetricDashboardsInput struct {
	MetricName string `json:"metric_name" jsonschema:"path parameter metric_name"`
}

//go:embed tools/zz_generated_signoz_get_metric_dashboards.json
var rawSchemaGetMetricDashboards []byte

// SchemaGetMetricDashboards is the self-contained JSON Schema for signoz_get_metric_dashboards,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_get_metric_dashboards.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaGetMetricDashboards = ComposeSchema(rawSchemaGetMetricDashboards)

// GetMetricHighlightsInput is the MCP tool input for GET /api/v2/metrics/{metric_name}/highlights (GetMetricHighlights).
// Tool name: signoz_get_metric_highlights.
type GetMetricHighlightsInput struct {
	MetricName string `json:"metric_name" jsonschema:"path parameter metric_name"`
}

//go:embed tools/zz_generated_signoz_get_metric_highlights.json
var rawSchemaGetMetricHighlights []byte

// SchemaGetMetricHighlights is the self-contained JSON Schema for signoz_get_metric_highlights,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_get_metric_highlights.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaGetMetricHighlights = ComposeSchema(rawSchemaGetMetricHighlights)

// GetMetricMetadataInput is the MCP tool input for GET /api/v2/metrics/{metric_name}/metadata (GetMetricMetadata).
// Tool name: signoz_get_metric_metadata.
type GetMetricMetadataInput struct {
	MetricName string `json:"metric_name" jsonschema:"path parameter metric_name"`
}

//go:embed tools/zz_generated_signoz_get_metric_metadata.json
var rawSchemaGetMetricMetadata []byte

// SchemaGetMetricMetadata is the self-contained JSON Schema for signoz_get_metric_metadata,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_get_metric_metadata.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaGetMetricMetadata = ComposeSchema(rawSchemaGetMetricMetadata)

// GetMetricsOnboardingStatusInput is the MCP tool input for GET /api/v2/metrics/onboarding (GetMetricsOnboardingStatus).
// Tool name: signoz_get_metrics_onboarding_status.
type GetMetricsOnboardingStatusInput struct {
}

//go:embed tools/zz_generated_signoz_get_metrics_onboarding_status.json
var rawSchemaGetMetricsOnboardingStatus []byte

// SchemaGetMetricsOnboardingStatus is the self-contained JSON Schema for signoz_get_metrics_onboarding_status,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_get_metrics_onboarding_status.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaGetMetricsOnboardingStatus = ComposeSchema(rawSchemaGetMetricsOnboardingStatus)

// GetMetricsStatsInput is the MCP tool input for POST /api/v2/metrics/stats (GetMetricsStats).
// Tool name: signoz_get_metrics_stats.
type GetMetricsStatsInput struct {
	Body json.RawMessage `json:"body,omitempty" jsonschema:"MetricsexplorertypesStatsRequest"`
}

//go:embed tools/zz_generated_signoz_get_metrics_stats.json
var rawSchemaGetMetricsStats []byte

// SchemaGetMetricsStats is the self-contained JSON Schema for signoz_get_metrics_stats,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_get_metrics_stats.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaGetMetricsStats = ComposeSchema(rawSchemaGetMetricsStats)

// GetMetricsTreemapInput is the MCP tool input for POST /api/v2/metrics/treemap (GetMetricsTreemap).
// Tool name: signoz_get_metrics_treemap.
type GetMetricsTreemapInput struct {
	Body json.RawMessage `json:"body,omitempty" jsonschema:"MetricsexplorertypesTreemapRequest"`
}

//go:embed tools/zz_generated_signoz_get_metrics_treemap.json
var rawSchemaGetMetricsTreemap []byte

// SchemaGetMetricsTreemap is the self-contained JSON Schema for signoz_get_metrics_treemap,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_get_metrics_treemap.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaGetMetricsTreemap = ComposeSchema(rawSchemaGetMetricsTreemap)

// InspectMetricsInput is the MCP tool input for POST /api/v2/metrics/inspect (InspectMetrics).
// Tool name: signoz_inspect_metrics.
type InspectMetricsInput struct {
	Body json.RawMessage `json:"body,omitempty" jsonschema:"MetricsexplorertypesInspectMetricsRequest"`
}

//go:embed tools/zz_generated_signoz_inspect_metrics.json
var rawSchemaInspectMetrics []byte

// SchemaInspectMetrics is the self-contained JSON Schema for signoz_inspect_metrics,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_inspect_metrics.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaInspectMetrics = ComposeSchema(rawSchemaInspectMetrics)

// UpdateMetricMetadataInput is the MCP tool input for POST /api/v2/metrics/{metric_name}/metadata (UpdateMetricMetadata).
// Tool name: signoz_update_metric_metadata.
type UpdateMetricMetadataInput struct {
	MetricName string          `json:"metric_name" jsonschema:"path parameter metric_name"`
	Body       json.RawMessage `json:"body,omitempty" jsonschema:"MetricsexplorertypesUpdateMetricMetadataRequest"`
}

//go:embed tools/zz_generated_signoz_update_metric_metadata.json
var rawSchemaUpdateMetricMetadata []byte

// SchemaUpdateMetricMetadata is the self-contained JSON Schema for signoz_update_metric_metadata,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_update_metric_metadata.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaUpdateMetricMetadata = ComposeSchema(rawSchemaUpdateMetricMetadata)
