// Code generated by cmd/gen-tools. DO NOT EDIT.
// Source: docs/api/openapi.yml

package gentools

import (
	_ "embed"
	"encoding/json"
)

var _ = json.RawMessage(nil)

// CreateServiceAccountInput is the MCP tool input for POST /api/v1/service_accounts (CreateServiceAccount).
// Tool name: signoz_create_service_account.
type CreateServiceAccountInput struct {
	Body json.RawMessage `json:"body,omitempty" jsonschema:"ServiceaccounttypesPostableServiceAccount"`
}

//go:embed tools/zz_generated_signoz_create_service_account.json
var rawSchemaCreateServiceAccount []byte

// SchemaCreateServiceAccount is the self-contained JSON Schema for signoz_create_service_account,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_create_service_account.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaCreateServiceAccount = ComposeSchema(rawSchemaCreateServiceAccount)

// CreateServiceAccountKeyInput is the MCP tool input for POST /api/v1/service_accounts/{id}/keys (CreateServiceAccountKey).
// Tool name: signoz_create_service_account_key.
type CreateServiceAccountKeyInput struct {
	Id   string          `json:"id" jsonschema:"path parameter id"`
	Body json.RawMessage `json:"body,omitempty" jsonschema:"ServiceaccounttypesPostableFactorAPIKey"`
}

//go:embed tools/zz_generated_signoz_create_service_account_key.json
var rawSchemaCreateServiceAccountKey []byte

// SchemaCreateServiceAccountKey is the self-contained JSON Schema for signoz_create_service_account_key,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_create_service_account_key.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaCreateServiceAccountKey = ComposeSchema(rawSchemaCreateServiceAccountKey)

// CreateServiceAccountRoleInput is the MCP tool input for POST /api/v1/service_accounts/{id}/roles (CreateServiceAccountRole).
// Tool name: signoz_create_service_account_role.
type CreateServiceAccountRoleInput struct {
	Id   string          `json:"id" jsonschema:"path parameter id"`
	Body json.RawMessage `json:"body,omitempty" jsonschema:"ServiceaccounttypesPostableServiceAccountRole"`
}

//go:embed tools/zz_generated_signoz_create_service_account_role.json
var rawSchemaCreateServiceAccountRole []byte

// SchemaCreateServiceAccountRole is the self-contained JSON Schema for signoz_create_service_account_role,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_create_service_account_role.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaCreateServiceAccountRole = ComposeSchema(rawSchemaCreateServiceAccountRole)

// DeleteServiceAccountInput is the MCP tool input for DELETE /api/v1/service_accounts/{id} (DeleteServiceAccount).
// Tool name: signoz_delete_service_account.
type DeleteServiceAccountInput struct {
	Id string `json:"id" jsonschema:"path parameter id"`
}

//go:embed tools/zz_generated_signoz_delete_service_account.json
var rawSchemaDeleteServiceAccount []byte

// SchemaDeleteServiceAccount is the self-contained JSON Schema for signoz_delete_service_account,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_delete_service_account.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaDeleteServiceAccount = ComposeSchema(rawSchemaDeleteServiceAccount)

// DeleteServiceAccountRoleInput is the MCP tool input for DELETE /api/v1/service_accounts/{id}/roles/{rid} (DeleteServiceAccountRole).
// Tool name: signoz_delete_service_account_role.
type DeleteServiceAccountRoleInput struct {
	Id  string `json:"id" jsonschema:"path parameter id"`
	Rid string `json:"rid" jsonschema:"path parameter rid"`
}

//go:embed tools/zz_generated_signoz_delete_service_account_role.json
var rawSchemaDeleteServiceAccountRole []byte

// SchemaDeleteServiceAccountRole is the self-contained JSON Schema for signoz_delete_service_account_role,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_delete_service_account_role.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaDeleteServiceAccountRole = ComposeSchema(rawSchemaDeleteServiceAccountRole)

// GetMyServiceAccountInput is the MCP tool input for GET /api/v1/service_accounts/me (GetMyServiceAccount).
// Tool name: signoz_get_my_service_account.
type GetMyServiceAccountInput struct {
}

//go:embed tools/zz_generated_signoz_get_my_service_account.json
var rawSchemaGetMyServiceAccount []byte

// SchemaGetMyServiceAccount is the self-contained JSON Schema for signoz_get_my_service_account,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_get_my_service_account.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaGetMyServiceAccount = ComposeSchema(rawSchemaGetMyServiceAccount)

// GetServiceAccountInput is the MCP tool input for GET /api/v1/service_accounts/{id} (GetServiceAccount).
// Tool name: signoz_get_service_account.
type GetServiceAccountInput struct {
	Id string `json:"id" jsonschema:"path parameter id"`
}

//go:embed tools/zz_generated_signoz_get_service_account.json
var rawSchemaGetServiceAccount []byte

// SchemaGetServiceAccount is the self-contained JSON Schema for signoz_get_service_account,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_get_service_account.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaGetServiceAccount = ComposeSchema(rawSchemaGetServiceAccount)

// GetServiceAccountRolesInput is the MCP tool input for GET /api/v1/service_accounts/{id}/roles (GetServiceAccountRoles).
// Tool name: signoz_get_service_account_roles.
type GetServiceAccountRolesInput struct {
	Id string `json:"id" jsonschema:"path parameter id"`
}

//go:embed tools/zz_generated_signoz_get_service_account_roles.json
var rawSchemaGetServiceAccountRoles []byte

// SchemaGetServiceAccountRoles is the self-contained JSON Schema for signoz_get_service_account_roles,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_get_service_account_roles.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaGetServiceAccountRoles = ComposeSchema(rawSchemaGetServiceAccountRoles)

// ListServiceAccountKeysInput is the MCP tool input for GET /api/v1/service_accounts/{id}/keys (ListServiceAccountKeys).
// Tool name: signoz_list_service_account_keys.
type ListServiceAccountKeysInput struct {
	Id string `json:"id" jsonschema:"path parameter id"`
}

//go:embed tools/zz_generated_signoz_list_service_account_keys.json
var rawSchemaListServiceAccountKeys []byte

// SchemaListServiceAccountKeys is the self-contained JSON Schema for signoz_list_service_account_keys,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_list_service_account_keys.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaListServiceAccountKeys = ComposeSchema(rawSchemaListServiceAccountKeys)

// ListServiceAccountsInput is the MCP tool input for GET /api/v1/service_accounts (ListServiceAccounts).
// Tool name: signoz_list_service_accounts.
type ListServiceAccountsInput struct {
}

//go:embed tools/zz_generated_signoz_list_service_accounts.json
var rawSchemaListServiceAccounts []byte

// SchemaListServiceAccounts is the self-contained JSON Schema for signoz_list_service_accounts,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_list_service_accounts.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaListServiceAccounts = ComposeSchema(rawSchemaListServiceAccounts)

// RevokeServiceAccountKeyInput is the MCP tool input for DELETE /api/v1/service_accounts/{id}/keys/{fid} (RevokeServiceAccountKey).
// Tool name: signoz_revoke_service_account_key.
type RevokeServiceAccountKeyInput struct {
	Id  string `json:"id" jsonschema:"path parameter id"`
	Fid string `json:"fid" jsonschema:"path parameter fid"`
}

//go:embed tools/zz_generated_signoz_revoke_service_account_key.json
var rawSchemaRevokeServiceAccountKey []byte

// SchemaRevokeServiceAccountKey is the self-contained JSON Schema for signoz_revoke_service_account_key,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_revoke_service_account_key.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaRevokeServiceAccountKey = ComposeSchema(rawSchemaRevokeServiceAccountKey)

// UpdateMyServiceAccountInput is the MCP tool input for PUT /api/v1/service_accounts/me (UpdateMyServiceAccount).
// Tool name: signoz_update_my_service_account.
type UpdateMyServiceAccountInput struct {
	Body json.RawMessage `json:"body,omitempty" jsonschema:"ServiceaccounttypesPostableServiceAccount"`
}

//go:embed tools/zz_generated_signoz_update_my_service_account.json
var rawSchemaUpdateMyServiceAccount []byte

// SchemaUpdateMyServiceAccount is the self-contained JSON Schema for signoz_update_my_service_account,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_update_my_service_account.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaUpdateMyServiceAccount = ComposeSchema(rawSchemaUpdateMyServiceAccount)

// UpdateServiceAccountInput is the MCP tool input for PUT /api/v1/service_accounts/{id} (UpdateServiceAccount).
// Tool name: signoz_update_service_account.
type UpdateServiceAccountInput struct {
	Id   string          `json:"id" jsonschema:"path parameter id"`
	Body json.RawMessage `json:"body,omitempty" jsonschema:"ServiceaccounttypesPostableServiceAccount"`
}

//go:embed tools/zz_generated_signoz_update_service_account.json
var rawSchemaUpdateServiceAccount []byte

// SchemaUpdateServiceAccount is the self-contained JSON Schema for signoz_update_service_account,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_update_service_account.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaUpdateServiceAccount = ComposeSchema(rawSchemaUpdateServiceAccount)

// UpdateServiceAccountKeyInput is the MCP tool input for PUT /api/v1/service_accounts/{id}/keys/{fid} (UpdateServiceAccountKey).
// Tool name: signoz_update_service_account_key.
type UpdateServiceAccountKeyInput struct {
	Id   string          `json:"id" jsonschema:"path parameter id"`
	Fid  string          `json:"fid" jsonschema:"path parameter fid"`
	Body json.RawMessage `json:"body,omitempty" jsonschema:"ServiceaccounttypesUpdatableFactorAPIKey"`
}

//go:embed tools/zz_generated_signoz_update_service_account_key.json
var rawSchemaUpdateServiceAccountKey []byte

// SchemaUpdateServiceAccountKey is the self-contained JSON Schema for signoz_update_service_account_key,
// composed at package init by injecting the transitive closure of $refs from
// the components/ catalogue into the skeleton loaded from
// tools/zz_generated_signoz_update_service_account_key.json. Hand it to mcp.WithRawInputSchema
// directly.
var SchemaUpdateServiceAccountKey = ComposeSchema(rawSchemaUpdateServiceAccountKey)
