name: build
on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  binary:
    runs-on: ubuntu-latest
    steps:
      - name: self-checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: go-install
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.GO_VERSION }}
      - name: run-goreleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser-pro
          version: '~> v2'
          args: release --clean
          workdir: ${{ matrix.workdirs }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
